import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #24 (TypeScript)", title: "Styled Component Pattern — Typed", body: "Themed button using CSS variables. Type the wrapper style (CSS custom properties) and use var(--primary) in button style.", usecase: "CSS variables enable theming; typing style objects in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Wrapper style with --primary, --secondary (typed as React.CSSProperties or custom)", "Button style: backgroundColor: 'var(--primary)'", "Render Primary and Secondary buttons"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create a wrapper div with inline style that sets CSS variables: --primary and --secondary. Use style={{ ['--primary']: '#3b82f6', ['--secondary']: '#6b7280' }}.", answer_keywords: ["primary", "secondary", "variable", "style"], seed_code: "export default function ThemedButton() {\n  return (\n    <div style={{ ['--primary']: '#3b82f6', ['--secondary']: '#6b7280', padding: 20 }}>\n      <button>Click</button>\n    </div>\n  )\n}", feedback_correct: "✅ CSS variables defined.", feedback_partial: "Set --primary and --secondary.", feedback_wrong: "style with --primary", expected: "Wrapper with CSS variables" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Style the button with backgroundColor: 'var(--primary)', color: 'white'.", answer_keywords: ["var", "primary", "background", "button"], seed_code: "export default function ThemedButton() {\n  return (\n    <div style={{ ['--primary']: '#3b82f6', ['--secondary']: '#6b7280', padding: 20 }}>\n      <button style={{ backgroundColor: 'var(--primary)', color: 'white', padding: '8px 16px', border: 'none', borderRadius: 6 }}>Primary</button>\n    </div>\n  )\n}", feedback_correct: "✅ Button uses var(--primary).", feedback_partial: "Button style with var(--primary).", feedback_wrong: "backgroundColor: 'var(--primary)'", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add a second button that uses var(--secondary). Export the component.", answer_keywords: ["export", "secondary"], seed_code: "export default function ThemedButton() {\n  return (\n    <div style={{ ['--primary']: '#3b82f6', ['--secondary']: '#6b7280', padding: 20 }}>\n      <button style={{ backgroundColor: 'var(--primary)', color: 'white', padding: '8px 16px', border: 'none', borderRadius: 6 }}>Primary</button>\n      <button style={{ backgroundColor: 'var(--secondary)', color: 'white', marginLeft: 8, padding: '8px 16px', border: 'none', borderRadius: 6 }}>Secondary</button>\n    </div>\n  )\n}", feedback_correct: "✅ Themed buttons with TypeScript complete.", feedback_partial: "Both buttons use variables.", feedback_wrong: "Export and var(--secondary).", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 24, title: "Styled Component Pattern (TS)", shortName: "TS — CSS VARIABLES" });
