import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #22 (TypeScript)", title: "Inline Styles — Typed", body: "Progress bar with dynamic width. Use useState<number>(0) for progress and type the bar style as React.CSSProperties.", usecase: "Typed state and CSSProperties for dynamic styles." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["useState<number>(0) for progress", "Bar style: React.CSSProperties with width: progress + '%'", "Clamp 0–100 with Math.min/Math.max"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create const [progress, setProgress] = useState<number>(0). Render outer div (track) and inner div (bar) with width from progress.", answer_keywords: ["usestate", "number", "progress", "width"], seed_code: "import { useState } from 'react'\n\nexport default function ProgressBar() {\n  const [progress, setProgress] = useState<number>(0)\n  return (\n    <div style={{ width: '100%', height: 20, background: '#eee', borderRadius: 4 }}>\n      <div style={{ width: progress + '%', height: 20, background: '#3b82f6', borderRadius: 4 }} />\n    </div>\n  )\n}", feedback_correct: "✅ Progress state and bar.", feedback_partial: "useState<number> and width from progress.", feedback_wrong: "progress + '%'", expected: "Track and bar with dynamic width" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add buttons +10 and -10. Use setProgress with Math.min(100, p + 10) and Math.max(0, p - 10).", answer_keywords: ["button", "math.min", "math.max", "setprogress"], seed_code: "import { useState } from 'react'\n\nexport default function ProgressBar() {\n  const [progress, setProgress] = useState<number>(0)\n  return (\n    <div>\n      <div style={{ width: '100%', height: 20, background: '#eee', borderRadius: 4 }}>\n        <div style={{ width: progress + '%', height: 20, background: '#3b82f6', borderRadius: 4 }} />\n      </div>\n      <button onClick={() => setProgress(p => Math.min(100, p + 10))}>+10</button>\n      <button onClick={() => setProgress(p => Math.max(0, p - 10))}>-10</button>\n    </div>\n  )\n}", feedback_correct: "✅ Buttons clamp progress.", feedback_partial: "setProgress with clamp.", feedback_wrong: "Math.min and Math.max", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export the component. Optionally type barStyle as React.CSSProperties.", answer_keywords: ["export"], seed_code: "import { useState } from 'react'\n\nexport default function ProgressBar() {\n  const [progress, setProgress] = useState<number>(0)\n  const barStyle: React.CSSProperties = { width: progress + '%', height: 20, background: '#3b82f6', borderRadius: 4 }\n  return (\n    <div>\n      <div style={{ width: '100%', height: 20, background: '#eee', borderRadius: 4 }}>\n        <div style={barStyle} />\n      </div>\n      <button onClick={() => setProgress(p => Math.min(100, p + 10))}>+10</button>\n      <button onClick={() => setProgress(p => Math.max(0, p - 10))}>-10</button>\n    </div>\n  )\n}", feedback_correct: "✅ Inline styles with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 22, title: "Inline Styles (TS)", shortName: "TS — PROGRESS BAR" });
