import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #26 (TypeScript)", title: "Controlled vs Uncontrolled — Typed", body: "Controlled input: useState<string>. Uncontrolled: useRef<HTMLInputElement | null>(null), read .current?.value. Type both patterns.", usecase: "Typing refs and form state in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Controlled: useState<string>(''), value and onChange", "Uncontrolled: useRef<HTMLInputElement | null>(null), ref and defaultValue", "Show both in one component"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Build a controlled input: const [value, setValue] = useState<string>(''). Input with value={value} and onChange. Display value below.", answer_keywords: ["usestate", "string", "value", "onchange", "controlled"], seed_code: "import { useState } from 'react'\n\nexport default function CompareInputs() {\n  const [value, setValue] = useState<string>('')\n  return (\n    <div>\n      <input value={value} onChange={e => setValue(e.target.value)} />\n      <span> → {value}</span>\n    </div>\n  )\n}", feedback_correct: "✅ Controlled input typed.", feedback_partial: "useState<string> and value/onChange.", feedback_wrong: "value={value} onChange", expected: "Controlled input with state" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add uncontrolled input: useRef<HTMLInputElement | null>(null), ref={inputRef}, defaultValue. Button that reads inputRef.current?.value.", answer_keywords: ["useref", "ref", "defaultvalue", "current"], seed_code: "import { useState, useRef } from 'react'\n\nexport default function CompareInputs() {\n  const [value, setValue] = useState<string>('')\n  const inputRef = useRef<HTMLInputElement | null>(null)\n  return (\n    <div>\n      <div>Controlled: <input value={value} onChange={e => setValue(e.target.value)} /> → {value}</div>\n      <div>Uncontrolled: <input ref={inputRef} defaultValue=\"\" /> <button onClick={() => alert(inputRef.current?.value)}>Read</button></div>\n    </div>\n  )\n}", feedback_correct: "✅ Uncontrolled input with typed ref.", feedback_partial: "useRef<HTMLInputElement | null> and ref.", feedback_wrong: "inputRef.current?.value", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add a short comment: Controlled = state is source of truth. Uncontrolled = DOM holds value. Export the component.", answer_keywords: ["comment", "export"], seed_code: "import { useState, useRef } from 'react'\n\n// Controlled: state is source of truth. Uncontrolled: DOM holds value, read on demand.\nexport default function CompareInputs() {\n  const [value, setValue] = useState<string>('')\n  const inputRef = useRef<HTMLInputElement | null>(null)\n  return (\n    <div>\n      <div>Controlled: <input value={value} onChange={e => setValue(e.target.value)} /> → {value}</div>\n      <div>Uncontrolled: <input ref={inputRef} defaultValue=\"\" /> <button onClick={() => alert(inputRef.current?.value)}>Read</button></div>\n    </div>\n  )\n}", feedback_correct: "✅ Controlled vs uncontrolled with TypeScript complete.", feedback_partial: "Comment and export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 26, title: "Controlled vs Uncontrolled (TS)", shortName: "TS — CONTROLLED VS UNCONTROLLED" });
