import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #20 (TypeScript)", title: "Event Handling — Typed", body: "Form where Enter submits and Escape clears. Type the keyboard handler as (e: React.KeyboardEvent<HTMLFormElement>) => void.", usecase: "Typing keyboard events prevents wrong event types." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["useState<string> for value", "onKeyDown: (e: React.KeyboardEvent<HTMLInputElement>) => void or similar", "Check e.key === 'Enter' and e.key === 'Escape'"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create state const [value, setValue] = useState<string>(''). Form with onSubmit that prevents default.", answer_keywords: ["usestate", "string", "form", "onsubmit", "preventdefault"], seed_code: "import { useState } from 'react'\n\nexport default function KeyForm() {\n  const [value, setValue] = useState<string>('')\n  const handleSubmit = () => console.log(value)\n  return <form onSubmit={e => { e.preventDefault(); handleSubmit() }}><input value={value} onChange={e => setValue(e.target.value)} /></form>\n}", feedback_correct: "✅ Form and state typed.", feedback_partial: "useState<string> and form onSubmit.", feedback_wrong: "useState<string> and preventDefault", expected: "Form with submit" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add onKeyDown. When e.key === 'Enter' call submit; when e.key === 'Escape' setValue(''). Type e as React.KeyboardEvent.", answer_keywords: ["onkeydown", "enter", "escape", "key"], seed_code: "import { useState } from 'react'\n\nexport default function KeyForm() {\n  const [value, setValue] = useState<string>('')\n  const handleSubmit = () => console.log(value)\n  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {\n    if (e.key === 'Enter') { e.preventDefault(); handleSubmit() }\n    if (e.key === 'Escape') setValue('')\n  }\n  return (\n    <form onSubmit={e => { e.preventDefault(); handleSubmit() }}>\n      <input value={value} onChange={e => setValue(e.target.value)} onKeyDown={handleKeyDown} placeholder=\"Enter or Esc\" />\n    </form>\n  )\n}", feedback_correct: "✅ Keyboard handler typed.", feedback_partial: "onKeyDown with Enter and Escape.", feedback_wrong: "e.key === 'Enter' and 'Escape'", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "No submit button — submit only via Enter. Export the component.", answer_keywords: ["export"], seed_code: "import { useState } from 'react'\n\nexport default function KeyForm() {\n  const [value, setValue] = useState<string>('')\n  const handleSubmit = () => console.log(value)\n  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {\n    if (e.key === 'Enter') { e.preventDefault(); handleSubmit() }\n    if (e.key === 'Escape') setValue('')\n  }\n  return (\n    <form onSubmit={e => { e.preventDefault(); handleSubmit() }}>\n      <input value={value} onChange={e => setValue(e.target.value)} onKeyDown={handleKeyDown} placeholder=\"Enter or Esc\" />\n    </form>\n  )\n}", feedback_correct: "✅ Event handling with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 20, title: "Event Handling (TS)", shortName: "TS — KEYBOARD" });
