import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #23 (TypeScript)", title: "CSS Modules — Typed", body: "Simulate CSS Modules with a typed styles object. Use Record<string, string> for the styles object so className is type-safe.", usecase: "Typing module-style class maps in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["const styles: Record<string, string> = { card: 'card_xyz' }", "className={styles.card}", "Comment: modules scope class names"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create a component with a div. Use inline styles for padding and border.", answer_keywords: ["div", "style", "padding", "border"], seed_code: "export default function Card() {\n  return <div style={{ padding: 16, border: '1px solid #333' }}>Content</div>\n}", feedback_correct: "✅ Component with inline styles.", feedback_partial: "div with padding and border.", feedback_wrong: "style object", expected: "div with style" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Define const styles: Record<string, string> = { card: 'card' }. Use className={styles.card} on the div.", answer_keywords: ["record", "string", "styles", "classname"], seed_code: "const styles: Record<string, string> = { card: 'card' }\n\nexport default function Card() {\n  return (\n    <div className={styles.card} style={{ padding: 16, border: '1px solid #333' }}>\n      Content\n    </div>\n  )\n}", feedback_correct: "✅ Typed styles object.", feedback_partial: "Record<string, string> and className.", feedback_wrong: "styles.card", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add a comment: CSS Modules scope class names to avoid global clashes. Export the component.", answer_keywords: ["comment", "scope", "export"], seed_code: "// CSS Modules scope class names to avoid global clashes\nconst styles: Record<string, string> = { card: 'card' }\n\nexport default function Card() {\n  return <div className={styles.card} style={{ padding: 16, border: '1px solid #333' }}>Content</div>\n}", feedback_correct: "✅ CSS Modules pattern with TypeScript complete.", feedback_partial: "Comment and export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 23, title: "CSS Modules (TS)", shortName: "TS — CSS MODULES" });
