import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #18 (TypeScript)", title: "PropTypes / TypeScript Interface", body: "UserCard with typed props. Define interface UserCardProps { name: string; age: number; avatar?: string } and use it.", usecase: "Interfaces document and enforce component API in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Interface UserCardProps { name: string; age: number; avatar?: string }", "Use it in the component", "Conditionally render avatar"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface UserCardProps { name: string; age: number }. Render name and age.", answer_keywords: ["interface", "usercardprops", "name", "age"], seed_code: "interface UserCardProps { name: string; age: number }\n\nexport default function UserCard({ name, age }: UserCardProps) {\n  return <div>{name}, {age}</div>\n}", feedback_correct: "✅ UserCardProps defined.", feedback_partial: "interface with name and age.", feedback_wrong: "interface UserCardProps", expected: "UserCardProps and render" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add avatar?: string. Conditionally render img when avatar is provided.", answer_keywords: ["avatar", "optional", "img"], seed_code: "interface UserCardProps { name: string; age: number; avatar?: string }\n\nexport default function UserCard({ name, age, avatar }: UserCardProps) {\n  return (\n    <div>\n      {avatar && <img src={avatar} alt={name} />}\n      <span>{name}, {age}</span>\n    </div>\n  )\n}", feedback_correct: "✅ Optional avatar typed and rendered.", feedback_partial: "avatar?: string and conditional img.", feedback_wrong: "avatar && <img", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export UserCard. Usage: <UserCard name=\"Jane\" age={25} /> or with avatar.", answer_keywords: ["export"], seed_code: "interface UserCardProps { name: string; age: number; avatar?: string }\n\nexport default function UserCard({ name, age, avatar }: UserCardProps) {\n  return (\n    <div>\n      {avatar && <img src={avatar} alt={name} />}\n      <span>{name}, {age}</span>\n    </div>\n  )\n}", feedback_correct: "✅ UserCard with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 18, title: "UserCard / TypeScript (TS)", shortName: "TS — USERCARD" });
