import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #15 (TypeScript)", title: "Children Prop — Typed", body: "Container that wraps children. Type props as { children: React.ReactNode }.", usecase: "React.ReactNode is the standard type for children in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Interface ContainerProps { children: React.ReactNode }", "Use it in the component", "Apply styles to wrapper div"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface ContainerProps { children: React.ReactNode }. Return <div>{children}</div>.", answer_keywords: ["interface", "children", "reactnode"], seed_code: "interface ContainerProps { children: React.ReactNode }\n\nexport default function Container({ children }: ContainerProps) {\n  return <div>{children}</div>\n}", feedback_correct: "✅ Children typed.", feedback_partial: "interface with children: React.ReactNode.", feedback_wrong: "ContainerProps { children: React.ReactNode }", expected: "Interface and div" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add styles to the div: maxWidth, padding, border. Type style as React.CSSProperties if needed.", answer_keywords: ["style", "maxwidth", "padding"], seed_code: "interface ContainerProps { children: React.ReactNode }\n\nexport default function Container({ children }: ContainerProps) {\n  return <div style={{ maxWidth: '600px', padding: 24, border: '1px solid #333', borderRadius: 8 }}>{children}</div>\n}", feedback_correct: "✅ Styled container.", feedback_partial: "style with maxWidth and padding.", feedback_wrong: "style object", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export Container. Usage: <Container><h1>Hi</h1></Container>.", answer_keywords: ["export"], seed_code: "interface ContainerProps { children: React.ReactNode }\n\nexport default function Container({ children }: ContainerProps) {\n  return <div style={{ maxWidth: '600px', padding: 24, border: '1px solid #333', borderRadius: 8 }}>{children}</div>\n}", feedback_correct: "✅ Children Prop with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 15, title: "Children Prop (TS)", shortName: "TS — CONTAINER" });
