import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #28 (TypeScript)", title: "Star Rating Component — Typed", body: "Clickable 5-star rating. Use useState<number>(0) for rating (0–5). Type the star click handler and optional toggle (same star clears).", usecase: "Typed numeric state for ratings." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["useState<number>(0) for rating", "Render 5 clickable elements, filled for i <= rating", "onClick sets rating; optional: rating === i ? 0 : i to clear"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create state: const [rating, setRating] = useState<number>(0). Render 5 buttons. Clicking the i-th one calls setRating(i) (1–5).", answer_keywords: ["usestate", "number", "rating", "setrating", "button", "onclick"], seed_code: "import { useState } from 'react'\n\nexport default function StarRating() {\n  const [rating, setRating] = useState<number>(0)\n  return (\n    <div>\n      {[1,2,3,4,5].map(i => (\n        <button key={i} onClick={() => setRating(i)}>★</button>\n      ))}\n    </div>\n  )\n}", feedback_correct: "✅ Clickable stars set rating.", feedback_partial: "Five elements, onClick sets rating.", feedback_wrong: "setRating(i)", expected: "5 stars, click sets rating" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Show filled vs empty: color or character. Use i <= rating ? 'gold' : '#ccc' for color, or ★ vs ☆.", answer_keywords: ["filled", "empty", "rating", "color"], seed_code: "import { useState } from 'react'\n\nexport default function StarRating() {\n  const [rating, setRating] = useState<number>(0)\n  return (\n    <div>\n      {[1,2,3,4,5].map(i => (\n        <button key={i} onClick={() => setRating(rating === i ? 0 : i)} style={{ fontSize: 24, background: 'none', border: 'none', cursor: 'pointer', color: i <= rating ? 'gold' : '#ccc' }}>\n          ★\n        </button>\n      ))}\n    </div>\n  )\n}", feedback_correct: "✅ Filled/empty by rating.", feedback_partial: "Conditional color by rating.", feedback_wrong: "i <= rating ? 'gold' : '#ccc'", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Display current rating (e.g. 'Rating: {rating}'). Export the component.", answer_keywords: ["display", "export"], seed_code: "import { useState } from 'react'\n\nexport default function StarRating() {\n  const [rating, setRating] = useState<number>(0)\n  return (\n    <div>\n      {[1,2,3,4,5].map(i => (\n        <button key={i} onClick={() => setRating(rating === i ? 0 : i)} style={{ fontSize: 24, background: 'none', border: 'none', cursor: 'pointer', color: i <= rating ? 'gold' : '#ccc' }}>\n          ★\n        </button>\n      ))}\n      <span>Rating: {rating}</span>\n    </div>\n  )\n}", feedback_correct: "✅ Star rating with TypeScript complete.", feedback_partial: "Show rating and export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 28, title: "Star Rating (TS)", shortName: "TS — STAR RATING" });
