import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #5 (TypeScript)", title: "Conditional Rendering with Ternary — Typed", body: "A status card that shows different content based on a boolean. Use useState<boolean> and type the conditional branches.", usecase: "Typing the state that drives conditional render keeps branches type-safe." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use useState<boolean> for isLoggedIn or similar", "Type the setter", "Render different JSX with ternary"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Declare state: const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false).", answer_keywords: ["usestate", "boolean", "isloggedin"], seed_code: "import { useState } from 'react'\n\nexport default function StatusCard() {\n  // Step 1: useState<boolean>\n}", feedback_correct: "✅ Boolean state typed.", feedback_partial: "useState<boolean>.", feedback_wrong: "useState<boolean>(false)", expected: "useState<boolean>" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Use a ternary to show 'Welcome back!' when true and 'Please sign in' when false.", answer_keywords: ["ternary", "isloggedin", "welcome", "sign in"], seed_code: "import { useState } from 'react'\n\nexport default function StatusCard() {\n  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false)\n  return <div>{isLoggedIn ? 'Welcome back!' : 'Please sign in'}</div>\n}", feedback_correct: "✅ Ternary render.", feedback_partial: "Conditional text with ternary.", feedback_wrong: "isLoggedIn ? '...' : '...'", expected: "Ternary for message" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add buttons: Login (sets true) and Logout (sets false). Export the component.", answer_keywords: ["button", "setisloggedin", "login", "logout"], seed_code: "import { useState } from 'react'\n\nexport default function StatusCard() {\n  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false)\n  return (\n    <div>\n      {isLoggedIn ? 'Welcome back!' : 'Please sign in'}\n      <button onClick={() => setIsLoggedIn(true)}>Login</button>\n      <button onClick={() => setIsLoggedIn(false)}>Logout</button>\n    </div>\n  )\n}", feedback_correct: "✅ Conditional rendering with TypeScript complete.", feedback_partial: "Buttons to toggle state.", feedback_wrong: "Login/Logout buttons.", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 5, title: "Conditional Rendering with Ternary (TS)", shortName: "TS — TERNARY" });
