import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #4 (TypeScript)", title: "Multiple State Variables — Typed", body: "Track multiple form fields (e.g. email, password) with separate useState. Type each as useState<string>('').", usecase: "Typing each field prevents mixing types and gives autocomplete." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use useState<string> for email and password", "Type both setters", "Wire controlled inputs"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Declare email and password state, both useState<string>('').", hint: "const [email, setEmail] = useState<string>(''); same for password.", answer_keywords: ["usestate", "string", "email", "password"], seed_code: "import { useState } from 'react'\n\nexport default function MultiState() {\n  // Step 1: email, password useState<string>\n}", feedback_correct: "✅ Both typed as string.", feedback_partial: "Two useState<string>.", feedback_wrong: "useState<string> for each.", expected: "email and password useState<string>" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add two controlled inputs. Use (e: React.ChangeEvent<HTMLInputElement>) => setEmail(e.target.value) or untyped e.", answer_keywords: ["input", "value", "onchange", "setemail", "setpassword"], seed_code: "import { useState } from 'react'\n\nexport default function MultiState() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  // Step 2: two inputs\n}", feedback_correct: "✅ Inputs wired.", feedback_partial: "value and onChange for both.", feedback_wrong: "Two inputs with value and onChange.", expected: "Two controlled inputs" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Return a form or div with both inputs. Export the component.", answer_keywords: ["return", "form", "export"], seed_code: "import { useState } from 'react'\n\nexport default function MultiState() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  return (\n    <form>\n      <input value={email} onChange={e => setEmail(e.target.value)} />\n      <input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" />\n    </form>\n  )\n}", feedback_correct: "✅ Multiple state with TypeScript complete.", feedback_partial: "Form with both inputs.", feedback_wrong: "Return form and export.", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 4, title: "Multiple State Variables (TS)", shortName: "TS — MULTIPLE STATE" });
