import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #27 (TypeScript)", title: "Simple Todo List — Typed", body: "Add, complete, delete todos with useState. Type state as array of { id: number; text: string; done: boolean }. Full CRUD with typed handlers.", usecase: "Typing list state and item shape is essential for todo-style UIs." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["interface Todo { id: number; text: string; done: boolean }", "useState<Todo[]>([]) and useState<string> for input", "Add, toggle (map), delete (filter) with typed setters"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create state: const [todos, setTodos] = useState<Todo[]>([]) and const [text, setText] = useState<string>(''). Add input and button to add a todo: { id: Date.now(), text, done: false }.", answer_keywords: ["usestate", "todo", "todos", "text", "id", "done", "add"], seed_code: "import { useState } from 'react'\n\ninterface Todo { id: number; text: string; done: boolean }\n\nexport default function TodoList() {\n  const [todos, setTodos] = useState<Todo[]>([])\n  const [text, setText] = useState<string>('')\n  const add = () => { if (!text.trim()) return; setTodos([...todos, { id: Date.now(), text, done: false }]); setText('') }\n  return (\n    <div>\n      <input value={text} onChange={e => setText(e.target.value)} />\n      <button onClick={add}>Add</button>\n    </div>\n  )\n}", feedback_correct: "✅ Add todo with typed state.", feedback_partial: "Todo interface and add handler.", feedback_wrong: "setTodos([...todos, { id, text, done: false }])", expected: "Add handler and Todo type" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Render the list. Each item: text, checkbox (checked={todo.done}, onChange to toggle), delete button. Toggle: setTodos(todos.map(t => t.id === id ? { ...t, done: !t.done } : t)). Delete: setTodos(todos.filter(t => t.id !== id)).", answer_keywords: ["map", "filter", "toggle", "delete", "checkbox"], seed_code: "import { useState } from 'react'\n\ninterface Todo { id: number; text: string; done: boolean }\n\nexport default function TodoList() {\n  const [todos, setTodos] = useState<Todo[]>([])\n  const [text, setText] = useState<string>('')\n  const add = () => { if (!text.trim()) return; setTodos([...todos, { id: Date.now(), text, done: false }]); setText('') }\n  const toggle = (id: number) => setTodos(todos.map(t => t.id === id ? { ...t, done: !t.done } : t))\n  const del = (id: number) => setTodos(todos.filter(t => t.id !== id))\n  return (\n    <div>\n      <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} />\n      <button onClick={add}>Add</button>\n      <ul>\n        {todos.map(t => (\n          <li key={t.id} style={{ textDecoration: t.done ? 'line-through' : 'none' }}>\n            <input type=\"checkbox\" checked={t.done} onChange={() => toggle(t.id)} />\n            {t.text}\n            <button onClick={() => del(t.id)}>Delete</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  )\n}", feedback_correct: "✅ Toggle and delete typed.", feedback_partial: "List with toggle and delete.", feedback_wrong: "map for toggle, filter for delete", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Style completed items (textDecoration: 'line-through'). Export the component.", answer_keywords: ["linethrough", "export"], seed_code: "import { useState } from 'react'\n\ninterface Todo { id: number; text: string; done: boolean }\n\nexport default function TodoList() {\n  const [todos, setTodos] = useState<Todo[]>([])\n  const [text, setText] = useState<string>('')\n  const add = () => { if (!text.trim()) return; setTodos([...todos, { id: Date.now(), text, done: false }]); setText('') }\n  const toggle = (id: number) => setTodos(todos.map(t => t.id === id ? { ...t, done: !t.done } : t))\n  const del = (id: number) => setTodos(todos.filter(t => t.id !== id))\n  return (\n    <div>\n      <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} />\n      <button onClick={add}>Add</button>\n      <ul>\n        {todos.map(t => (\n          <li key={t.id} style={{ textDecoration: t.done ? 'line-through' : 'none' }}>\n            <input type=\"checkbox\" checked={t.done} onChange={() => toggle(t.id)} />\n            {t.text}\n            <button onClick={() => del(t.id)}>Delete</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  )\n}", feedback_correct: "✅ Simple Todo List with TypeScript complete.", feedback_partial: "Completed style and export.", feedback_wrong: "Export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 27, title: "Simple Todo List (TS)", shortName: "TS — TODO LIST" });
