import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #21 (TypeScript)", title: "Conditional Classes — Typed", body: "Apply different CSS classes based on state. Use useState<boolean>(false) for isActive and type the button className as string.", usecase: "Typed state and string class names in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["useState<boolean>(false) for isActive", "className as string: isActive ? 'btn active' : 'btn'", "Apply to button"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create const [isActive, setIsActive] = useState<boolean>(false). Render a button that toggles isActive on click.", answer_keywords: ["usestate", "boolean", "isactive", "onclick"], seed_code: "import { useState } from 'react'\n\nexport default function ToggleButton() {\n  const [isActive, setIsActive] = useState<boolean>(false)\n  return <button onClick={() => setIsActive(!isActive)}>Toggle</button>\n}", feedback_correct: "✅ Toggle state typed.", feedback_partial: "useState<boolean> and onClick.", feedback_wrong: "useState<boolean>(false)", expected: "Button that toggles isActive" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add className that includes 'active' when isActive. Use string: 'btn ' + (isActive ? 'active' : '').", answer_keywords: ["classname", "active", "isactive"], seed_code: "import { useState } from 'react'\n\nexport default function ToggleButton() {\n  const [isActive, setIsActive] = useState<boolean>(false)\n  return (\n    <button onClick={() => setIsActive(!isActive)} className={'btn ' + (isActive ? 'active' : '')}>\n      Toggle\n    </button>\n  )\n}", feedback_correct: "✅ Conditional class applied.", feedback_partial: "className with isActive ? 'active' : ''.", feedback_wrong: "className with active when isActive", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add inline style for active state (e.g. backgroundColor). Export the component.", answer_keywords: ["style", "background", "export"], seed_code: "import { useState } from 'react'\n\nexport default function ToggleButton() {\n  const [isActive, setIsActive] = useState<boolean>(false)\n  return (\n    <button\n      onClick={() => setIsActive(!isActive)}\n      className={'btn ' + (isActive ? 'active' : '')}\n      style={{ backgroundColor: isActive ? '#3b82f6' : '#ccc', color: isActive ? '#fff' : '#333' }}\n    >\n      Toggle\n    </button>\n  )\n}", feedback_correct: "✅ Conditional classes with TypeScript complete.", feedback_partial: "Style and export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 21, title: "Conditional Classes (TS)", shortName: "TS — TOGGLE CLASS" });
