import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #10 (TypeScript)", title: "Multiple State Vars — Typed", body: "Registration form: name, email, password, confirmPassword. Type all as useState<string>('').", usecase: "Consistent string typing across many fields." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Four useState<string> for the four fields", "Type all change handlers", "Optional: type match message as boolean or string"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Declare name, email, password, confirmPassword as useState<string>('').", answer_keywords: ["usestate", "string", "name", "email", "password"], seed_code: "import { useState } from 'react'\n\nexport default function RegistrationForm() {\n  // Step 1: four useState<string>\n}", feedback_correct: "✅ Four fields typed.", feedback_partial: "useState<string> for each.", feedback_wrong: "Four useState<string>", expected: "name, email, password, confirmPassword state" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add four controlled inputs. Wire value and onChange for each.", answer_keywords: ["input", "value", "onchange"], seed_code: "import { useState } from 'react'\n\nexport default function RegistrationForm() {\n  const [name, setName] = useState<string>('')\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  const [confirmPassword, setConfirmPassword] = useState<string>('')\n  return (\n    <form>\n      <input value={name} onChange={e => setName(e.target.value)} placeholder=\"Name\" />\n      <input value={email} onChange={e => setEmail(e.target.value)} type=\"email\" />\n      <input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" />\n      <input value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} type=\"password\" placeholder=\"Confirm\" />\n    </form>\n  )\n}", feedback_correct: "✅ All inputs wired.", feedback_partial: "Four inputs with value and onChange.", feedback_wrong: "Controlled inputs", expected: "Four inputs" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Optionally show 'Passwords match' when password === confirmPassword. Export the component.", answer_keywords: ["match", "export", "password"], seed_code: "import { useState } from 'react'\n\nexport default function RegistrationForm() {\n  const [name, setName] = useState<string>('')\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  const [confirmPassword, setConfirmPassword] = useState<string>('')\n  return (\n    <form>\n      <input value={name} onChange={e => setName(e.target.value)} placeholder=\"Name\" />\n      <input value={email} onChange={e => setEmail(e.target.value)} type=\"email\" />\n      <input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" />\n      <input value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} type=\"password\" placeholder=\"Confirm\" />\n      {password && confirmPassword && (password === confirmPassword ? <p>Passwords match</p> : <p>Passwords do not match</p>)}\n    </form>\n  )\n}", feedback_correct: "✅ Multiple State Vars with TypeScript complete.", feedback_partial: "Match message and export.", feedback_wrong: "Export and optional match.", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 10, title: "Multiple State Vars (TS)", shortName: "TS — REGISTRATION" });
