import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #29 (TypeScript)", title: "Accordion — Typed", body: "Single-open accordion. State: openIndex as number | null. Type panels as { title: string; content: string }[].", usecase: "Typing openIndex as number | null and panel shape." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["useState<number | null>(null) for openIndex", "interface Panel { title: string; content: string }; panels: Panel[]", "Show content when openIndex === i; click toggles"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create state: const [openIndex, setOpenIndex] = useState<number | null>(null). Define panels array with title and content. Render clickable panel titles.", answer_keywords: ["usestate", "null", "openindex", "panel", "click"], seed_code: "import { useState } from 'react'\n\nconst panels: { title: string; content: string }[] = [{ title: 'Panel 1', content: 'Content 1' }, { title: 'Panel 2', content: 'Content 2' }, { title: 'Panel 3', content: 'Content 3' }]\n\nexport default function Accordion() {\n  const [openIndex, setOpenIndex] = useState<number | null>(null)\n  return (\n    <div>\n      {panels.map((p, i) => (\n        <div key={i}>\n          <div onClick={() => setOpenIndex(i)} style={{ cursor: 'pointer', padding: 8, border: '1px solid #333' }}>{p.title}</div>\n        </div>\n      ))}\n    </div>\n  )\n}", feedback_correct: "✅ Headers set openIndex.", feedback_partial: "useState<number | null> and clickable headers.", feedback_wrong: "setOpenIndex(i)", expected: "Headers that set openIndex" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "For each panel, show content only when openIndex === i. Single-open: clicking another header closes the previous.", answer_keywords: ["openindex", "content", "conditional"], seed_code: "import { useState } from 'react'\n\nconst panels: { title: string; content: string }[] = [{ title: 'Panel 1', content: 'Content 1' }, { title: 'Panel 2', content: 'Content 2' }]\n\nexport default function Accordion() {\n  const [openIndex, setOpenIndex] = useState<number | null>(null)\n  return (\n    <div>\n      {panels.map((p, i) => (\n        <div key={i}>\n          <div onClick={() => setOpenIndex(i)} style={{ cursor: 'pointer', padding: 8, border: '1px solid #333' }}>{p.title}</div>\n          {openIndex === i && <div style={{ padding: 8, border: '1px solid #333', borderTop: 'none' }}>{p.content}</div>}\n        </div>\n      ))}\n    </div>\n  )\n}", feedback_correct: "✅ Single-open accordion.", feedback_partial: "Show content when openIndex === i.", feedback_wrong: "openIndex === i && content", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Clicking the open panel again closes it: setOpenIndex(openIndex === i ? null : i). Export the component.", answer_keywords: ["toggle", "null", "export"], seed_code: "import { useState } from 'react'\n\nconst panels: { title: string; content: string }[] = [{ title: 'Panel 1', content: 'Content 1' }, { title: 'Panel 2', content: 'Content 2' }, { title: 'Panel 3', content: 'Content 3' }]\n\nexport default function Accordion() {\n  const [openIndex, setOpenIndex] = useState<number | null>(null)\n  return (\n    <div>\n      {panels.map((p, i) => (\n        <div key={i}>\n          <div onClick={() => setOpenIndex(openIndex === i ? null : i)} style={{ cursor: 'pointer', padding: 8, border: '1px solid #333' }}>{p.title}</div>\n          {openIndex === i && <div style={{ padding: 8, border: '1px solid #333', borderTop: 'none' }}>{p.content}</div>}\n        </div>\n      ))}\n    </div>\n  )\n}", feedback_correct: "✅ Accordion with TypeScript complete.", feedback_partial: "Toggle close and export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 29, title: "Accordion (TS)", shortName: "TS — ACCORDION" });
