import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #16 (TypeScript)", title: "Conditional Rendering — Typed", body: "Show different UI for loading, error, empty, data. Type status as union: 'loading' | 'error' | 'empty' | 'data'.", usecase: "Union types make state machines explicit and safe." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["type Status = 'loading' | 'error' | 'empty' | 'data'", "useState<Status>('loading')", "Render different JSX per status"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define type Status = 'loading' | 'error' | 'empty' | 'data'. Use useState<Status>('loading').", answer_keywords: ["type", "status", "usestate", "loading"], seed_code: "type Status = 'loading' | 'error' | 'empty' | 'data'\n\nimport { useState } from 'react'\nexport default function DataView() {\n  const [status, setStatus] = useState<Status>('loading')\n  if (status === 'loading') return <p>Loading...</p>\n  return null\n}", feedback_correct: "✅ Status union typed.", feedback_partial: "type Status and useState<Status>.", feedback_wrong: "type Status = 'loading' | ...", expected: "Status type and state" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add branches for error, empty, data. Return different JSX for each.", answer_keywords: ["error", "empty", "data", "return"], seed_code: "type Status = 'loading' | 'error' | 'empty' | 'data'\nimport { useState } from 'react'\nexport default function DataView() {\n  const [status, setStatus] = useState<Status>('loading')\n  if (status === 'loading') return <p>Loading...</p>\n  if (status === 'error') return <p>Something went wrong</p>\n  if (status === 'empty') return <p>No data</p>\n  return <p>Data loaded</p>\n}", feedback_correct: "✅ All branches typed.", feedback_partial: "Branches for each status.", feedback_wrong: "if status === 'error' etc.", expected: "Four branches" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Optionally add buttons to set status so you can see each state. Export.", answer_keywords: ["setstatus", "button", "export"], seed_code: "type Status = 'loading' | 'error' | 'empty' | 'data'\nimport { useState } from 'react'\nexport default function DataView() {\n  const [status, setStatus] = useState<Status>('loading')\n  if (status === 'loading') return <div><p>Loading...</p><button onClick={() => setStatus('data')}>Done</button></div>\n  if (status === 'error') return <p>Error</p>\n  if (status === 'empty') return <p>No data</p>\n  return <p>Data loaded</p>\n}", feedback_correct: "✅ Conditional rendering with TypeScript complete.", feedback_partial: "Buttons and export.", feedback_wrong: "setStatus with valid Status", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 16, title: "Conditional Rendering (TS)", shortName: "TS — CONDITIONAL" });
