import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #13 (TypeScript)", title: "Props Drilling — Typed", body: "Pass data 3 levels deep. Type the value prop as string (or a union) so each layer has typed props.", usecase: "Typed props at each level document the contract." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Type Layer1/2/3 props: { value: string }", "Pass value down and render in Layer3", "Optional: type label as string"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create Layer3 with props typed as { value: string }. Render <span>{value}</span>. Layer2 and Layer1 pass value down.", answer_keywords: ["interface", "value", "string", "layer3"], seed_code: "interface LayerProps { value: string }\nfunction Layer3({ value }: LayerProps) { return <span>{value}</span> }\nfunction Layer2({ value }: LayerProps) { return <Layer3 value={value} /> }\nfunction Layer1({ value }: LayerProps) { return <Layer2 value={value} /> }\nexport default function App() { return <Layer1 value=\"hello\" /> }", feedback_correct: "✅ Typed props through layers.", feedback_partial: "Type value in each layer.", feedback_wrong: "interface with value: string", expected: "LayerProps with value: string" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add label?: string to the props type. Pass it through Layer1 and Layer2; only Layer3 renders it.", answer_keywords: ["label", "optional", "layer"], seed_code: "interface LayerProps { value: string; label?: string }\nfunction Layer3({ value, label }: LayerProps) { return <span>{label}: {value}</span> }\nfunction Layer2({ value, label }: LayerProps) { return <Layer3 value={value} label={label} /> }\nfunction Layer1({ value, label }: LayerProps) { return <Layer2 value={value} label={label} /> }\nexport default function App() { return <Layer1 value=\"hello\" label=\"Msg\" /> }", feedback_correct: "✅ Optional label typed and passed.", feedback_partial: "label?: string in interface.", feedback_wrong: "label optional", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export App. Add a short comment on why drilling is painful (middle layers must declare props they do not use).", answer_keywords: ["export", "comment"], seed_code: "// Drilling: middle layers must declare and forward props they don't use.\ninterface LayerProps { value: string; label?: string }\nfunction Layer3({ value, label }: LayerProps) { return <span>{label}: {value}</span> }\nfunction Layer2({ value, label }: LayerProps) { return <Layer3 value={value} label={label} /> }\nfunction Layer1({ value, label }: LayerProps) { return <Layer2 value={value} label={label} /> }\nexport default function App() { return <Layer1 value=\"hello\" label=\"Msg\" /> }", feedback_correct: "✅ Props drilling with TypeScript complete.", feedback_partial: "Export and comment.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 13, title: "Props Drilling (TS)", shortName: "TS — PROPS DRILLING" });
