import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #30 (TypeScript)", title: "Image Gallery — Typed", body: "Grid of images with click-to-enlarge modal. State: selectedImage as string | null. Type the image URL array as string[].", usecase: "Typing modal state as string | null for image URLs." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["useState<string | null>(null) for selectedImage", "images: string[] (URLs)", "Grid of thumbnails; modal when selectedImage is set; close sets null"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create state: const [selectedImage, setSelectedImage] = useState<string | null>(null). Define images: string[]. Render a grid of clickable images.", answer_keywords: ["usestate", "string", "null", "selectedimage", "grid", "onclick"], seed_code: "import { useState } from 'react'\n\nconst images: string[] = ['https://picsum.photos/200/200?1', 'https://picsum.photos/200/200?2', 'https://picsum.photos/200/200?3']\n\nexport default function ImageGallery() {\n  const [selectedImage, setSelectedImage] = useState<string | null>(null)\n  return (\n    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>\n      {images.map((url, i) => (\n        <img key={i} src={url} alt=\"\" onClick={() => setSelectedImage(url)} style={{ width: '100%', cursor: 'pointer' }} />\n      ))}\n    </div>\n  )\n}", feedback_correct: "✅ Grid and typed state.", feedback_partial: "useState<string | null> and grid of images.", feedback_wrong: "setSelectedImage(url)", expected: "Grid + click sets selectedImage" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "When selectedImage is not null, render a modal: fixed overlay with large image and close button. Clicking close sets setSelectedImage(null).", answer_keywords: ["modal", "fixed", "overlay", "close", "button"], seed_code: "import { useState } from 'react'\n\nconst images: string[] = ['https://picsum.photos/200/200?1', 'https://picsum.photos/200/200?2', 'https://picsum.photos/200/200?3']\n\nexport default function ImageGallery() {\n  const [selectedImage, setSelectedImage] = useState<string | null>(null)\n  return (\n    <div>\n      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>\n        {images.map((url, i) => <img key={i} src={url} alt=\"\" onClick={() => setSelectedImage(url)} style={{ width: '100%', cursor: 'pointer' }} />)}\n      </div>\n      {selectedImage && (\n        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>\n          <img src={selectedImage} alt=\"\" style={{ maxWidth: '90%', maxHeight: '90%' }} />\n          <button onClick={() => setSelectedImage(null)} style={{ position: 'absolute', top: 16, right: 16 }}>Close</button>\n        </div>\n      )}\n    </div>\n  )\n}", feedback_correct: "✅ Modal with close.", feedback_partial: "Overlay with image and close button.", feedback_wrong: "selectedImage && overlay", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Clicking the overlay background closes the modal. Use e.stopPropagation() on the image so clicking it does not close. Export the component.", answer_keywords: ["stopPropagation", "overlay", "export"], seed_code: "import { useState } from 'react'\n\nconst images: string[] = ['https://picsum.photos/200/200?1', 'https://picsum.photos/200/200?2', 'https://picsum.photos/200/200?3']\n\nexport default function ImageGallery() {\n  const [selectedImage, setSelectedImage] = useState<string | null>(null)\n  return (\n    <div>\n      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>\n        {images.map((url, i) => <img key={i} src={url} alt=\"\" onClick={() => setSelectedImage(url)} style={{ width: '100%', cursor: 'pointer' }} />)}\n      </div>\n      {selectedImage && (\n        <div onClick={() => setSelectedImage(null)} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>\n          <img src={selectedImage} alt=\"\" onClick={e => e.stopPropagation()} style={{ maxWidth: '90%', maxHeight: '90%' }} />\n          <button onClick={() => setSelectedImage(null)} style={{ position: 'absolute', top: 16, right: 16 }}>Close</button>\n        </div>\n      )}\n    </div>\n  )\n}", feedback_correct: "✅ Image gallery with TypeScript complete.", feedback_partial: "Overlay click and export.", feedback_wrong: "stopPropagation on image", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 30, title: "Image Gallery (TS)", shortName: "TS — IMAGE GALLERY" });
