import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #11 (TypeScript)", title: "Reusable Button — Typed", body: "Button with label, onClick, variant, disabled. Define interface ButtonProps and use it in the component.", usecase: "Typed props are the core of reusable components in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Interface ButtonProps { label: string; onClick: () => void; variant?: string; disabled?: boolean }", "Use it in the function signature", "Apply styles from variant"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface ButtonProps with label: string, onClick: () => void, variant?: string, disabled?: boolean. Use it in the component.", answer_keywords: ["interface", "buttonprops", "label", "onclick"], seed_code: "interface ButtonProps { label: string; onClick: () => void; variant?: string; disabled?: boolean }\n\nexport default function Button({ label, onClick, variant, disabled }: ButtonProps) {\n  return <button onClick={onClick} disabled={disabled}>{label}</button>\n}", feedback_correct: "✅ Props interface defined.", feedback_partial: "interface ButtonProps and destructured props.", feedback_wrong: "interface ButtonProps { label: string; onClick: () => void }", expected: "ButtonProps interface" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add styles based on variant. Use Record<string, React.CSSProperties> or const styles.", answer_keywords: ["variant", "style", "record", "primary"], seed_code: "interface ButtonProps { label: string; onClick: () => void; variant?: string; disabled?: boolean }\n\nexport default function Button({ label, onClick, variant = 'primary', disabled }: ButtonProps) {\n  const styles: Record<string, React.CSSProperties> = { primary: { background: '#3b82f6', color: '#fff' }, secondary: { background: '#6b7280', color: '#fff' } }\n  return <button onClick={onClick} disabled={disabled} style={styles[variant] || styles.primary}>{label}</button>\n}", feedback_correct: "✅ Variant styles typed.", feedback_partial: "Style object from variant.", feedback_wrong: "styles[variant]", expected: "Typed styles object" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "When disabled, apply opacity. Export the component.", answer_keywords: ["disabled", "opacity", "export"], seed_code: "interface ButtonProps { label: string; onClick: () => void; variant?: string; disabled?: boolean }\n\nexport default function Button({ label, onClick, variant = 'primary', disabled = false }: ButtonProps) {\n  const styles: Record<string, React.CSSProperties> = { primary: { background: '#3b82f6', color: '#fff' }, secondary: { background: '#6b7280', color: '#fff' } }\n  return <button onClick={onClick} disabled={disabled} style={{ ...(styles[variant] || styles.primary), opacity: disabled ? 0.6 : 1 }}>{label}</button>\n}", feedback_correct: "✅ Reusable Button with TypeScript complete.", feedback_partial: "disabled opacity and export.", feedback_wrong: "opacity when disabled", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 11, title: "Reusable Button (TS)", shortName: "TS — BUTTON" });
