import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #17 (TypeScript)", title: "List Rendering — Typed", body: "Render a list of products. Define interface Product { id: number; name: string; price: number } and type the array and map callback.", usecase: "Typing list items and map callback prevents shape errors." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Interface Product { id: number; name: string; price: number }", "const products: Product[] = [...]", "map with (item: Product) => ..."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface Product { id: number; name: string; price: number }. Create products: Product[] and map to divs with key.", answer_keywords: ["interface", "product", "id", "name", "price", "map", "key"], seed_code: "interface Product { id: number; name: string; price: number }\nconst products: Product[] = [{ id: 1, name: 'Apple', price: 1 }, { id: 2, name: 'Bread', price: 2 }]\n\nexport default function ProductList() {\n  return <div>{products.map((p: Product) => <div key={p.id}>{p.name} - {p.price}</div>)}</div>\n}", feedback_correct: "✅ Product interface and typed map.", feedback_partial: "interface Product and products: Product[].", feedback_wrong: "interface Product { id, name, price }", expected: "Product[] and map with key" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Ensure key={item.id} and the callback parameter is typed as Product.", answer_keywords: ["key", "product", "item"], seed_code: "interface Product { id: number; name: string; price: number }\nconst products: Product[] = [{ id: 1, name: 'Apple', price: 1 }, { id: 2, name: 'Bread', price: 2 }]\n\nexport default function ProductList() {\n  return <div>{products.map((item: Product) => <div key={item.id}>{item.name} - {item.price}</div>)}</div>\n}", feedback_correct: "✅ Typed list with keys.", feedback_partial: "key and Product type in map.", feedback_wrong: "map((item: Product) =>", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add a comment: keys help React reconcile the list. Export the component.", answer_keywords: ["comment", "export"], seed_code: "// Keys help React match list items across re-renders.\ninterface Product { id: number; name: string; price: number }\nconst products: Product[] = [{ id: 1, name: 'Apple', price: 1 }, { id: 2, name: 'Bread', price: 2 }]\n\nexport default function ProductList() {\n  return <div>{products.map((item: Product) => <div key={item.id}>{item.name} - {item.price}</div>)}</div>\n}", feedback_correct: "✅ List rendering with TypeScript complete.", feedback_partial: "Comment and export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 17, title: "List Rendering (TS)", shortName: "TS — LIST" });
