import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #7 (TypeScript)", title: "useEffect & Side Effects — Typed", body: "Use useEffect with typed dependencies. Type the state that the effect reads and ensure the effect callback is typed.", usecase: "Typing effect dependencies and state keeps side effects predictable." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use useState<number> or similar and useEffect", "Type the dependency array", "Optionally type the cleanup return"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Declare state: const [count, setCount] = useState<number>(0). Add useEffect that logs count when it changes.", answer_keywords: ["usestate", "useeffect", "count", "dependency"], seed_code: "import { useState, useEffect } from 'react'\n\nexport default function EffectDemo() {\n  const [count, setCount] = useState<number>(0)\n  useEffect(() => { console.log(count) }, [count])\n  return <button onClick={() => setCount(c => c + 1)}>Count: {count}</button>\n}", feedback_correct: "✅ Effect with typed state.", feedback_partial: "useEffect with [count].", feedback_wrong: "useEffect(() => {...}, [count])", expected: "useState<number> and useEffect" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add a cleanup in the effect (e.g. return () => {}). TypeScript infers the return type.", answer_keywords: ["return", "cleanup", "effect"], seed_code: "import { useState, useEffect } from 'react'\n\nexport default function EffectDemo() {\n  const [count, setCount] = useState<number>(0)\n  useEffect(() => {\n    const id = setInterval(() => setCount(c => c + 1), 1000)\n    return () => clearInterval(id)\n  }, [])\n  return <div>{count}</div>\n}", feedback_correct: "✅ Effect with cleanup.", feedback_partial: "return cleanup function.", feedback_wrong: "return () => clearInterval(...)", expected: "Cleanup in useEffect" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export the component. Ensure dependency array is correctly typed (e.g. [count] as const if needed).", answer_keywords: ["export", "dependency"], seed_code: "import { useState, useEffect } from 'react'\n\nexport default function EffectDemo() {\n  const [count, setCount] = useState<number>(0)\n  useEffect(() => {\n    document.title = String(count)\n    return () => { document.title = '' }\n  }, [count])\n  return <button onClick={() => setCount(c => c + 1)}>{count}</button>\n}", feedback_correct: "✅ useEffect with TypeScript complete.", feedback_partial: "Export and deps.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 7, title: "useEffect & Side Effects (TS)", shortName: "TS — USEEFFECT" });
