import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #14 (TypeScript)", title: "Default Props — Typed", body: "Avatar with default props for size and image. Use interface AvatarProps with optional props and default parameters.", usecase: "Optional props with defaults keep components flexible and typed." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Interface AvatarProps { image?: string; size?: number }", "Use default parameters in destructuring or in the type", "Render img with typed dimensions"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface AvatarProps { image?: string; size?: number }. Component: ({ image = 'https://via.placeholder.com/40', size = 40 }: AvatarProps).", answer_keywords: ["interface", "avatarprops", "image", "size", "optional"], seed_code: "interface AvatarProps { image?: string; size?: number }\n\nexport default function Avatar({ image = 'https://via.placeholder.com/40', size = 40 }: AvatarProps) {\n  return <img src={image} alt=\"Avatar\" style={{ width: size, height: size, borderRadius: '50%' }} />\n}", feedback_correct: "✅ AvatarProps with optional and defaults.", feedback_partial: "interface with image? and size?.", feedback_wrong: "AvatarProps { image?: string; size?: number }", expected: "Interface and defaults" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Render img with src={image}, alt='Avatar', style with width and height from size.", answer_keywords: ["img", "src", "style", "width", "height"], seed_code: "interface AvatarProps { image?: string; size?: number }\n\nexport default function Avatar({ image = 'https://via.placeholder.com/40', size = 40 }: AvatarProps) {\n  return <img src={image} alt=\"Avatar\" style={{ width: size, height: size, borderRadius: '50%' }} />\n}", feedback_correct: "✅ Typed dimensions.", feedback_partial: "img with size from prop.", feedback_wrong: "style width/height", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export Avatar. When called with no props it shows placeholder at 40x40.", answer_keywords: ["export", "default"], seed_code: "interface AvatarProps { image?: string; size?: number }\n\nexport default function Avatar({ image = 'https://via.placeholder.com/40', size = 40 }: AvatarProps) {\n  return <img src={image} alt=\"Avatar\" style={{ width: size, height: size, borderRadius: '50%' }} />\n}", feedback_correct: "✅ Default Props with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 14, title: "Default Props (TS)", shortName: "TS — AVATAR" });
