import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #8 (TypeScript)", title: "Forms & Validation — Typed", body: "Login form with email/password. Type state as string, type errors as string or Record<string, string>, and type the submit handler.", usecase: "Typed form state and error state scale to large forms." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use useState<string> for fields and useState for errors", "Type e in onSubmit as React.FormEvent", "Optional: type errors as { email?: string; password?: string }"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Declare email, password (useState<string>), and optionally errors. Type the state.", answer_keywords: ["usestate", "string", "email", "password"], seed_code: "import { useState } from 'react'\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  // Step 1: state\n}", feedback_correct: "✅ Form state typed.", feedback_partial: "useState<string> for email and password.", feedback_wrong: "email and password state", expected: "useState<string> for both" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add form with onSubmit. Type the handler: (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); ... }.", answer_keywords: ["form", "onsubmit", "preventdefault"], seed_code: "import { useState } from 'react'\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); console.log(email, password) }\n  return <form onSubmit={handleSubmit}><input value={email} onChange={e => setEmail(e.target.value)} /><input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" /><button type=\"submit\">Submit</button></form>\n}", feedback_correct: "✅ Form and handler typed.", feedback_partial: "onSubmit with e.preventDefault().", feedback_wrong: "handleSubmit(e: React.FormEvent<...>)", expected: "Form with typed onSubmit" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Optionally add validation and display errors. Export the component.", answer_keywords: ["export", "validation", "error"], seed_code: "import { useState } from 'react'\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault() }\n  return <form onSubmit={handleSubmit}><input value={email} onChange={e => setEmail(e.target.value)} /><input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" /><button type=\"submit\">Submit</button></form>\n}", feedback_correct: "✅ Forms & Validation with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 8, title: "Forms & Validation (TS)", shortName: "TS — FORMS" });
