import createINPACTEngine from "./inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Problem", content: { tag: "PROBLEM #25 (TypeScript)", title: "Lifting State Up — Typed", body: "Two sibling components share state via a parent. Type Display props as { count: number } and Controls as { onIncrement: () => void; onDecrement?: () => void }.", usecase: "Typed props for parent and children when lifting state." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Parent: useState<number>(0)", "Display({ count }: { count: number })", "Controls({ onIncrement, onDecrement }: { onIncrement: () => void; onDecrement: () => void })"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create parent with const [count, setCount] = useState<number>(0). Display and Controls with typed props. Pass count to Display and onIncrement to Controls.", answer_keywords: ["usestate", "number", "display", "controls", "count"], seed_code: "import { useState } from 'react'\n\nfunction Display({ count }: { count: number }) { return <div>Count: {count}</div> }\nfunction Controls({ onIncrement }: { onIncrement: () => void }) { return <button onClick={onIncrement}>+</button> }\n\nexport default function Parent() {\n  const [count, setCount] = useState<number>(0)\n  return (\n    <div>\n      <Display count={count} />\n      <Controls onIncrement={() => setCount(c => c + 1)} />\n    </div>\n  )\n}", feedback_correct: "✅ State in parent, typed children.", feedback_partial: "Parent state and typed Display/Controls.", feedback_wrong: "Display count and Controls onIncrement", expected: "Parent with state, typed Display and Controls" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Display shows count. Controls has + button that calls onIncrement. State lives only in parent.", answer_keywords: ["count", "onclick", "onincrement"], seed_code: "import { useState } from 'react'\n\nfunction Display({ count }: { count: number }) { return <div>Count: {count}</div> }\nfunction Controls({ onIncrement }: { onIncrement: () => void }) { return <button onClick={onIncrement}>+</button> }\n\nexport default function Parent() {\n  const [count, setCount] = useState<number>(0)\n  return (\n    <div>\n      <Display count={count} />\n      <Controls onIncrement={() => setCount(c => c + 1)} />\n    </div>\n  )\n}", feedback_correct: "✅ Siblings share state via parent.", feedback_partial: "Display shows count, Controls calls onIncrement.", feedback_wrong: "Both children receive props", expected: "Same as seed" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add onDecrement to Controls (typed). Pass from parent. Export the parent.", answer_keywords: ["ondecrement", "button", "export"], seed_code: "import { useState } from 'react'\n\nfunction Display({ count }: { count: number }) { return <div>Count: {count}</div> }\nfunction Controls({ onIncrement, onDecrement }: { onIncrement: () => void; onDecrement: () => void }) {\n  return (\n    <div>\n      <button onClick={onIncrement}>+</button>\n      <button onClick={onDecrement}>-</button>\n    </div>\n  )\n}\n\nexport default function Parent() {\n  const [count, setCount] = useState<number>(0)\n  return (\n    <div>\n      <Display count={count} />\n      <Controls onIncrement={() => setCount(c => c + 1)} onDecrement={() => setCount(c => c - 1)} />\n    </div>\n  )\n}", feedback_correct: "✅ Lifting state up with TypeScript complete.", feedback_partial: "onDecrement and export.", feedback_wrong: "onDecrement from parent", expected: "Same as seed" },
];
const sideItems = [{ label: "Problem", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 25, title: "Lifting State Up (TS)", shortName: "TS — LIFTING STATE" });
