import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #86 (TypeScript)", title: "Race Condition Fix — Typed", body: "Fix stale API overwriting fresh — AbortController Use TypeScript where appropriate.", usecase: "Race conditions." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Identify a memory leak caused by a setState call after component unmount and fix it with a cleanup flag so the learner can spot the failure mode before applying the fix so the effect leaves no stale subscriptions, timers, or listeners behind.","Return a clearTimeout or clearInterval cleanup function typed as () => void from useEffect so consumers receive a stable contract and the effect of that contract can be tested immediately so the effect leaves no stale subscriptions, timers, or listeners behind.","Abort an in-flight fetch request using AbortController.abort() inside the useEffect cleanup so the learner can explain both the mechanism and the visible result, and the effect leaves no stale subscriptions, timers, or listeners behind.","Use the Chrome Memory tab to take a heap snapshot and confirm a suspect component is no longer retained after unmount so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #86 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 86, title: "Race Condition Fix (TS)", shortName: "TS — RACE CONDITION FIX" });
