import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #82 (TypeScript)", title: "Undo/Redo — Typed", body: "Undo/redo for text editor with useReducer + history stack Use TypeScript where appropriate.", usecase: "Undo redo." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Configure a Webpack Module Federation plugin to expose and consume typed remote components so the infrastructure supports the typed runtime behavior the feature depends on.","Model a module type definition file (.d.ts) for a remote federated module to restore TypeScript type safety so state, refs, or values keep a predictable shape as the feature evolves.","Load a remote component lazily using React.lazy(() => import('remote/Component')) inside a Suspense boundary so the learner can explain both the mechanism and the visible result.","Establish a shared typed contract interface used by both the shell and the remote to communicate props so the contract is explicit and incorrect usage is caught early."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #82 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 82, title: "Undo/Redo (TS)", shortName: "TS — UNDOREDO" });
