import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #71 (TypeScript)", title: "useImperativeHandle — Typed", body: "Expose focus()/clear() from child via forwardRef + useImperativeHandle Use TypeScript where appropriate.", usecase: "Imperative handle." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Call useDeferredValue<T>(value) with an explicit generic type parameter to create a deferred copy of a state variable so the hook or API is used with an intentional contract and observable outcome.","Pass the deferred value to a slow child component while passing the immediate value to a responsive input so data crossing component boundaries stays explicit, safe, and easy to trace.","Wrap the slow child in React.memo so it only re-renders when the deferred value actually changes so the boundary is explicit and the fallback or optimization can be verified at runtime and verify whether stable props actually reduce avoidable re-renders.","Compare the behavior of useDeferredValue with useTransition by observing which API controls the timing of the deferred work so the learner can explain both the mechanism and the visible result."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #71 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 71, title: "useImperativeHandle (TS)", shortName: "TS — USEIMPERATIVEHANDL" });
