import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #33 (TypeScript)", title: "useLocalStorage — Typed", body: "Sync state with localStorage — read on mount, write on change Use TypeScript where appropriate.", usecase: "Persist preferences across reloads." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a custom hook usePrevious<T>(value: T): T | undefined with a generic type parameter so the abstraction solves a concrete UI lesson and exposes a reliable typed contract.","Model a useRef<T | undefined>(undefined) to store the previous value without triggering re-renders so state, refs, or values keep a predictable shape as the feature evolves.","Update the ref inside useEffect after every render so it always holds the prior value so the learner can explain both the mechanism and the visible result, and side effects stay predictable across renders and teardown.","Consume usePrevious in a component and display both current and previous values to verify behavior so the learner can connect the typed API to real screen behavior."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #33 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 33, title: "useLocalStorage (TS)", shortName: "TS — USELOCALSTORAGE" });
