import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #60 (TypeScript)", title: "Recursive TreeView — Typed", body: "Recursive TreeView for nested folders Use TypeScript where appropriate.", usecase: "Recursive components." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Model separate useState<string> variables for the raw input value and the debounced search term so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Apply the useDebounce<string> hook to produce a debounced query string that updates after a delay so the learner sees how a typed pattern changes behavior, reuse, or safety in practice.","Trigger a typed useFetch<Result[]> call inside useEffect only when the debounced query changes so the learner can explain both the mechanism and the visible result, and side effects stay predictable across renders and teardown.","Render search results by mapping over a typed Result[] array returned from the fetch hook so the learner can connect the typed data shape to the final UI output so async data is handled with an explicit and safe data shape."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #60 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 60, title: "Recursive TreeView (TS)", shortName: "TS — RECURSIVE TREEVIEW" });
