import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #81 (TypeScript)", title: "Feature Flag Hook — Typed", body: "useFeatureFlag(flagName) from context Use TypeScript where appropriate.", usecase: "Feature flags." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a Theme interface with typed token fields (colors, spacing, typography) and create a typed ThemeContext so the contract is explicit, and shared data can move without losing type safety across components.","Write a typed useTheme hook that reads the ThemeContext and returns the full Theme object so the abstraction solves a concrete UI lesson and exposes a reliable typed contract so shared data can move without losing type safety across components.","Apply theme tokens inside a component by reading from the typed theme object and assigning to React.CSSProperties so the learner sees how a typed pattern changes behavior, reuse, or safety in practice.","Extend the Theme interface to add a new token and confirm that all components using useTheme receive a compiler error until the token is provided so reuse does not weaken the contract or blur responsibility and use the compiler feedback to correct the contract before runtime."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #81 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 81, title: "Feature Flag Hook (TS)", shortName: "TS — FEATURE FLAG HOOK" });
