import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #66 (TypeScript)", title: "Discriminated Union Props — Typed", body: "Button: variant=link requires href, variant=action requires onClick Use TypeScript where appropriate.", usecase: "Discriminated unions." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a generic hook useFetch<T>(url: string): { data: T | null; loading: boolean; error: Error | null } so the abstraction solves a concrete UI problem and exposes a reliable typed contract.","Cast the fetch JSON response to T using the as keyword and explain its type-assertion semantics so the learner can explain both the mechanism and the visible result, and async data is handled with an explicit and safe data shape.","Instantiate useFetch<User[]>, useFetch<Product>, and useFetch<Order> and confirm each returns a correctly typed data field so the generic or runtime object proves its value in a concrete case.","Add a generic constraint <T extends object> to prevent the hook from being instantiated with primitive types so the UI becomes more robust, accessible, or verifiable in use."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #66 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 66, title: "Discriminated Union Props (TS)", shortName: "TS — DISCRIMINATED UNIO" });
