import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #35 (TypeScript)", title: "useWindowSize — Typed", body: "Track window width/height with resize listener and cleanup Use TypeScript where appropriate.", usecase: "Responsive layouts." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a custom hook useKeyPress(targetKey: string): boolean with explicit return type so the abstraction solves a concrete UI problem and exposes a reliable typed contract.","Model a useState<boolean> to track whether the target key is currently pressed so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Attach keydown and keyup event listeners in useEffect typed as (e: KeyboardEvent) => void so the event or DOM boundary behaves correctly and can be verified during interaction so side effects stay predictable across renders and teardown.","Return the boolean keyPressed value and use it in a component to trigger a UI state change so consumers receive a stable contract and the effect of that contract can be tested immediately."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #35 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 35, title: "useWindowSize (TS)", shortName: "TS — USEWINDOWSIZE" });
