import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #12 (TypeScript)", title: "Card Component — Typed", body: "Card with title, description, image, footer. Define interface CardProps; footer can be React.ReactNode.", usecase: "Typing optional props and ReactNode in layout components." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a shared TypeScript interface and import it across parent and child component files so the contract is explicit and incorrect usage is caught early.","Pass typed props through two or more component layers without losing type safety at any level so data crossing component boundaries stays explicit, safe, and easy to trace.","Destructure typed props in a child component signature and confirm no implicit any warnings so the returned contract is readable and its parts are used intentionally.","Identify the compile error produced when a required prop is omitted and fix it at the call site so the learner can spot the failure mode before applying the fix."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface CardProps with title: string, description: string. Use it and render title and description.", answer_keywords: ["interface", "cardprops", "title", "description"], seed_code: "interface CardProps { title: string; description: string }\n\nexport default function Card({ title, description }: CardProps) {\n  return <div><h2>{title}</h2><p>{description}</p></div>\n}", feedback_correct: "✅ CardProps and render.", feedback_partial: "interface and component.", feedback_wrong: "interface CardProps", expected: "CardProps interface" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add image: string to the interface. Render img src={image} alt={title}.", answer_keywords: ["image", "img", "src", "alt"], seed_code: "interface CardProps { title: string; description: string; image: string }\n\nexport default function Card({ title, description, image }: CardProps) {\n  return <div><h2>{title}</h2><img src={image} alt={title} /><p>{description}</p></div>\n}", feedback_correct: "✅ Image prop typed.", feedback_partial: "image in interface and img.", feedback_wrong: "image: string", expected: "image prop" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add footer?: React.ReactNode. Render {footer} at the bottom. Export.", answer_keywords: ["footer", "reactnode", "export"], seed_code: "interface CardProps { title: string; description: string; image: string; footer?: React.ReactNode }\n\nexport default function Card({ title, description, image, footer }: CardProps) {\n  return <div><h2>{title}</h2><img src={image} alt={title} /><p>{description}</p>{footer}</div>\n}", feedback_correct: "✅ Card with TypeScript complete.", feedback_partial: "footer?: React.ReactNode.", feedback_wrong: "footer optional", expected: "Add footer?: React.ReactNode; render {footer} at bottom. Export." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 12, title: "Card Component (TS)", shortName: "TS — CARD" });
