import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #76 (TypeScript)", title: "Mini Redux — Typed", body: "Global state with useReducer + Context + useSelector-style hook Use TypeScript where appropriate.", usecase: "Mini Redux." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a custom hook usePolling<T>(fetchFn: () => Promise<T>, interval: number): { data: T | null; error: Error | null } so the abstraction solves a concrete UI lesson and exposes a reliable typed contract so async data is handled with an explicit and safe data shape.","Use setInterval inside useEffect to call fetchFn on each tick and update typed state with the result so the pattern drives visible behavior, and async data is handled with an explicit and safe data shape.","Return a clearInterval cleanup from useEffect to stop polling when the component unmounts so consumers receive a stable contract and the effect of that contract can be tested immediately so the effect leaves no stale subscriptions, timers, or listeners behind.","Expose a stop function typed as () => void from the hook so the consumer can pause polling manually so consumers interact with a deliberate surface instead of reaching into implementation details."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #76 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 76, title: "Mini Redux (TS)", shortName: "TS — MINI REDUX" });
