import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #18 (TypeScript)", title: "PropTypes / TypeScript Interface", body: "UserCard with typed props. Define interface UserCardProps { name: string; age: number; avatar?: string } and use it.", usecase: "Interfaces document and enforce component API in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Build a className string dynamically using a ternary expression based on a boolean state variable so multiple typed pieces work together as one coherent UI pattern.","Establish a string literal union prop for variant and map it to a class name using an object literal lookup typed as Record<Variant, string> so the contract is explicit and incorrect usage is caught early.","Use the clsx or classnames library with TypeScript to compose class names from conditional expressions so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Extract a typed getClassName helper function with return type string that encapsulates class logic so repeated logic becomes reusable without obscuring the contract."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define interface UserCardProps { name: string; age: number }. Render name and age.", answer_keywords: ["interface", "usercardprops", "name", "age"], seed_code: "interface UserCardProps { name: string; age: number }\n\nexport default function UserCard({ name, age }: UserCardProps) {\n  return <div>{name}, {age}</div>\n}", feedback_correct: "✅ UserCardProps defined.", feedback_partial: "interface with name and age.", feedback_wrong: "interface UserCardProps", expected: "UserCardProps and render" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add avatar?: string. Conditionally render img when avatar is provided.", answer_keywords: ["avatar", "?", "img"], seed_code: "interface UserCardProps { name: string; age: number; avatar?: string }\n\nexport default function UserCard({ name, age, avatar }: UserCardProps) {\n  return (\n    <div>\n      {avatar && <img src={avatar} alt={name} />}\n      <span>{name}, {age}</span>\n    </div>\n  )\n}", feedback_correct: "✅ Optional avatar typed and rendered.", feedback_partial: "avatar?: string and conditional img.", feedback_wrong: "avatar && <img", expected: "avatar?: string; conditionally render img when avatar provided." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export UserCard. Usage: <UserCard name=\"Jane\" age={25} /> or with avatar.", answer_keywords: ["export"], seed_code: "interface UserCardProps { name: string; age: number; avatar?: string }\n\nexport default function UserCard({ name, age, avatar }: UserCardProps) {\n  return (\n    <div>\n      {avatar && <img src={avatar} alt={name} />}\n      <span>{name}, {age}</span>\n    </div>\n  )\n}", feedback_correct: "✅ UserCard with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Export UserCard. Usage with or without avatar." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 18, title: "UserCard / TypeScript (TS)", shortName: "TS — USERCARD" });
