import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #4 (TypeScript)", title: "Multiple State Variables — Typed", body: "Track multiple form fields (e.g. email, password) with separate useState. Type each as useState<string>('').", usecase: "Typing each field prevents mixing types and gives autocomplete." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Model multiple independent state variables each with an explicit type parameter so state, refs, or values keep a predictable shape as the feature evolves.","Type each setter function implicitly from useState and use it in a dedicated handler so invalid interactions are rejected by the compiler, and data shape and updates remain explicit throughout the lesson.","Group related state fields into a typed object interface and manage them with a single useState call so related data can be updated cohesively without weakening the type contract so data shape and updates remain explicit throughout the lesson.","Apply partial<T> to update only changed fields within a single setState call so the learner sees how a typed pattern changes behavior, reuse, or safety in practice."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create separate string state for email and password; initialize both empty.", hint: "const [email, setEmail] = useState<string>(''); same for password.", answer_keywords: ["usestate", "string", "email", "password"], seed_code: "import { useState } from 'react'\n\nexport default function MultiState() {\n  // Step 1: email, password useState<string>\n}", feedback_correct: "✅ Both typed as string.", feedback_partial: "Two useState<string>.", feedback_wrong: "useState<string> for each.", expected: "email and password useState<string>" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add two controlled inputs; wire value and change handling with appropriately typed events.", answer_keywords: ["input", "value", "onchange", "setemail", "setpassword"], seed_code: "import { useState } from 'react'\n\nexport default function MultiState() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  // Step 2: two inputs\n}", feedback_correct: "✅ Inputs wired.", feedback_partial: "value and onChange for both.", feedback_wrong: "Two inputs with value and onChange.", expected: "Two controlled inputs" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Return a form or div containing both fields; export the component.", answer_keywords: ["return", "form", "export"], seed_code: "import { useState } from 'react'\n\nexport default function MultiState() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  return (\n    <form>\n      <input value={email} onChange={e => setEmail(e.target.value)} />\n      <input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" />\n    </form>\n  )\n}", feedback_correct: "✅ Multiple state with TypeScript complete.", feedback_partial: "Form with both inputs.", feedback_wrong: "Return form and export.", expected: "Return form or div with both inputs (email, password). Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 4, title: "Multiple State Variables (TS)", shortName: "TS — MULTIPLE STATE" });
