import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #6 (TypeScript)", title: "List Rendering with map() — Typed", body: "Render a list of items. Define an interface for each item (e.g. id: number, name: string) and type the array and map callback.", usecase: "Typing list data and map callbacks prevents runtime shape errors." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a TypeScript interface for a list item object (e.g. id, label, value) so the contract is explicit and incorrect usage is caught early.","Model a typed array state variable using useState<Item[]> so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Use the array .map() method to iterate over typed objects and return a JSX element per item so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Supply a key prop of type string | number to each mapped element to satisfy React's reconciler so each consumer receives exactly the data or behavior it depends on."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define an interface, e.g. interface Product { id: number; name: string }. Create an array of type Product[].", answer_keywords: ["interface", "id", "name", "[]"], seed_code: "interface Product { id: number; name: string }\n\nconst products: Product[] = [{ id: 1, name: 'Apple' }, { id: 2, name: 'Bread' }]\n\nexport default function ProductList() {\n  // Step 1: interface and array\n}", feedback_correct: "✅ Interface and typed array.", feedback_partial: "interface with id and name; array of that type.", feedback_wrong: "interface Product { id: number; name: string }; products: Product[]", expected: "Interface and Product[]" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Map over the array and render a div per item. Use key={item.id}. Type the callback: (item: Product) => ...", answer_keywords: ["map", "key", "item", "div"], seed_code: "interface Product { id: number; name: string }\nconst products: Product[] = [{ id: 1, name: 'Apple' }, { id: 2, name: 'Bread' }]\n\nexport default function ProductList() {\n  return <div>{products.map((item: Product) => <div key={item.id}>{item.name}</div>)}</div>\n}", feedback_correct: "✅ Typed map with key.", feedback_partial: "map with key and item type.", feedback_wrong: "products.map(item => <div key={item.id}>...)", expected: "map with key" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export the component. Optionally type the component as React.FC or leave as default function.", answer_keywords: ["export", "default"], seed_code: "interface Product { id: number; name: string }\nconst products: Product[] = [{ id: 1, name: 'Apple' }, { id: 2, name: 'Bread' }]\n\nexport default function ProductList() {\n  return <div>{products.map((item: Product) => <div key={item.id}>{item.name}</div>)}</div>\n}", feedback_correct: "✅ List rendering with TypeScript complete.", feedback_partial: "Export component.", feedback_wrong: "export default", expected: "Export default function ProductList with the map and key pattern from the seed. Optionally type as React.FC." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 6, title: "List Rendering with map() (TS)", shortName: "TS — LIST RENDERING" });
