import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #63 (TypeScript)", title: "Debounced Search — Typed", body: "useDebounce + useFetch for real-time search Use TypeScript where appropriate.", usecase: "Search UX." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish two prop interfaces that share a type discriminant field ('success' | 'error') with different additional fields so the contract is explicit and incorrect usage is caught early.","Create a discriminated union type by combining the two interfaces with the | operator so the design pattern is reusable and its contract is clear to downstream code.","Type a component to accept the union type and use a switch statement on the type field to narrow to each branch so invalid interactions are rejected by the compiler instead of leaking into runtime.","Demonstrate that accessing a field only present on one branch without narrowing produces a TypeScript error so the learner can observe the consequence and attach a mental model to it."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #63 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 63, title: "Debounced Search (TS)", shortName: "TS — DEBOUNCED SEARCH" });
