import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #50 (TypeScript)", title: "useCallback for Stable References — Typed", body: "Stabilise callback so child does not re-render Use TypeScript where appropriate.", usecase: "Stable refs." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Wrap a route component import in React.lazy(() => import('./Page')) to create a lazy-loaded module so the boundary is explicit and the fallback or optimization can be verified at runtime.","Wrap lazy components in <React.Suspense fallback={...}> and type the fallback prop as React.ReactNode so the boundary is explicit and the fallback or optimization can be verified at runtime.","Use react Router's <Route> element with a typed component prop to register the lazy component so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Verify code splitting by inspecting the Network tab for a separate chunk loaded on route navigation so the learner can explain both the mechanism and the visible result and confirm the runtime behavior instead of assuming the optimization worked."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #50 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 50, title: "useCallback for Stable References (TS)", shortName: "TS — USECALLBACK FOR ST" });
