import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #39 (TypeScript)", title: "useOnlineStatus — Typed", body: "Track whether the user is online or offline Use TypeScript where appropriate.", usecase: "Show banner when offline." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish an AuthContextType interface with user (User | null), login, and logout typed as functions so the contract is explicit, and shared data can move without losing type safety across components.","Create a typed context with createContext<AuthContextType | undefined>(undefined) so the design pattern is reusable, and shared data can move without losing type safety across components.","Implement a useAuth hook that reads the context with useContext and throws if used outside the provider so the feature works end to end, and shared data can move without losing type safety across components.","Consume the typed user object from useAuth in a component to conditionally render authenticated UI so the learner can connect the typed API to real screen behavior, and the UI exposes only the branch that matches the current state."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #39 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 39, title: "useOnlineStatus (TS)", shortName: "TS — USEONLINESTATUS" });
