import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #26 (TypeScript)", title: "Controlled vs Uncontrolled — Typed", body: "Controlled input: useState<string>. Uncontrolled: useRef<HTMLInputElement | null>(null), read .current?.value. Type both patterns.", usecase: "Typing refs and form state in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish an AccordionItem interface with id, title, and content fields and declare useState<string | null> for the open item so the contract is explicit, and data shape and updates remain explicit throughout the lesson.","Use .map() over a typed AccordionItem[] array to render a list of panel elements so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Implement a toggle handler typed as (id: string) => void that sets state to null when the active panel is re-clicked so the feature works end to end and the resulting behavior can be observed and explained.","Pass an isOpen boolean prop to each panel child component and use it to conditionally render content so data crossing component boundaries stays explicit, safe, and easy to trace so the UI exposes only the branch that matches the current state."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create string state for the field; build a controlled input and show the live value beside it.", answer_keywords: ["usestate", "string", "value", "onchange", "input"], seed_code: "import { useState } from 'react'\n\nexport default function CompareInputs() {\n  const [value, setValue] = useState<string>('')\n  return (\n    <div>\n      <input value={value} onChange={e => setValue(e.target.value)} />\n      <span> → {value}</span>\n    </div>\n  )\n}", feedback_correct: "✅ Controlled input typed.", feedback_partial: "useState<string> and value/onChange.", feedback_wrong: "value={value} onChange", expected: "Controlled input with state" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add an uncontrolled field with a typed element ref and initial default; read the current DOM value on demand (e.g. via a button).", answer_keywords: ["useref", "ref", "defaultvalue", "current"], seed_code: "import { useState, useRef } from 'react'\n\nexport default function CompareInputs() {\n  const [value, setValue] = useState<string>('')\n  const inputRef = useRef<HTMLInputElement | null>(null)\n  return (\n    <div>\n      <div>Controlled: <input value={value} onChange={e => setValue(e.target.value)} /> → {value}</div>\n      <div>Uncontrolled: <input ref={inputRef} defaultValue=\"\" /> <button onClick={() => alert(inputRef.current?.value)}>Read</button></div>\n    </div>\n  )\n}", feedback_correct: "✅ Uncontrolled input with typed ref.", feedback_partial: "useRef<HTMLInputElement | null> and ref.", feedback_wrong: "inputRef.current?.value", expected: "useRef<HTMLInputElement | null>, ref={inputRef}, defaultValue, button that reads inputRef.current?.value." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Comment briefly on controlled vs uncontrolled source of truth; export the component.", answer_keywords: ["//", "export"], seed_code: "import { useState, useRef } from 'react'\n\n// Controlled: state is source of truth. Uncontrolled: DOM holds value, read on demand.\nexport default function CompareInputs() {\n  const [value, setValue] = useState<string>('')\n  const inputRef = useRef<HTMLInputElement | null>(null)\n  return (\n    <div>\n      <div>Controlled: <input value={value} onChange={e => setValue(e.target.value)} /> → {value}</div>\n      <div>Uncontrolled: <input ref={inputRef} defaultValue=\"\" /> <button onClick={() => alert(inputRef.current?.value)}>Read</button></div>\n    </div>\n  )\n}", feedback_correct: "✅ Controlled vs uncontrolled with TypeScript complete.", feedback_partial: "Comment and export.", feedback_wrong: "export default", expected: "Add comment explaining controlled vs uncontrolled. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 26, title: "Controlled vs Uncontrolled (TS)", shortName: "TS — CONTROLLED VS UNCONTROLLED" });
