import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #87 (TypeScript)", title: "Memoization Strategy — Typed", body: "Dashboard with 20 widgets — memoization strategy Use TypeScript where appropriate.", usecase: "Memo strategy." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Mock the global fetch function using vi.fn() or jest.fn() with a typed return value matching the API response so tests stay realistic while preserving the same contract as production code so async data is handled with an explicit and safe data shape.","Write a typed renderHook call from @testing-library/react to invoke useFetch<T> in a test environment so the abstraction solves a concrete UI lesson and exposes a reliable typed contract.","Assert that the loading state is true before the fetch resolves and false after using waitFor so the expected behavior is proven rather than assumed so async data is handled with an explicit and safe data shape.","Assert that the returned data matches the typed mock response using expect with typed matchers so the expected behavior is proven rather than assumed."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #87 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 87, title: "Memoization Strategy (TS)", shortName: "TS — MEMOIZATION STRATE" });
