import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #96 (TypeScript)", title: "Design DataTable API — Typed", body: "Design props for sortable, filterable, paginated table Use TypeScript where appropriate.", usecase: "API design." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish typed interfaces for each metric panel's data shape and connect them via the useWebSocket<T> hook so the contract is explicit and incorrect usage is caught early.","Compose typed chart components by passing strongly-typed data arrays as props so the learner sees how smaller typed pieces form a larger UI capability.","Use useSyncExternalStore with a typed external metrics store to guarantee consistent reads across panels so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Wrap expensive chart computations in useMemo<ChartData> to prevent unnecessary recalculations on WebSocket updates so the boundary is explicit and the fallback or optimization can be verified at runtime."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #96 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 96, title: "Design DataTable API (TS)", shortName: "TS — DESIGN DATATABLE A" });
