import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #22 (TypeScript)", title: "Inline Styles — Typed", body: "Progress bar with dynamic width. Use useState<number>(0) for progress and type the bar style as React.CSSProperties.", usecase: "Typed state and CSSProperties for dynamic styles." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Move a useState declaration from a child component to the nearest common parent so the learner can explain both the mechanism and the visible result, and data shape and updates remain explicit throughout the lesson.","Pass the state value and its setter (typed as React.Dispatch<React.SetStateAction<T>>) as props to child components so data crossing component boundaries stays explicit, safe, and easy to trace.","Establish a callback prop typed as (value: T) => void to allow a child to communicate changes to its parent so the contract is explicit and incorrect usage is caught early.","Demonstrate that removing local state from a child and receiving it as a prop eliminates duplicate state so the learner can observe the consequence and attach a mental model to it."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create numeric progress (0–100); render a track and a bar whose width follows progress.", answer_keywords: ["usestate", "number", "progress", "width"], seed_code: "import { useState } from 'react'\n\nexport default function ProgressBar() {\n  const [progress, setProgress] = useState<number>(0)\n  return (\n    <div style={{ width: '100%', height: 20, background: '#eee', borderRadius: 4 }}>\n      <div style={{ width: progress + '%', height: 20, background: '#3b82f6', borderRadius: 4 }} />\n    </div>\n  )\n}", feedback_correct: "✅ Progress state and bar.", feedback_partial: "useState<number> and width from progress.", feedback_wrong: "progress + '%'", expected: "Track and bar with dynamic width" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add controls to nudge progress up and down; clamp so it stays within 0–100.", answer_keywords: ["button", "math.min", "math.max", "setprogress"], seed_code: "import { useState } from 'react'\n\nexport default function ProgressBar() {\n  const [progress, setProgress] = useState<number>(0)\n  return (\n    <div>\n      <div style={{ width: '100%', height: 20, background: '#eee', borderRadius: 4 }}>\n        <div style={{ width: progress + '%', height: 20, background: '#3b82f6', borderRadius: 4 }} />\n      </div>\n      <button onClick={() => setProgress(p => Math.min(100, p + 10))}>+10</button>\n      <button onClick={() => setProgress(p => Math.max(0, p - 10))}>-10</button>\n    </div>\n  )\n}", feedback_correct: "✅ Buttons clamp progress.", feedback_partial: "setProgress with clamp.", feedback_wrong: "Math.min and Math.max", expected: "Buttons: setProgress(p => Math.min(100, p + 10)) and Math.max(0, p - 10)." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Export the component; optional typed style object for the bar is fine.", answer_keywords: ["export"], seed_code: "import { useState } from 'react'\n\nexport default function ProgressBar() {\n  const [progress, setProgress] = useState<number>(0)\n  const barStyle: React.CSSProperties = { width: progress + '%', height: 20, background: '#3b82f6', borderRadius: 4 }\n  return (\n    <div>\n      <div style={{ width: '100%', height: 20, background: '#eee', borderRadius: 4 }}>\n        <div style={barStyle} />\n      </div>\n      <button onClick={() => setProgress(p => Math.min(100, p + 10))}>+10</button>\n      <button onClick={() => setProgress(p => Math.max(0, p - 10))}>-10</button>\n    </div>\n  )\n}", feedback_correct: "✅ Inline styles with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "Export the component. Optionally type barStyle as React.CSSProperties." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 22, title: "Inline Styles (TS)", shortName: "TS — PROGRESS BAR" });
