import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #84 (TypeScript)", title: "Component Library Theming — Typed", body: "Token-based theming with CSS variables + Context Use TypeScript where appropriate.", usecase: "Theming." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Apply useMemo with a typed return type to memoize a derived data transformation over a typed array so the learner sees how a typed pattern changes behavior, reuse, or safety in practice.","Apply useCallback with a typed signature to memoize an event handler passed to a React.memo child so the learner sees how a typed pattern changes behavior, reuse, or safety in practice and verify whether stable props actually reduce avoidable re-renders.","Identify when memoization is unnecessary by tracing the component tree for referential stability so the learner can spot the failure mode before applying the fix.","Write a typed selector function and compose it with useMemo to derive computed state from a context value so the abstraction solves a concrete UI lesson and exposes a reliable typed contract."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #84 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 84, title: "Component Library Theming (TS)", shortName: "TS — COMPONENT LIBRARY " });
