import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #92 (TypeScript)", title: "Test Async Component — Typed", body: "Test fetch component with msw, assert loading → data Use TypeScript where appropriate.", usecase: "Test async." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a generic Column<T> interface with key: keyof T, header: string, and an optional render prop typed as (val: T[keyof T], row: T) => React.ReactNode so the contract is explicit and incorrect usage is caught early.","Write a generic DataTable<T> component that accepts rows: T[] and columns: Column<T>[] and renders a typed <table> so the abstraction solves a concrete UI problem and exposes a reliable typed contract.","Implement a typed sort handler that reads the Column key and sorts the rows array using Array.prototype.sort so the feature works end to end and the resulting behavior can be observed and explained.","Expose a typed onRowClick prop as (row: T) => void and call it inside the row's onClick handler so consumers interact with a deliberate surface instead of reaching into implementation details."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #92 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 92, title: "Test Async Component (TS)", shortName: "TS — TEST ASYNC COMPONE" });
