import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #25 (TypeScript)", title: "Lifting State Up — Typed", body: "Two sibling components share state via a parent. Type Display props as { count: number } and Controls as { onIncrement: () => void; onDecrement?: () => void }.", usecase: "Typed props for parent and children when lifting state." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a StarRatingProps interface with rating, maxStars, and an onRate callback typed as (n: number) => void so the contract is explicit and incorrect usage is caught early.","Use array.from({ length: maxStars }) with .map() to generate an array of typed star elements so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Model a hover state variable using useState<number | null> to drive visual feedback so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Type mouse event handlers as React.MouseEventHandler<HTMLSpanElement> to update hover and rating state so invalid interactions are rejected by the compiler instead of leaking into runtime."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Lift count into the parent; define typed Display and Controls; pass the value down and an increment callback in.", answer_keywords: ["usestate", "number", "display", "controls", "count"], seed_code: "import { useState } from 'react'\n\nfunction Display({ count }: { count: number }) { return <div>Count: {count}</div> }\nfunction Controls({ onIncrement }: { onIncrement: () => void }) { return <button onClick={onIncrement}>+</button> }\n\nexport default function Parent() {\n  const [count, setCount] = useState<number>(0)\n  return (\n    <div>\n      <Display count={count} />\n      <Controls onIncrement={() => setCount(c => c + 1)} />\n    </div>\n  )\n}", feedback_correct: "✅ State in parent, typed children.", feedback_partial: "Parent state and typed Display/Controls.", feedback_wrong: "Display count and Controls onIncrement", expected: "Parent with state, typed Display and Controls" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Keep state only in the parent; Display reads count; Controls triggers onIncrement from props.", answer_keywords: ["count", "onclick", "onincrement"], seed_code: "import { useState } from 'react'\n\nfunction Display({ count }: { count: number }) { return <div>Count: {count}</div> }\nfunction Controls({ onIncrement }: { onIncrement: () => void }) { return <button onClick={onIncrement}>+</button> }\n\nexport default function Parent() {\n  const [count, setCount] = useState<number>(0)\n  return (\n    <div>\n      <Display count={count} />\n      <Controls onIncrement={() => setCount(c => c + 1)} />\n    </div>\n  )\n}", feedback_correct: "✅ Siblings share state via parent.", feedback_partial: "Display shows count, Controls calls onIncrement.", feedback_wrong: "Both children receive props", expected: "Display count; Controls with onIncrement from parent." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add a typed decrement callback from the parent; export the parent component.", answer_keywords: ["ondecrement", "button", "export"], seed_code: "import { useState } from 'react'\n\nfunction Display({ count }: { count: number }) { return <div>Count: {count}</div> }\nfunction Controls({ onIncrement, onDecrement }: { onIncrement: () => void; onDecrement: () => void }) {\n  return (\n    <div>\n      <button onClick={onIncrement}>+</button>\n      <button onClick={onDecrement}>-</button>\n    </div>\n  )\n}\n\nexport default function Parent() {\n  const [count, setCount] = useState<number>(0)\n  return (\n    <div>\n      <Display count={count} />\n      <Controls onIncrement={() => setCount(c => c + 1)} onDecrement={() => setCount(c => c - 1)} />\n    </div>\n  )\n}", feedback_correct: "✅ Lifting state up with TypeScript complete.", feedback_partial: "onDecrement and export.", feedback_wrong: "onDecrement from parent", expected: "Add onDecrement to Controls (typed). Pass () => setCount(c => c - 1) from parent. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 25, title: "Lifting State Up (TS)", shortName: "TS — LIFTING STATE" });
