import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #20 (TypeScript)", title: "Event Handling — Typed", body: "Form where Enter submits and Escape clears. Type the keyboard handler as (e: React.KeyboardEvent<HTMLFormElement>) => void.", usecase: "Typing keyboard events prevents wrong event types." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Import a CSS Module file and type the resulting styles object using the implicit module declaration so the learner can explain both the mechanism and the visible result.","Apply a CSS Module class to a JSX element using styles.className and verify no string typo errors so the learner sees how a typed pattern changes behavior, reuse, or safety in practice.","Compose multiple CSS Module classes using a template literal or clsx with typed keys so the learner sees how smaller typed pieces form a larger UI capability.","Model a custom .d.ts module declaration for a CSS Module file to enable named class exports so state, refs, or values keep a predictable shape as the feature evolves."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create state const [value, setValue] = useState<string>(''). Form with onSubmit that prevents default.", answer_keywords: ["usestate", "string", "form", "onsubmit", "preventdefault"], seed_code: "import { useState } from 'react'\n\nexport default function KeyForm() {\n  const [value, setValue] = useState<string>('')\n  const handleSubmit = () => console.log(value)\n  return <form onSubmit={e => { e.preventDefault(); handleSubmit() }}><input value={value} onChange={e => setValue(e.target.value)} /></form>\n}", feedback_correct: "✅ Form and state typed.", feedback_partial: "useState<string> and form onSubmit.", feedback_wrong: "useState<string> and preventDefault", expected: "Form with submit" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add onKeyDown. When e.key === 'Enter' call submit; when e.key === 'Escape' setValue(''). Type e as React.KeyboardEvent.", answer_keywords: ["onkeydown", "enter", "escape", "key"], seed_code: "import { useState } from 'react'\n\nexport default function KeyForm() {\n  const [value, setValue] = useState<string>('')\n  const handleSubmit = () => console.log(value)\n  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {\n    if (e.key === 'Enter') { e.preventDefault(); handleSubmit() }\n    if (e.key === 'Escape') setValue('')\n  }\n  return (\n    <form onSubmit={e => { e.preventDefault(); handleSubmit() }}>\n      <input value={value} onChange={e => setValue(e.target.value)} onKeyDown={handleKeyDown} placeholder=\"Enter or Esc\" />\n    </form>\n  )\n}", feedback_correct: "✅ Keyboard handler typed.", feedback_partial: "onKeyDown with Enter and Escape.", feedback_wrong: "e.key === 'Enter' and 'Escape'", expected: "onKeyDown: if (e.key === 'Enter') handleSubmit(); if (e.key === 'Escape') setValue(''). Type e as React.KeyboardEvent." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "No submit button — submit only via Enter. Export the component.", answer_keywords: ["export"], seed_code: "import { useState } from 'react'\n\nexport default function KeyForm() {\n  const [value, setValue] = useState<string>('')\n  const handleSubmit = () => console.log(value)\n  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {\n    if (e.key === 'Enter') { e.preventDefault(); handleSubmit() }\n    if (e.key === 'Escape') setValue('')\n  }\n  return (\n    <form onSubmit={e => { e.preventDefault(); handleSubmit() }}>\n      <input value={value} onChange={e => setValue(e.target.value)} onKeyDown={handleKeyDown} placeholder=\"Enter or Esc\" />\n    </form>\n  )\n}", feedback_correct: "✅ Event handling with TypeScript complete.", feedback_partial: "Export.", feedback_wrong: "export default", expected: "No submit button; submit only via Enter. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 20, title: "Event Handling (TS)", shortName: "TS — KEYBOARD" });
