import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #75 (TypeScript)", title: "useLayoutEffect vs useEffect — Typed", body: "Explain difference with DOM measurement example Use TypeScript where appropriate.", usecase: "Layout effect." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a typed in-flight cache using Map<string, Promise<T>> to store pending requests by URL key so the design pattern is reusable and its contract is clear to downstream code.","Write a typed fetchOnce<T>(url: string): Promise<T> function that returns the existing promise if a request is already in flight so the abstraction solves a concrete UI lesson and exposes a reliable typed contract so async data is handled with an explicit and safe data shape.","Remove the cache entry in the .finally() handler of the promise to allow re-fetching after completion so the learner can explain both the mechanism and the visible result, and async data is handled with an explicit and safe data shape.","Consume fetchOnce in multiple components that mount simultaneously and verify only one network request fires so the learner can connect the typed API to real screen behavior, and async data is handled with an explicit and safe data shape."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #75 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 75, title: "useLayoutEffect vs useEffect (TS)", shortName: "TS — USELAYOUTEFFECT VS" });
