import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #38 (TypeScript)", title: "useKeyPress — Typed", body: "Detect when a specific keyboard key is pressed Use TypeScript where appropriate.", usecase: "Shortcuts, escape to close." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a ThemeContextType interface and create a typed context with createContext<ThemeContextType | undefined>(undefined) so the contract is explicit, and shared data can move without losing type safety across components.","Write a ThemeProvider component that wraps children with Context.Provider and supplies a typed value so the abstraction solves a concrete UI lesson and exposes a reliable typed contract so shared data can move without losing type safety across components.","Write a useTheme custom hook that calls useContext, checks for undefined, and returns the typed context value so the abstraction solves a concrete UI lesson and exposes a reliable typed contract so shared data can move without losing type safety across components.","Consume useTheme in a child component and apply the theme token to a React.CSSProperties object so the learner can connect the typed API to real screen behavior."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #38 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 38, title: "useKeyPress (TS)", shortName: "TS — USEKEYPRESS" });
