import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #69 (TypeScript)", title: "Generic useFetch<T> — Typed", body: "Add generics to useFetch for typed responses Use TypeScript where appropriate.", usecase: "Generic hooks." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a typed external store with a subscribe function, a getSnapshot function, and a getServerSnapshot function so the design pattern is reusable and its contract is clear to downstream code.","Call useSyncExternalStore<T>(subscribe, getSnapshot) with a generic type parameter to get a typed snapshot so the hook or API is used with an intentional contract and observable outcome.","Implement a notify pattern in the store so state changes trigger all subscriber callbacks so the feature works end to end and the resulting behavior can be observed and explained.","Consume the typed store value in multiple components and verify they all update synchronously on a single store mutation so the learner can connect the typed API to real screen behavior."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #69 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 69, title: "Generic useFetch<T> (TS)", shortName: "TS — GENERIC USEFETCHT" });
