import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #91 (TypeScript)", title: "Test useFetch — Typed", body: "Test useFetch with renderHook, mock fetch, loading/error/data Use TypeScript where appropriate.", usecase: "Test hooks." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a typed child component that conditionally throws an Error to trigger the error boundary so the abstraction solves a concrete UI problem and exposes a reliable typed contract.","Render the ErrorBoundary wrapping the typed throwing child and assert the fallback UI is displayed so the learner can connect the typed data shape to the final UI output.","Spy on console.error and suppress it during the test to avoid noisy output from expected errors so the learner can explain both the mechanism and the visible result.","Re-render with a non-throwing child and assert the error boundary resets and shows the normal UI so the learner can explain both the mechanism and the visible result."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #91 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 91, title: "Test useFetch (TS)", shortName: "TS — TEST USEFETCH" });
