import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #47 (TypeScript)", title: "Compound Component (Tabs) — Typed", body: "Tabs component with Context so Tab children know active state Use TypeScript where appropriate.", usecase: "Tabs + Context." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Wrap an event handler in useCallback with a typed signature (...args) => returnType and a dependency array so the boundary is explicit and the fallback or optimization can be verified at runtime.","Pass the memoized callback as a prop to a React.memo child and verify the child no longer re-renders on parent state change so data crossing component boundaries stays explicit, safe, and easy to trace and verify whether stable props actually reduce avoidable re-renders.","Model the correct dependencies in the useCallback array so the function closes over fresh values so state, refs, or values keep a predictable shape as the feature evolves.","Demonstrate the referential equality check that React.memo performs on the callback prop between renders so the learner can observe the consequence and attach a mental model to it and verify whether stable props actually reduce avoidable re-renders."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #47 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 47, title: "Compound Component (Tabs) (TS)", shortName: "TS — COMPOUND COMPONENT" });
