import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #8 (TypeScript)", title: "Forms & Validation — Typed", body: "Login form with email/password. Type state as string, type errors as string or Record<string, string>, and type the submit handler.", usecase: "Typed form state and error state scale to large forms." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a FormState interface and manage all form fields with a single useState<FormState> so the contract is explicit, and data shape and updates remain explicit throughout the lesson.","Type a form submit handler as React.FormEventHandler<HTMLFormElement> and call e.preventDefault() so invalid interactions are rejected by the compiler instead of leaking into runtime.","Model a typed errors object using Partial<Record<keyof FormState, string>> and populate it in a validate function so state, refs, or values keep a predictable shape as the feature evolves.","Display per-field error messages conditionally using the && operator against the typed errors object so the user-facing result makes the underlying state or validation visible."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create string state for email and password; add error state if you need it for validation messages.", answer_keywords: ["usestate", "string", "email", "password"], seed_code: "import { useState } from 'react'\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  // Step 1: state\n}", feedback_correct: "✅ Form state typed.", feedback_partial: "useState<string> for email and password.", feedback_wrong: "email and password state", expected: "useState<string> for both" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add a form with submit handling; prevent default navigation and type the submit event for a form element.", answer_keywords: ["form", "onsubmit", "preventdefault"], seed_code: "import { useState } from 'react'\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); console.log(email, password) }\n  return <form onSubmit={handleSubmit}><input value={email} onChange={e => setEmail(e.target.value)} /><input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" /><button type=\"submit\">Submit</button></form>\n}", feedback_correct: "✅ Form and handler typed.", feedback_partial: "onSubmit with e.preventDefault().", feedback_wrong: "handleSubmit(e: React.FormEvent<...>)", expected: "Form with typed onSubmit" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Validate inputs (non-empty fields); surface errors from state in the form; export the component.", answer_keywords: ["export", "error", "seterror", "trim"], seed_code: "import { useState } from 'react'\n\nexport default function LoginForm() {\n  const [email, setEmail] = useState<string>('')\n  const [password, setPassword] = useState<string>('')\n  const [error, setError] = useState<string>('')\n  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {\n    e.preventDefault()\n    // Step 3: add validation here — setError('...') when invalid, setError('') when valid\n  }\n  return (\n    <form onSubmit={handleSubmit}>\n      <input value={email} onChange={e => setEmail(e.target.value)} placeholder=\"Email\" />\n      <input value={password} onChange={e => setPassword(e.target.value)} type=\"password\" placeholder=\"Password\" />\n      {/* Step 3: display error here, e.g. {error && <p>{error}</p>} */}\n      <button type=\"submit\">Submit</button>\n    </form>\n  )\n}", feedback_correct: "✅ Forms & Validation with TypeScript complete.", feedback_partial: "Add validation and show errors.", feedback_wrong: "Validate on submit and display error state.", expected: "In handleSubmit: validate email/password (e.g. !email.trim() → setError('Email required')). Clear with setError(''). In JSX add {error && <p style={{ color: 'red' }}>{error}</p>}. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 8, title: "Forms & Validation (TS)", shortName: "TS — FORMS" });
