import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #17 (TypeScript)", title: "List Rendering — Typed", body: "Render a list of products. Define interface Product { id: number; name: string; price: number } and type the array and map callback.", usecase: "Typing list items and map callback prevents shape errors." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Type mouse event handlers using React.MouseEvent<HTMLButtonElement> so invalid interactions are rejected by the compiler instead of leaking into runtime.","Type keyboard event handlers using React.KeyboardEvent<HTMLInputElement> and read e.key so invalid interactions are rejected by the compiler instead of leaking into runtime.","Type focus and blur handlers using React.FocusEvent<HTMLInputElement> so invalid interactions are rejected by the compiler instead of leaking into runtime.","Model an inline event handler directly on a JSX element with an explicit type annotation so state, refs, or values keep a predictable shape as the feature evolves."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define a Product type; build a typed list; render each row with a stable key.", answer_keywords: ["interface", "product", "id", "name", "price", "map", "key"], seed_code: "interface Product { id: number; name: string; price: number }\nconst products: Product[] = [{ id: 1, name: 'Apple', price: 1 }, { id: 2, name: 'Bread', price: 2 }]\n\nexport default function ProductList() {\n  return <div>{products.map((p: Product) => <div key={p.id}>{p.name} - {p.price}</div>)}</div>\n}", feedback_correct: "✅ Product interface and typed map.", feedback_partial: "interface Product and products: Product[].", feedback_wrong: "interface Product { id, name, price }", expected: "Product[] and map with key" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Keep keys tied to stable ids; type the map callback argument as your product type.", answer_keywords: ["key", "product", "item"], seed_code: "interface Product { id: number; name: string; price: number }\nconst products: Product[] = [{ id: 1, name: 'Apple', price: 1 }, { id: 2, name: 'Bread', price: 2 }]\n\nexport default function ProductList() {\n  return <div>{products.map((item: Product) => <div key={item.id}>{item.name} - {item.price}</div>)}</div>\n}", feedback_correct: "✅ Typed list with keys.", feedback_partial: "key and Product type in map.", feedback_wrong: "map((item: Product) =>", expected: "key={item.id} and callback typed as Product." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Note why list keys matter; export the component.", answer_keywords: ["//", "export"], seed_code: "// Keys help React match list items across re-renders.\ninterface Product { id: number; name: string; price: number }\nconst products: Product[] = [{ id: 1, name: 'Apple', price: 1 }, { id: 2, name: 'Bread', price: 2 }]\n\nexport default function ProductList() {\n  return <div>{products.map((item: Product) => <div key={item.id}>{item.name} - {item.price}</div>)}</div>\n}", feedback_correct: "✅ List rendering with TypeScript complete.", feedback_partial: "Comment and export.", feedback_wrong: "export default", expected: "Comment: keys help React reconcile the list. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 17, title: "List Rendering (TS)", shortName: "TS — LIST" });
