import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #21 (TypeScript)", title: "Conditional Classes — Typed", body: "Apply different CSS classes based on state. Use useState<boolean>(false) for isActive and type the button className as string.", usecase: "Typed state and string class names in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a styled component using a tagged template literal and type its props with a generic parameter so the design pattern is reusable and its contract is clear to downstream code.","Extend an existing styled component and override specific styles while inheriting its type so reuse does not weaken the contract or blur responsibility.","Pass a typed prop to a styled component's template literal to compute a dynamic CSS value so data crossing component boundaries stays explicit, safe, and easy to trace.","Use the css helper from styled-components with TypeScript to extract reusable typed style blocks so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create const [isActive, setIsActive] = useState<boolean>(false). Render a button that toggles isActive on click.", answer_keywords: ["usestate", "boolean", "isactive", "onclick"], seed_code: "import { useState } from 'react'\n\nexport default function ToggleButton() {\n  const [isActive, setIsActive] = useState<boolean>(false)\n  return <button onClick={() => setIsActive(!isActive)}>Toggle</button>\n}", feedback_correct: "✅ Toggle state typed.", feedback_partial: "useState<boolean> and onClick.", feedback_wrong: "useState<boolean>(false)", expected: "Button that toggles isActive" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add className that includes 'active' when isActive. Use string: 'btn ' + (isActive ? 'active' : '').", answer_keywords: ["classname", "active", "isactive"], seed_code: "import { useState } from 'react'\n\nexport default function ToggleButton() {\n  const [isActive, setIsActive] = useState<boolean>(false)\n  return (\n    <button onClick={() => setIsActive(!isActive)} className={'btn ' + (isActive ? 'active' : '')}>\n      Toggle\n    </button>\n  )\n}", feedback_correct: "✅ Conditional class applied.", feedback_partial: "className with isActive ? 'active' : ''.", feedback_wrong: "className with active when isActive", expected: "className={'btn ' + (isActive ? 'active' : '')}." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add inline style for active state (e.g. backgroundColor). Export the component.", answer_keywords: ["style", "background", "export"], seed_code: "import { useState } from 'react'\n\nexport default function ToggleButton() {\n  const [isActive, setIsActive] = useState<boolean>(false)\n  return (\n    <button\n      onClick={() => setIsActive(!isActive)}\n      className={'btn ' + (isActive ? 'active' : '')}\n      style={{ backgroundColor: isActive ? '#3b82f6' : '#ccc', color: isActive ? '#fff' : '#333' }}\n    >\n      Toggle\n    </button>\n  )\n}", feedback_correct: "✅ Conditional classes with TypeScript complete.", feedback_partial: "Style and export.", feedback_wrong: "export default", expected: "Inline style for active (e.g. backgroundColor). Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 21, title: "Conditional Classes (TS)", shortName: "TS — TOGGLE CLASS" });
