import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #89 (TypeScript)", title: "Concurrent Mode Gotchas — Typed", body: "Explain tearing and useSyncExternalStore Use TypeScript where appropriate.", usecase: "Tearing." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use userEvent.type to simulate keyboard input on a controlled input and assert the typed state updates so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Use userEvent.click to fire a button press and assert the resulting DOM change so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Use userEvent.selectOptions on a typed <select> element and verify the controlled value updates so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Assert that a form submit handler is called with the correct typed payload using a jest.fn() spy so the expected behavior is proven rather than assumed."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #89 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 89, title: "Concurrent Mode Gotchas (TS)", shortName: "TS — CONCURRENT MODE GO" });
