import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #40 (TypeScript)", title: "useMediaQuery — Typed", body: "Return true/false based on a CSS media query string Use TypeScript where appropriate.", usecase: "Responsive without CSS-in-JS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish cartItem and CartContextType interfaces and create a typed context with createContext so the contract is explicit, and shared data can move without losing type safety across components.","Implement addToCart and removeFromCart functions typed as (item: CartItem) => void in the provider so the feature works end to end and the resulting behavior can be observed and explained.","Use useReducer<CartState, CartAction> inside the provider to manage cart state with typed actions so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Consume the typed CartContext in a product component to add items and in a cart component to list them so the learner can connect the typed API to real screen behavior, and shared data can move without losing type safety across components."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #40 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 40, title: "useMediaQuery (TS)", shortName: "TS — USEMEDIAQUERY" });
