import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #58 (TypeScript)", title: "Portal — Typed", body: "Render modal outside root with ReactDOM.createPortal Use TypeScript where appropriate.", usecase: "Portals." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a typed usePagination<T>(items: T[], pageSize: number) hook that returns currentPage, totalPages, and a typed page slice so the contract is explicit and incorrect usage is caught early.","Use math.ceil to compute totalPages and Array.prototype.slice to extract the current page items so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Model useState<number> for currentPage and implement goToPage, nextPage, and prevPage functions typed as () => void so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Consume the typed hook in a component and render page items with .map() and navigation buttons so the learner can connect the typed API to real screen behavior."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #58 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 58, title: "Portal (TS)", shortName: "TS — PORTAL" });
