import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #79 (TypeScript)", title: "Polling Hook — Typed", body: "usePolling: refetch on interval, stop on unmount Use TypeScript where appropriate.", usecase: "Polling." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a typed History<T> interface with past: T[], present: T, and future: T[] fields so the contract is explicit and incorrect usage is caught early.","Implement a typed reducer with 'SET', 'UNDO', and 'REDO' action types that operate on the History<T> structure so the feature works end to end and the resulting behavior can be observed and explained.","Call useReducer<History<T>, HistoryAction<T>>(reducer, initialHistory) and destructure state and dispatch so the hook or API is used with an intentional contract and observable outcome.","Expose undo and redo dispatch calls via a typed useUndoRedo<T> hook with canUndo and canRedo boolean fields so consumers interact with a deliberate surface instead of reaching into implementation details."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #79 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 79, title: "Polling Hook (TS)", shortName: "TS — POLLING HOOK" });
