import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #43 (TypeScript)", title: "Cart Context — Typed", body: "Shopping cart: add, remove, update quantity, total price Use TypeScript where appropriate.", usecase: "Global cart state." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a State interface and a discriminated union type for Action with a type field so the contract is explicit and incorrect usage is caught early.","Implement a typed reducer function with signature (state: State, action: Action): State so the feature works end to end and the resulting behavior can be observed and explained.","Call useReducer<State, Action>(reducer, initialState) and destructure the typed [state, dispatch] tuple so the hook or API is used with an intentional contract and observable outcome.","Dispatch typed action objects from event handlers and demonstrate that the compiler rejects unknown action types so state transitions remain explicit, traceable, and type-safe."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #43 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 43, title: "Cart Context (TS)", shortName: "TS — CART CONTEXT" });
