import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #80 (TypeScript)", title: "WebSocket Hook — Typed", body: "useWebSocket: connect, reconnect, send + last message Use TypeScript where appropriate.", usecase: "WebSocket." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a generic useForm<T extends object>(initialValues: T) hook that manages typed field values and errors so the abstraction solves a concrete UI lesson and exposes a reliable typed contract.","Implement a typed handleChange function using keyof T to update individual fields without losing type safety so the feature works end to end and the resulting behavior can be observed and explained.","Implement a validate function typed as (values: T) => Partial<Record<keyof T, string>> that returns per-field errors so the feature works end to end and the resulting behavior can be observed and explained.","Return a typed register function from the hook that produces value, onChange, and onBlur props for any field so consumers receive a stable contract and the effect of that contract can be tested immediately."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #80 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 80, title: "WebSocket Hook (TS)", shortName: "TS — WEBSOCKET HOOK" });
