import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #56 (TypeScript)", title: "Render Props (MouseTracker) — Typed", body: "MouseTracker using render props pattern Use TypeScript where appropriate.", usecase: "Render props." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a class-based ErrorBoundary component that implements the React.Component<Props, State> generic so the design pattern is reusable and its contract is clear to downstream code.","Implement the static getDerivedStateFromError(error: Error): State lifecycle to set hasError state so the feature works end to end and the resulting behavior can be observed and explained.","Implement the componentDidCatch(error: Error, info: React.ErrorInfo): void lifecycle to log error details so the feature works end to end and the resulting behavior can be observed and explained.","Wrap a typed child subtree with ErrorBoundary and verify it catches thrown errors without crashing the app so the boundary is explicit and the fallback or optimization can be verified at runtime."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #56 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 56, title: "Render Props (MouseTracker) (TS)", shortName: "TS — RENDER PROPS MOUSE" });
