import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #51 (TypeScript)", title: "React.memo — Typed", body: "Wrap pure child; demonstrate it stops re-rendering Use TypeScript where appropriate.", usecase: "Memo demo." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a typed LazyImage component that uses useRef<HTMLImageElement>(null) to observe a DOM node so the design pattern is reusable and its contract is clear to downstream code.","Instantiate an IntersectionObserver in useEffect and type its callback as IntersectionObserverCallback so the generic or runtime object proves its value in a concrete case so side effects stay predictable across renders and teardown.","Swap the src attribute from a placeholder to the real URL when isIntersecting becomes true so the learner can explain both the mechanism and the visible result.","Return an observer.disconnect() cleanup from useEffect to avoid memory leaks so consumers receive a stable contract and the effect of that contract can be tested immediately so the effect leaves no stale subscriptions, timers, or listeners behind."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #51 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 51, title: "React.memo (TS)", shortName: "TS — REACTMEMO" });
