import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #77 (TypeScript)", title: "Optimistic UI — Typed", body: "Todo: add item instantly, sync server, rollback on failure Use TypeScript where appropriate.", usecase: "Optimistic updates." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a custom hook useWebSocket<T>(url: string) that opens a WebSocket connection inside useEffect so the abstraction solves a concrete UI lesson and exposes a reliable typed contract so side effects stay predictable across renders and teardown.","Type the onmessage handler as (e: MessageEvent) => void and parse e.data with JSON.parse, casting the result to T so invalid interactions are rejected by the compiler instead of leaking into runtime.","Model a useState<T | null> to store the latest typed message and update it in the message handler so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Return a send function typed as (payload: T) => void that calls ws.send(JSON.stringify(payload)) so consumers receive a stable contract and the effect of that contract can be tested immediately."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #77 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 77, title: "Optimistic UI (TS)", shortName: "TS — OPTIMISTIC UI" });
