import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #31 (TypeScript)", title: "useFetch — Typed", body: "Custom hook for data fetching with loading/error/data + AbortController cleanup Use TypeScript where appropriate.", usecase: "Reusable fetch with cleanup avoids leaks." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a custom hook useToggle(initialValue: boolean): [boolean, () => void] with explicit return type so the abstraction solves a concrete UI problem and exposes a reliable typed contract.","Implement the toggle function using the functional form of useState setter: setVal(v => !v) so the feature works end to end, and data shape and updates remain explicit throughout the lesson.","Return a tuple typed as [boolean, () => void] and destructure it at the call site so consumers receive a stable contract and the effect of that contract can be tested immediately.","Extend the hook to accept an optional forceValue: boolean parameter typed in the setter overload so reuse does not weaken the contract or blur responsibility."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #31 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 31, title: "useFetch (TS)", shortName: "TS — USEFETCH" });
