import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #45 (TypeScript)", title: "Context Performance — Typed", body: "Fix Context that re-renders entire tree — split or memo Use TypeScript where appropriate.", usecase: "Avoid over-renders." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Wrap a typed child component with React.memo to prevent re-renders when parent state changes but its props have not so the boundary is explicit and the fallback or optimization can be verified at runtime and verify whether stable props actually reduce avoidable re-renders.","Stabilize a callback prop using useCallback with a typed signature to avoid breaking React.memo so the learner can explain both the mechanism and the visible result and verify whether stable props actually reduce avoidable re-renders.","Use the React DevTools Profiler to identify which typed components re-render and record the cause so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler and validate the behavior with runtime evidence, not guesswork.","Lift an unchanged state variable out of a frequently-updating parent to eliminate child re-renders so the learner can explain both the mechanism and the visible result."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #45 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 45, title: "Context Performance (TS)", shortName: "TS — CONTEXT PERFORMANC" });
