import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #5 (TypeScript)", title: "Conditional Rendering with Ternary — Typed", body: "A status card that shows different content based on a boolean. Use useState<boolean> and type the conditional branches.", usecase: "Typing the state that drives conditional render keeps branches type-safe." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use a boolean state variable to drive a ternary expression that renders one of two typed components so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Apply the && short-circuit operator to conditionally render a JSX element so the learner sees how a typed pattern changes behavior, reuse, or safety in practice so the UI exposes only the branch that matches the current state.","Type a conditional render helper function with return type JSX.Element | null so invalid interactions are rejected by the compiler instead of leaking into runtime.","Pass a boolean prop to a child component and use it to switch between two render paths so data crossing component boundaries stays explicit, safe, and easy to trace."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create boolean state for logged-in vs signed-out; initialize signed-out.", answer_keywords: ["usestate", "boolean", "isloggedin"], seed_code: "import { useState } from 'react'\n\nexport default function StatusCard() {\n  // Step 1: useState<boolean>\n}", feedback_correct: "✅ Boolean state typed.", feedback_partial: "useState<boolean>.", feedback_wrong: "useState<boolean>(false)", expected: "useState<boolean>" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Render one message when logged in and another when not; keep the branch explicit in JSX.", answer_keywords: ["?", "isloggedin", "welcome", "sign in"], seed_code: "import { useState } from 'react'\n\nexport default function StatusCard() {\n  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false)\n  return <div>{isLoggedIn ? 'Welcome back!' : 'Please sign in'}</div>\n}", feedback_correct: "✅ Ternary render.", feedback_partial: "Conditional text with ternary.", feedback_wrong: "isLoggedIn ? '...' : '...'", expected: "Ternary for message" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Add controls that sign the user in and out; export the component.", answer_keywords: ["button", "setisloggedin", "login", "logout"], seed_code: "import { useState } from 'react'\n\nexport default function StatusCard() {\n  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false)\n  return (\n    <div>\n      {isLoggedIn ? 'Welcome back!' : 'Please sign in'}\n      <button onClick={() => setIsLoggedIn(true)}>Login</button>\n      <button onClick={() => setIsLoggedIn(false)}>Logout</button>\n    </div>\n  )\n}", feedback_correct: "✅ Conditional rendering with TypeScript complete.", feedback_partial: "Buttons to toggle state.", feedback_wrong: "Login/Logout buttons.", expected: "Add Login and Logout buttons that call setIsLoggedIn(true) and setIsLoggedIn(false). Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 5, title: "Conditional Rendering with Ternary (TS)", shortName: "TS — TERNARY" });
