import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #42 (TypeScript)", title: "Auth Context — Typed", body: "Mock auth: login, logout, protected route, user in context Use TypeScript where appropriate.", usecase: "Auth state and guards." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Split a single context into two typed contexts — one for state and one for dispatch — to limit re-render scope so the learner can explain both the mechanism and the visible result.","Wrap the context value object in useMemo with a typed return to prevent unnecessary consumer re-renders so the boundary is explicit and the fallback or optimization can be verified at runtime.","Wrap dispatch callbacks in useCallback with explicit return type () => void to stabilize references so the boundary is explicit and the fallback or optimization can be verified at runtime.","Use react.memo on a typed consumer component and verify it skips re-render when irrelevant context changes so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler and verify whether stable props actually reduce avoidable re-renders."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #42 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 42, title: "Auth Context (TS)", shortName: "TS — AUTH CONTEXT" });
