import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #97 (TypeScript)", title: "Design Auth Flow — Typed", body: "Login, token storage, refresh, protected routes, logout Use TypeScript where appropriate.", usecase: "Auth design." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Call useId() and assign its string return value to a const to generate a stable, unique ID per component instance so the hook or API is used with an intentional contract and observable outcome.","Use the generated ID to associate a <label> htmlFor with an <input> id to satisfy accessibility requirements so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Append a suffix to the base ID (e.g. id + '-input') to create multiple related typed IDs within one component so the learner can explain both the mechanism and the visible result.","Demonstrate that useId produces different IDs across multiple instances of the same component so the learner can observe the consequence and attach a mental model to it."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #97 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 97, title: "Design Auth Flow (TS)", shortName: "TS — DESIGN AUTH FLOW" });
