import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #36 (TypeScript)", title: "usePrevious — Typed", body: "Return the previous value of any state using useRef Use TypeScript where appropriate.", usecase: "Compare prev vs current." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Write a custom hook useOnlineStatus(): boolean that returns navigator.onLine as initial state so the abstraction solves a concrete UI lesson and exposes a reliable typed contract.","Attach online and offline event listeners to window in useEffect and update boolean state in each handler so the event or DOM boundary behaves correctly and can be verified during interaction so side effects stay predictable across renders and teardown.","Return a cleanup function from useEffect that removes both event listeners so consumers receive a stable contract and the effect of that contract can be tested immediately so the effect leaves no stale subscriptions, timers, or listeners behind.","Consume the boolean return value in a component to render a typed status indicator so the learner can connect the typed API to real screen behavior."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #36 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 36, title: "usePrevious (TS)", shortName: "TS — USEPREVIOUS" });
