import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #99 (TypeScript)", title: "Design Permission System — Typed", body: "Can action resource component, roles data model Use TypeScript where appropriate.", usecase: "Permissions." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Instantiate an AbortController inside useEffect and pass its signal to the fetch call as a typed RequestInit field so the generic or runtime object proves its value in a concrete case so async data is handled with an explicit and safe data shape.","Return controller.abort() as the cleanup function from useEffect to cancel the request on unmount so consumers receive a stable contract and the effect of that contract can be tested immediately so the effect leaves no stale subscriptions, timers, or listeners behind.","Catch the AbortError by name in the catch block to distinguish a user-cancelled request from a real network failure so the learner can explain both the mechanism and the visible result.","Demonstrate that without the abort cleanup a component that unmounts mid-fetch still calls setState and logs a warning so the learner can observe the consequence and attach a mental model to it so the effect leaves no stale subscriptions, timers, or listeners behind."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #99 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 99, title: "Design Permission System (TS)", shortName: "TS — DESIGN PERMISSION " });
