import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #44 (TypeScript)", title: "Notification Context — Typed", body: "Toast system: push, auto-dismiss, stack limit Use TypeScript where appropriate.", usecase: "Global toasts." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a parent Tabs component that holds activeTab state and exposes it via a typed context so the design pattern is reusable and its contract is clear to downstream code.","Build tab and TabPanel child components that consume the typed context to determine visibility so multiple typed pieces work together as one coherent UI pattern.","Attach child components as static properties on the parent (Tabs.Tab, Tabs.Panel) with typed signatures so the event or DOM boundary behaves correctly and can be verified during interaction.","Compose the compound component at the call site using only JSX nesting with no explicit prop threading so the learner sees how smaller typed pieces form a larger UI capability."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #44 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 44, title: "Notification Context (TS)", shortName: "TS — NOTIFICATION CONTE" });
