import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #85 (TypeScript)", title: "Micro-frontend Shell — Typed", body: "Sketch React as micro-frontend with Module Federation Use TypeScript where appropriate.", usecase: "Micro-frontends." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Identify a tearing bug caused by reading from an external store without useSyncExternalStore and fix it so the learner can spot the failure mode before applying the fix.","Replace a direct state mutation in a transition with an immutable update to prevent concurrent mode inconsistencies so the learner can explain both the mechanism and the visible result.","Wrap a state update in startTransition to demonstrate deferred rendering for a slow non-urgent update so the boundary is explicit and the fallback or optimization can be verified at runtime.","Use the React DevTools Profiler in concurrent mode to observe interrupted renders and commit phases so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler and validate the behavior with runtime evidence, not guesswork."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #85 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 85, title: "Micro-frontend Shell (TS)", shortName: "TS — MICROFRONTEND SHEL" });
