import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #57 (TypeScript)", title: "Controlled DatePicker — Typed", body: "Fully controlled DatePicker component Use TypeScript where appropriate.", usecase: "Controlled pattern." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a TreeNode interface with id, label, and an optional children: TreeNode[] recursive field so the contract is explicit and incorrect usage is caught early.","Write a TreeNode component typed as React.FC<{ node: TreeNode }> that calls itself for each child node so the abstraction solves a concrete UI lesson and exposes a reliable typed contract.","Model a useState<Set<string>> to track expanded node IDs and update it in a typed toggle handler so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Use the && operator to conditionally render children only when a node's ID is in the expanded set so the pattern drives visible behavior, and the UI exposes only the branch that matches the current state."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #57 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 57, title: "Controlled DatePicker (TS)", shortName: "TS — CONTROLLED DATEPIC" });
