import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #41 (TypeScript)", title: "Theme Context — Typed", body: "Dark/light mode toggle using Context + useReducer Use TypeScript where appropriate.", usecase: "Global theme state." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a Notification interface and a string literal union type for notification kind ('info' | 'success' | 'error') so the contract is explicit and incorrect usage is caught early.","Create a typed NotificationContext and implement addNotification typed as (n: Omit<Notification, 'id'>) => void so the design pattern is reusable, and shared data can move without losing type safety across components.","Use .filter() in a removeNotification function typed as (id: string) => void to update notification state so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Consume the context in a component to dispatch a typed notification and render the list with .map() so the learner can connect the typed API to real screen behavior."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #41 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 41, title: "Theme Context (TS)", shortName: "TS — THEME CONTEXT" });
