import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #88 (TypeScript)", title: "Bundle Analysis — Typed", body: "Webpack Bundle Analyzer + code splitting for slow load Use TypeScript where appropriate.", usecase: "Bundle size." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Render a component that fetches data using render from @testing-library/react with typed mock props so the learner can connect the typed data shape to the final UI output so async data is handled with an explicit and safe data shape.","Use waitFor or findByText to assert that async content appears in the DOM after the mock resolves so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Mock a named module export using vi.mock or jest.mock and type the mock implementation to match the real signature so tests stay realistic while preserving the same contract as production code.","Assert that an error message renders when the mock fetch rejects with a typed Error object so the expected behavior is proven rather than assumed so async data is handled with an explicit and safe data shape."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #88 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 88, title: "Bundle Analysis (TS)", shortName: "TS — BUNDLE ANALYSIS" });
