import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #78 (TypeScript)", title: "Request Deduplication — Typed", body: "Fetch layer that prevents duplicate in-flight same URL Use TypeScript where appropriate.", usecase: "Dedup fetch." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Establish a FeatureFlags interface with boolean fields for each flag and create a typed context for it so the contract is explicit and incorrect usage is caught early.","Write a useFeatureFlag(flag: keyof FeatureFlags): boolean hook that reads and returns the typed flag value so the abstraction solves a concrete UI problem and exposes a reliable typed contract.","Consume useFeatureFlag in a component to conditionally render a typed JSX block with the && operator so the learner can connect the typed API to real screen behavior, and the UI exposes only the branch that matches the current state.","Implement a FeatureFlagProvider that merges server-fetched flags with a typed default flags object so the feature works end to end, and async data is handled with an explicit and safe data shape."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #78 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 78, title: "Request Deduplication (TS)", shortName: "TS — REQUEST DEDUPLICAT" });
