import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #55 (TypeScript)", title: "HOC withAuth — Typed", body: "withAuth HOC that redirects unauthenticated users Use TypeScript where appropriate.", usecase: "Auth HOC." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Use reactDOM.createPortal to render a typed JSX element into a DOM node outside the component tree so the pattern drives visible behavior and can be verified in the UI, runtime, or compiler.","Select the portal target using document.getElementById and narrow its type from Element | null to Element with a null check so the learner can explain both the mechanism and the visible result.","Wrap portal rendering in a typed Modal component that accepts children as React.ReactNode and an isOpen boolean so the boundary is explicit and the fallback or optimization can be verified at runtime.","Attach a keydown handler typed as (e: KeyboardEvent) => void to close the modal on Escape key press so the event or DOM boundary behaves correctly and can be verified during interaction."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #55 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 55, title: "HOC withAuth (TS)", shortName: "TS — HOC WITHAUTH" });
