import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #23 (TypeScript)", title: "CSS Modules — Typed", body: "Simulate CSS Modules with a typed styles object. Use Record<string, string> for the styles object so className is type-safe.", usecase: "Typing module-style class maps in TS." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Implement a controlled input by binding value to a useState<string> variable and onChange to a typed handler so the feature works end to end, and data shape and updates remain explicit throughout the lesson.","Implement an uncontrolled input using useRef<HTMLInputElement>(null) and reading .current.value on submit so the feature works end to end and the resulting behavior can be observed and explained.","Type a ref as React.RefObject<HTMLInputElement> and access its .current property safely with a null check so invalid interactions are rejected by the compiler instead of leaking into runtime.","Demonstrate the compiler difference between a typed controlled handler and a ref read at point-of-use so the learner can observe the consequence and attach a mental model to it."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create a component that wraps content in a div with padding and border via inline styles.", answer_keywords: ["div", "style", "padding", "border"], seed_code: "export default function Card() {\n  return <div style={{ padding: 16, border: '1px solid #333' }}>Content</div>\n}", feedback_correct: "✅ Component with inline styles.", feedback_partial: "div with padding and border.", feedback_wrong: "style object", expected: "div with style" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Introduce a typed map of class names; apply one entry to the wrapper via className.", answer_keywords: ["record", "string", "styles", "classname"], seed_code: "const styles: Record<string, string> = { card: 'card' }\n\nexport default function Card() {\n  return (\n    <div className={styles.card} style={{ padding: 16, border: '1px solid #333' }}>\n      Content\n    </div>\n  )\n}", feedback_correct: "✅ Typed styles object.", feedback_partial: "Record<string, string> and className.", feedback_wrong: "styles.card", expected: "Record<string, string> and className={styles.card}." },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Note why scoped class maps help avoid global CSS collisions; export the component.", answer_keywords: ["//", "scope", "export"], seed_code: "// CSS Modules scope class names to avoid global clashes\nconst styles: Record<string, string> = { card: 'card' }\n\nexport default function Card() {\n  return <div className={styles.card} style={{ padding: 16, border: '1px solid #333' }}>Content</div>\n}", feedback_correct: "✅ CSS Modules pattern with TypeScript complete.", feedback_partial: "Comment and export.", feedback_wrong: "export default", expected: "Comment about CSS Modules scoping. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 23, title: "CSS Modules (TS)", shortName: "TS — CSS MODULES" });
