import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #98 (TypeScript)", title: "Design Notification System — Typed", body: "Toasts: types, auto-dismiss, max 3, queue Use TypeScript where appropriate.", usecase: "Notification design." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Wrap a functional component with React.forwardRef<HTMLInputElement, InputProps> to accept a typed ref from a parent so the boundary is explicit and the fallback or optimization can be verified at runtime.","Attach the forwarded ref to the underlying <input> DOM element via the ref prop so the event or DOM boundary behaves correctly and can be verified during interaction.","Model a useRef<HTMLInputElement>(null) in the parent and pass it to the forwarded component to call .focus() so state, refs, or values keep a predictable shape as the feature evolves.","Combine forwardRef with useImperativeHandle to expose a limited typed API instead of the raw DOM node so the learner can explain both the mechanism and the visible result."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create the structure and typed state this lesson needs; initialize defaults appropriately.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core behavior or UI; keep types explicit throughout.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire interactions, complete the UI, and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #98 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 98, title: "Design Notification System (TS)", shortName: "TS — DESIGN NOTIFICATIO" });
