import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #90 (TypeScript)", title: "Memory Leak Hunt — Typed", body: "Find and fix: listener, interval, subscription not cleaned Use TypeScript where appropriate.", usecase: "Memory leaks." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create a typed custom render function that wraps the component under test in a typed context Provider so the design pattern is reusable and its contract is clear to downstream code.","Assert that a component correctly reads a typed context value by inspecting its rendered output so the expected behavior is proven rather than assumed.","Simulate a context value change by re-rendering with a different typed provider value and asserting the UI update so the learner can verify behavior from the user perspective rather than only from implementation details.","Test a useContext-based custom hook using renderHook wrapped in a typed Provider so the learner can explain both the mechanism and the visible result, and shared data can move without losing type safety across components."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Set up the initial structure and typed state for this problem.", answer_keywords: ["import", "usestate", "interface"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add typed setup.", feedback_wrong: "Set up structure", expected: "Initial setup" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Implement the core logic or UI with proper types.", answer_keywords: ["return", "type"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Core logic in place.", feedback_wrong: "Implement core", expected: "Core implementation" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Wire everything together and export the typed component.", answer_keywords: ["export", "default"], seed_code: "import { useState } from 'react'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Problem #90 (TS) complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 90, title: "Memory Leak Hunt (TS)", shortName: "TS — MEMORY LEAK HUNT" });
