import createINPACTEngine from "../inpact_engine_shared";
const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #9 (TypeScript)", title: "Color Picker — Typed", body: "Dropdown that sets a div background. Use useState<string> for the selected color and type the option values.", usecase: "Typing string union state (e.g. 'red' | 'green' | 'blue') gives autocomplete." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Model a string state variable to hold a CSS hex color value using useState<string> so state, refs, or values keep a predictable shape as the feature evolves, and data shape and updates remain explicit throughout the lesson.","Type a change handler for an <input type='color'> as React.ChangeEventHandler<HTMLInputElement> so invalid interactions are rejected by the compiler instead of leaking into runtime.","Apply the selected color as an inline style using React.CSSProperties typed object so the learner sees how a typed pattern changes behavior, reuse, or safety in practice.","Establish a ColorPickerProps interface with an onColorChange callback typed as (color: string) => void so the contract is explicit and incorrect usage is caught early."] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Define and create string state for the chosen color; initialize to a sensible default.", answer_keywords: ["usestate", "string", "color", "setcolor"], seed_code: "import { useState } from 'react'\n\nexport default function ColorPicker() {\n  // Step 1: useState<string>('red')\n}", feedback_correct: "✅ Color state typed.", feedback_partial: "useState<string> for color.", feedback_wrong: "const [color, setColor] = useState<string>('red')", expected: "useState<string>" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add a select bound to that state; handle changes with a typed select change event.", answer_keywords: ["select", "value", "onchange", "setcolor"], seed_code: "import { useState } from 'react'\n\nexport default function ColorPicker() {\n  const [color, setColor] = useState<string>('red')\n  return (\n    <select value={color} onChange={e => setColor(e.target.value)}>\n      <option value=\"red\">Red</option>\n      <option value=\"green\">Green</option>\n      <option value=\"blue\">Blue</option>\n    </select>\n  )\n}", feedback_correct: "✅ Select wired with typed state.", feedback_partial: "value and onChange.", feedback_wrong: "select with value and onChange", expected: "Controlled select" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Preview the color on a block (e.g. background driven by state); export the component.", answer_keywords: ["div", "style", "backgroundcolor", "export"], seed_code: "import { useState } from 'react'\n\nexport default function ColorPicker() {\n  const [color, setColor] = useState<string>('red')\n  return (\n    <div>\n      <select value={color} onChange={e => setColor(e.target.value)}>\n        <option value=\"red\">Red</option>\n        <option value=\"green\">Green</option>\n        <option value=\"blue\">Blue</option>\n      </select>\n      <div style={{ backgroundColor: color, minHeight: 100 }} />\n    </div>\n  )\n}", feedback_correct: "✅ Color Picker with TypeScript complete.", feedback_partial: "Div with backgroundColor.", feedback_wrong: "style={{ backgroundColor: color }}", expected: "Div with style={{ backgroundColor: color }}. Export the component." },
];
const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 9, title: "Color Picker (TS)", shortName: "TS — COLOR PICKER" });
