export const REACT_TS_CURRICULUM = [
  { title: "JSX — The Full Language", prereqs: [] },
  { title: "TypeScript — Interfaces + Types", prereqs: [1] },
  { title: "TypeScript — Utility Types", prereqs: [1, 2] },
  { title: "TypeScript — Generics in Components", prereqs: [1, 2, 3] },
  { title: "Props + Interface", prereqs: [1, 2] },
  { title: "Optional Props + Defaults", prereqs: [1, 2, 5] },
  { title: "children Prop + ReactNode", prereqs: [1, 2, 5, 6] },
  { title: "useState — Primitives", prereqs: [1] },
  { title: "useState — Objects + Spread", prereqs: [1, 8] },
  { title: "useState — Arrays", prereqs: [1, 8, 9] },
  { title: "Controlled Inputs", prereqs: [1, 8] },
  { title: "Controlled Select + Union Types", prereqs: [1, 2, 8, 11] },
  { title: "Conditional Rendering", prereqs: [1, 8] },
  { title: "List Rendering + key", prereqs: [1, 8, 9] },
  { title: "Event Handling — Click", prereqs: [1, 8] },
  { title: "Event Handling — Input + Form", prereqs: [1, 8, 11] },
  { title: "Event Handling — Keyboard + Focus", prereqs: [1, 8, 11, 16] },
  { title: "Component Composition", prereqs: [1, 5, 6, 7] },
  { title: "Conditional CSS Classes", prereqs: [1, 8, 13] },
  { title: "Inline Styles + CSSProperties", prereqs: [1, 2, 8] },
  { title: "CSS Modules", prereqs: [1, 8, 14] },
  { title: "useEffect — Mount", prereqs: [1, 8] },
  { title: "useEffect — Dependencies", prereqs: [1, 8, 22] },
  { title: "useEffect — Cleanup", prereqs: [1, 8, 22, 23] },
  { title: "useLayoutEffect vs useEffect", prereqs: [1, 8, 22, 23, 24] },
  { title: "fetch + Loading + Error State", prereqs: [1, 8, 22, 23] },
  { title: "AbortController", prereqs: [1, 8, 22, 23, 24, 26] },
  { title: "useRef — DOM Access", prereqs: [1, 8, 22] },
  { title: "useRef — Mutable Values", prereqs: [1, 8, 22, 28] },
  { title: "useReducer", prereqs: [1, 8, 9] },
  { title: "Custom Hook — Extract Logic", prereqs: [1, 8, 22, 23] },
  { title: "Custom Hook — useFetch", prereqs: [1, 8, 22, 23, 26, 31] },
  { title: "Custom Hook — useDebounce", prereqs: [1, 8, 22, 23, 31] },
  { title: "Custom Hook — useLocalStorage", prereqs: [1, 8, 22, 31] },
  { title: "Custom Hook — useWindowSize", prereqs: [1, 8, 22, 23, 24, 31] },
  { title: "Custom Hook — useClickOutside", prereqs: [1, 8, 22, 23, 28, 31] },
  { title: "Custom Hook — useKeyPress", prereqs: [1, 8, 17, 22, 23, 31] },
  { title: "Custom Hook — useOnlineStatus", prereqs: [1, 8, 22, 23, 31] },
  { title: "Custom Hook — useMediaQuery", prereqs: [1, 8, 22, 23, 24, 31] },
  { title: "Custom Hook — useWebSocket", prereqs: [1, 8, 22, 23, 26, 31] },
  { title: "Custom Hook — usePolling", prereqs: [1, 8, 22, 23, 26, 31] },
  { title: "React.memo", prereqs: [1, 5, 6, 8, 18] },
  { title: "useMemo", prereqs: [1, 8, 22, 42] },
  { title: "useCallback", prereqs: [1, 8, 22, 42, 43] },
  { title: "Identifying Re-renders", prereqs: [1, 8, 42, 43, 44] },
  { title: "List Virtualization — react-window", prereqs: [1, 8, 10, 14, 42] },
  { title: "Code Splitting + React.lazy", prereqs: [1, 8, 22] },
  { title: "Suspense + Fallback", prereqs: [1, 8, 47] },
  { title: "useTransition — React 18", prereqs: [1, 8, 22, 43] },
  { title: "useDeferredValue — React 18", prereqs: [1, 8, 22, 43, 49] },
  { title: "Image Lazy Loading", prereqs: [1, 8, 28] },
  { title: "Context API — createContext + useContext", prereqs: [1, 2, 8, 13] },
  { title: "Context — Theme Provider", prereqs: [1, 2, 8, 52] },
  { title: "Context — Auth Provider", prereqs: [1, 2, 8, 52, 53] },
  { title: "Context Performance — Split + Memo", prereqs: [1, 8, 42, 43, 44, 52] },
  { title: "Zustand — Store Basics", prereqs: [1, 8, 22] },
  { title: "Zustand — UI State", prereqs: [1, 8, 56] },
  { title: "Zustand — Persist Middleware", prereqs: [1, 8, 56, 57] },
  { title: "Mini Redux from Scratch", prereqs: [1, 8, 30] },
  { title: "Redux Toolkit — createSlice", prereqs: [1, 8, 59] },
  { title: "Redux Toolkit — configureStore", prereqs: [1, 8, 60] },
  { title: "Redux Toolkit — useSelector + useDispatch", prereqs: [1, 8, 60, 61] },
  { title: "RTK — createAsyncThunk", prereqs: [1, 8, 26, 60, 61, 62] },
  { title: "RTK — Entity Adapter", prereqs: [1, 8, 60, 61, 62, 63] },
  { title: "RTK Query — createApi", prereqs: [1, 8, 26, 60] },
  { title: "RTK Query — useQuery", prereqs: [1, 8, 65] },
  { title: "RTK Query — useMutation", prereqs: [1, 8, 65, 66] },
  { title: "RTK Query — WebSocket Listener", prereqs: [1, 8, 40, 65, 66] },
  { title: "TanStack Query — useQuery", prereqs: [1, 8, 26, 31] },
  { title: "TanStack Query — useMutation", prereqs: [1, 8, 69] },
  { title: "TanStack Query — Infinite Scroll", prereqs: [1, 8, 69, 70] },
  { title: "TanStack Query — Optimistic Updates", prereqs: [1, 8, 69, 70, 71] },
  { title: "Compound Components", prereqs: [1, 2, 5, 6, 7, 52] },
  { title: "Render Props", prereqs: [1, 2, 4, 5, 6] },
  { title: "HOC — withAuth", prereqs: [1, 2, 5, 6, 54] },
  { title: "HOC — withPermission", prereqs: [1, 2, 5, 6, 75] },
  { title: "forwardRef", prereqs: [1, 5, 6, 28] },
  { title: "useImperativeHandle", prereqs: [1, 5, 6, 28, 77] },
  { title: "Portal", prereqs: [1, 8, 22] },
  { title: "Error Boundary", prereqs: [1, 5, 6, 8] },
  { title: "Recursive Component — TreeView", prereqs: [1, 2, 5, 6, 10] },
  { title: "Generic Component — List<T>", prereqs: [1, 2, 3, 4, 5, 10] },
  { title: "Discriminated Union Props", prereqs: [1, 2, 5, 6, 13] },
  { title: "React Hook Form — Basics", prereqs: [1, 5, 6, 8, 11, 16] },
  { title: "React Hook Form — Validation", prereqs: [1, 5, 6, 84] },
  { title: "Zod — Schema Definition", prereqs: [1, 2, 3] },
  { title: "Zod + RHF — Integration", prereqs: [1, 84, 85, 86] },
  { title: "Multi-Step Form — Wizard", prereqs: [1, 8, 13, 84, 85] },
  { title: "Conditional Form Fields", prereqs: [1, 8, 13, 84, 85] },
  { title: "Draft Autosave", prereqs: [1, 8, 22, 23, 33, 84] },
  { title: "Form Array Fields", prereqs: [1, 10, 84, 85] },
  { title: "File Upload Component", prereqs: [1, 8, 11, 16, 84] },
  { title: "React Router — Setup + Basic Routes", prereqs: [1, 8] },
  { title: "React Router — useNavigate + useParams", prereqs: [1, 8, 93] },
  { title: "React Router — Nested Routes + Outlet", prereqs: [1, 8, 93, 94] },
  { title: "Protected Route — Auth Guard", prereqs: [1, 8, 54, 93, 94] },
  { title: "Protected Route — RBAC Guard", prereqs: [1, 8, 76, 93, 94, 96] },
  { title: "React Router — Lazy Routes", prereqs: [1, 8, 47, 48, 93] },
  { title: "JWT — Decode + Store", prereqs: [1, 8, 34] },
  { title: "Axios Interceptors — Token Attach", prereqs: [1, 8, 26, 99] },
  { title: "Axios Interceptors — Token Refresh", prereqs: [1, 8, 26, 99, 100] },
  { title: "Session Timeout Hook", prereqs: [1, 8, 22, 23, 99] },
  { title: "Cookie-Based Auth Flow", prereqs: [1, 8, 99, 100] },
  { title: "Multi-Tab Auth Sync", prereqs: [1, 8, 34, 99, 103] },
  { title: "OAuth2 PKCE Flow", prereqs: [1, 8, 99, 100, 101] },
  { title: "RBAC — usePermission Hook", prereqs: [1, 8, 52, 54, 99] },
  { title: "Secure Token Rotation", prereqs: [1, 8, 99, 100, 101, 105] },
  { title: "Optimistic UI", prereqs: [1, 8, 26, 66, 67, 69] },
  { title: "Race Condition Fix", prereqs: [1, 8, 26, 27, 32] },
  { title: "Request Deduplication", prereqs: [1, 8, 26, 32, 65] },
  { title: "Pagination — Controlled", prereqs: [1, 8, 10, 26, 66] },
  { title: "Infinite Scroll — useIntersectionObserver", prereqs: [1, 8, 22, 28, 71] },
  { title: "CSV/Excel Export", prereqs: [1, 8, 10, 15] },
  { title: "Clipboard API", prereqs: [1, 8, 15] },
  { title: "Date/Time Handling in UI", prereqs: [1, 8, 2] },
  { title: "Toast Notification System", prereqs: [1, 8, 52, 79] },
  { title: "Modal — Portal + Focus Trap", prereqs: [1, 8, 17, 79] },
  { title: "Accordion", prereqs: [1, 8, 13, 15] },
  { title: "Tabs — Compound Component", prereqs: [1, 8, 13, 73] },
  { title: "Drag and Drop — Reorder", prereqs: [1, 8, 10, 15] },
  { title: "Debounced Search", prereqs: [1, 8, 11, 33] },
  { title: "Star Rating Component", prereqs: [1, 8, 13, 15] },
  { title: "Image Gallery + Lightbox", prereqs: [1, 8, 10, 13, 51] },
  { title: "Undo/Redo", prereqs: [1, 8, 10, 30] },
  { title: "Conditional Classes — clsx", prereqs: [1, 8, 13, 19] },
  { title: "Styled Component Pattern", prereqs: [1, 8, 5, 20] },
  { title: "ARIA Roles + Labels", prereqs: [1, 8, 5] },
  { title: "Keyboard Navigation", prereqs: [1, 8, 17, 127] },
  { title: "Focus Management", prereqs: [1, 8, 28, 127, 128] },
  { title: "useId — Stable IDs", prereqs: [1, 8, 22, 127] },
  { title: "Testing — Render + Query", prereqs: [1, 5, 8] },
  { title: "Testing — User Interactions", prereqs: [1, 8, 15, 131] },
  { title: "Testing — Async Components", prereqs: [1, 8, 26, 131] },
  { title: "Testing — Context + Providers", prereqs: [1, 8, 52, 131] },
  { title: "Testing — Custom Hooks", prereqs: [1, 8, 31, 131] },
  { title: "Testing — Error Boundary", prereqs: [1, 8, 80, 131] },
  { title: "Testing — Mocking Axios", prereqs: [1, 8, 26, 100, 131] },
  { title: "Testing — RTK Query", prereqs: [1, 8, 65, 66, 67, 131] },
];

export const LESSON_LIST = REACT_TS_CURRICULUM.map((l) => l.title);
export const LESSON_PREREQS = REACT_TS_CURRICULUM.map((l) => l.prereqs);

export function getLessonPrereqs(lessonNumber) {
  const idx = lessonNumber - 1;
  if (idx < 0 || idx >= LESSON_PREREQS.length) return [];
  return LESSON_PREREQS[idx];
}

