import createINPACTEngine from "../inpact_engine_shared";

export const NODES = [
  {
    "id": "intro",
    "type": "reveal",
    "phase": "Lesson",
    "content": {
      "tag": "ui-integration-test-crud-flows",
      "title": "Automating End-to-End UI Tests for CRUD Flows",
      "body": "\n        Manual testing of user interfaces is a time-consuming and error-prone process. As applications grow and evolve, even small changes can inadvertently break existing functionality, leading to regressions that impact user experience and data integrity. Automated UI tests address this challenge by simulating real user interactions with the application's interface, allowing developers to quickly and reliably verify that core features, especially those involving Create, Read, Update, and Delete (CRUD) operations, continue to work as expected after code changes. This proactive approach catches bugs early in the development cycle, saving significant time and resources compared to discovering them in production.\n\n        The patterns for automating UI tests for CRUD flows are highly transferable across various application types. You'll find this approach invaluable when testing any management interface, such as a user account dashboard, a product catalog editor, a task list manager, or a settings configuration panel. By mastering the techniques to script these end-to-end interactions, you gain the ability to build robust test suites that provide continuous confidence in the stability and correctness of your application's most critical user-facing features, regardless of the specific business domain.\n      ",
      "usecase": "Ensuring a user management panel correctly handles adding new users, updating their profiles, and removing them from the system."
    }
  },
  {
    "id": "objectives",
    "type": "objectives",
    "phase": "Objectives",
    "items": [
      "Understand the purpose of end-to-end UI testing for CRUD operations.",
      "Learn to set up a basic UI test suite using a modern testing framework.",
      "Practice scripting user interactions to create, read, update, and delete data.",
      "Implement assertions to verify UI state changes after each operation.",
      "Recognize common pitfalls and best practices in UI test automation."
    ]
  },
  {
    "id": "step1",
    "type": "question",
    "phase": "Step 1 of 5",
    "paal": "To begin automating UI tests, the first step is to set up your test file. This involves importing the necessary testing utilities and defining a test suite that groups related tests together.",
    "hint": "Think about the basic structure provided by UI testing frameworks for organizing tests.",
    "example_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  // Tests for creating, editing, and deleting items will go here.\n});",
    "think_prompt": "Which option correctly sets up a basic test file for UI testing, including imports and a test suite definition?",
    "mc_options": [
      "import { describe, it } from 'mocha'; describe('Test Suite', () => { it('should work', () => {}); });",
      "import { test, expect } from '@playwright/test'; test.describe('Item Management CRUD', () => { /* ... */ });",
      "const test = require('test'); test.suite('My Suite', () => { test.case('My Case', () => {}); });"
    ],
    "mc_correct_option": "import { test, expect } from '@playwright/test'; test.describe('Item Management CRUD', () => { /* ... */ });",
    "mc_anchor": "test.describe",
    "why_this_matters": "A well-structured test suite improves readability, maintainability, and allows for targeted execution of specific test groups. Proper imports ensure all necessary testing functions are available.",
    "answer_keywords": [
      "import",
      "test.describe",
      "test suite",
      "Playwright"
    ],
    "seed_code": "",
    "starter_code": "// Import the necessary testing utilities and define your test suite here.\n// Use 'test' and 'expect' from '@playwright/test'.\n// Name your test suite 'Item Management CRUD'.",
    "feedback_correct": "Excellent! You've correctly set up the test file with the required imports and a `test.describe` block, which is the standard way to group tests in Playwright.",
    "feedback_partial": "You're on the right track with importing, but ensure you're using the correct syntax for defining a test suite with Playwright's `test.describe`.",
    "feedback_wrong": "This option uses a different testing framework's syntax. Remember to use `import { test, expect } from '@playwright/test';` and `test.describe` for Playwright.",
    "expected": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  // Tests for creating, editing, and deleting items will go here.\n});",
    "analog_example": "// Analogous setup for a different testing scenario (e.g., a login flow)\nimport { test, expect } from '@playwright/test';\n\ntest.describe('User Authentication Flow', () => {\n  test('should allow a user to log in successfully', async ({ page }) => {\n    // Test steps for login...\n  });\n\n  test('should prevent login with invalid credentials', async ({ page }) => {\n    // Test steps for invalid login...\n  });\n});",
    "deepDiveLabel": "Why do we use `test.describe` and `test`?",
    "deepDive": {
      "hook": "Imagine you're trying to organize a massive library. If every single book was just thrown onto shelves randomly, finding anything would be a nightmare. You'd spend hours just locating one specific title. The same chaos can happen with automated tests. If you just write individual test cases without any structure, your test suite quickly becomes an unmanageable mess. When a test fails, it's hard to tell what part of the application it's even related to. When you want to run only tests related to a specific feature, you have no easy way to do so. This lack of organization leads to slow debugging, difficulty in understanding test coverage, and ultimately, a test suite that developers dread maintaining. Without a clear structure, your tests become a burden rather than an asset, undermining the very purpose of automation.",
      "pain": "⚠️ **Lesson:** Unorganized test files lead to confusion, slow debugging, and difficulty in managing test execution. Symptom: A single file with hundreds of 'test' calls, making it impossible to understand the scope or purpose of individual tests without reading each one in detail.",
      "mentalModel": "**Mental model:** The \"Test Filing Cabinet.\" Think of your entire test suite as a large filing cabinet. Each drawer in the cabinet is a 'test.describe' block, representing a major feature or component (e.g., \"User Management,\" \"Product Catalog\"). Inside each drawer, you have individual folders, which are your 'test' blocks, each containing a specific test case (e.g., \"Create New User,\" \"Edit Product Price\"). This hierarchical structure allows you to quickly locate, understand, and manage your tests, just as a well-organized filing cabinet helps you find documents efficiently.",
      "discover": "**Pattern - Test Suite Structure:**\n```typescript\nimport { test, expect } from '@playwright/test'; // 1. Import necessary functions\n\ntest.describe('Feature Name', () => { // 2. Group related tests for a feature\n  test.beforeEach(async ({ page }) => { // 3. Optional: Run code before each test in this suite\n    await page.goto('/feature-path');\n  });\n\n  test('should do something specific', async ({ page }) => { // 4. Define an individual test case\n    // ... test steps ...\n    await expect(page.locator('#element')).toBeVisible();\n  });\n\n  test('should do something else', async ({ page }) => { // Another test case\n    // ...\n  });\n});\n```\n-   **1. Imports:** Bring in `test` (for defining tests and suites) and `expect` (for making assertions) from your testing library.\n-   **2. `test.describe`:** This function groups a collection of related tests. It takes a description string and a callback function containing the tests.\n-   **3. `test.beforeEach` (and `test.afterEach`, `test.beforeAll`, `test.afterAll`):** Hooks that run code before/after each or all tests within the `describe` block, useful for setup/teardown.\n-   **4. `test`:** This function defines a single, independent test case. It also takes a description and an `async` callback function, often receiving a `page` object for browser interaction.",
      "quickRules": "**Quick rules:**\n-   ✅ Always group related tests within a `test.describe` block for clarity and organization.\n-   ✅ Use `test` for each individual, atomic test case to ensure isolation.\n-   ✅ Start each test file with the necessary imports from your testing framework.\n-   ✅ Give descriptive names to your `test.describe` blocks and `test` cases.\n-   ❌ Never write tests directly at the top level of a file without a `test.describe` or `test` wrapper.\n-   ❌ Avoid putting unrelated tests into the same `test.describe` block.\n-   ❌ Do not forget to import `test` and `expect` – your tests won't run without them.",
      "watchOut": "👀 **Watch out:** While it's tempting to put all your tests in one giant `test.describe` block or even just use individual `test` calls, this quickly becomes unmanageable. Think about how you'd find a specific test if you had 500 of them. Grouping is key. Also, ensure your test runner is configured to discover these files; simply writing them isn't enough.",
      "dryRun": "🔁 **Think:**\n1.  **Initial State:** An empty test file.\n2.  **Action 1:** Add `import { test, expect } from '@playwright/test';`.\n    *   **Result:** The `test` and `expect` functions are now available for use in this file.\n3.  **Action 2:** Add `test.describe('Item Management CRUD', () => { /* ... */ });`.\n    *   **Result:** A new test suite named 'Item Management CRUD' is registered with the test runner. Any `test` blocks placed inside this `describe` block will be associated with this suite. The test runner now knows how to categorize and potentially run these tests together.\n(Hint: The test runner uses these structures to build a tree of tests it can execute.)",
      "build": "**Learning focus:** Set up the basic structure of a UI test file by importing the testing library and defining a test suite."
    }
  },
  {
    "id": "step2",
    "type": "question",
    "phase": "Step 2 of 5",
    "paal": "Before interacting with specific elements, each test should navigate to the correct starting page. This ensures consistency and isolates tests from previous navigation states.",
    "hint": "Most UI testing frameworks provide a method on the `page` object to navigate to a URL.",
    "example_code": "test('should create a new item', async ({ page }) => {\n  await page.goto('/items'); // Navigate to the items list page\n  // ... rest of the test steps for creating an item\n});",
    "think_prompt": "How do you correctly navigate the browser to the '/items' path at the beginning of a test?",
    "mc_options": [
      "page.navigate('/items');",
      "await page.goto('/items');",
      "browser.url('/items');"
    ],
    "mc_correct_option": "await page.goto('/items');",
    "mc_anchor": "page.goto",
    "why_this_matters": "Starting each test from a known, consistent URL prevents flaky tests caused by unexpected previous states and makes tests more reliable and easier to debug.",
    "answer_keywords": [
      "page.goto",
      "navigate",
      "URL",
      "async/await"
    ],
    "seed_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  // Tests for creating, editing, and deleting items will go here.\n});",
    "starter_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    // Navigate to the items list page here.\n    // Use the 'page' object provided by Playwright.\n  });\n});",
    "feedback_correct": "Correct! `await page.goto('/items');` is the standard Playwright method for navigating the browser to a specific URL, ensuring your test starts from the right place.",
    "feedback_partial": "You're close, but `page.navigate` is not the correct Playwright method. Remember to use `page.goto` and `await` for asynchronous operations.",
    "feedback_wrong": "This syntax belongs to a different testing tool. In Playwright, you use `page.goto` and must `await` its completion because navigation is an asynchronous operation.",
    "expected": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items'); // Navigate to the items list page\n    // ... rest of the test steps for creating an item\n  });\n});",
    "analog_example": "// Analogous navigation for a different test scenario (e.g., accessing user profile)\nimport { test, expect } from '@playwright/test';\n\ntest.describe('User Profile Management', () => {\n  test('should display user profile details', async ({ page }) => {\n    await page.goto('/profile/current'); // Navigate to the user's profile page\n    await expect(page.getByText('Welcome, John Doe')).toBeVisible();\n    // ... further assertions\n  });\n});",
    "deepDiveLabel": "Why is `page.goto` asynchronous and why do we need `await`?",
    "deepDive": {
      "hook": "Imagine you're sending a letter to someone. You put it in the mailbox, but you don't instantly know if it arrived, or if the recipient even opened it. You have to wait for a response, or at least for enough time to pass to assume it's been delivered. In programming, many operations are like sending a letter – they don't complete instantly. If your code tried to read the letter's contents immediately after sending it, it would fail because the letter hasn't arrived yet. This is precisely the problem with browser navigation. When you tell a browser to go to a URL, it doesn't instantly load the page. It sends a request, waits for a response, downloads assets, renders the page, and only then is the page fully ready for interaction. If your test script tries to click a button on the page *before* the page has finished loading, it will fail because the button isn't there yet. This leads to frustrating, intermittent test failures that are hard to diagnose.",
      "pain": "⚠️ **Lesson:** Asynchronous operations like page navigation take time to complete. Symptom: Tests fail with errors like \"Element not found\" or \"Cannot click on undefined\" because the script tried to interact with the page before it was fully loaded.",
      "mentalModel": "**Mental model:** The \"Page Loading Journey.\" When you call `page.goto()`, it's like telling a car to drive to a destination. The car doesn't instantly appear there; it has to travel. The `await` keyword is like waiting for the car to arrive and park before you try to open its door or look inside. Without `await`, your script would immediately try to open the door of a car that's still on the highway, leading to an error. `await` ensures your script pauses and waits for the browser to complete its entire page loading journey before moving on to the next interaction.",
      "discover": "**Pattern - Asynchronous Navigation:**\n```typescript\ntest('My test', async ({ page }) => { // 1. Mark the test function as 'async'\n  await page.goto('/some-path'); // 2. Use 'await' before asynchronous operations\n  // ... now the page is loaded and ready for interaction ...\n  await page.click('button'); // 3. Other interactions are also often asynchronous\n});\n```\n-   **1. `async` keyword:** The `async` keyword before a function declaration indicates that the function will perform asynchronous operations and can use the `await` keyword.\n-   **2. `await page.goto('/some-path')`:** The `page.goto()` method initiates navigation. `await` pauses the execution of the `async` function until the navigation is complete (i.e., the page has loaded and is ready).\n-   **3. Other `await` calls:** Many browser interactions (like `click`, `fill`, `waitForSelector`) are also asynchronous because they involve waiting for the browser to respond or for elements to become ready.\n-   **Error Handling:** If navigation fails (e.g., 404, network error), `await page.goto()` will throw an error, which can be caught or will fail the test.",
      "quickRules": "**Quick rules:**\n-   ✅ Always use `await` before `page.goto()` to ensure the page is fully loaded.\n-   ✅ Mark any test function that uses `await` with the `async` keyword.\n-   ✅ Understand that network requests and UI rendering are inherently asynchronous.\n-   ✅ Use `page.goto()` to establish a clean, consistent starting point for each test.\n-   ❌ Never omit `await` before `page.goto()` in an `async` function; it will lead to race conditions.\n-   ❌ Do not try to interact with elements immediately after `page.goto()` without `await`.\n-   ❌ Avoid hardcoding sleep timers (`setTimeout`) instead of using `await` for page readiness.",
      "watchOut": "👀 **Watch out:** Forgetting `await` is a common mistake that leads to \"flaky\" tests – tests that sometimes pass and sometimes fail without any code changes. This is because the timing of the page loading versus your script's execution can vary slightly. Always use `await` for `page.goto()` and other interactions that involve waiting for the browser.",
      "dryRun": "🔁 **Think:**\n1.  **Initial State:** Browser is on an unknown page, or a blank page.\n2.  **Action:** `test('...', async ({ page }) => { await page.goto('/items'); /* ... */ });` is executed.\n    *   **Transition 1:** The `page.goto('/items')` call is made. The browser starts navigating to the '/items' URL. The test execution *pauses* at the `await` keyword.\n    *   **Transition 2:** The browser completes loading the '/items' page. All HTML, CSS, and JavaScript are processed, and the page is rendered.\n    *   **Result:** The `await` keyword resolves, and the test execution *resumes*. The `page` object now represents the fully loaded '/items' page, and subsequent interactions can safely target elements on that page.\n(Hint: The `await` keyword acts as a synchronization point, ensuring the browser state matches the script's expectation.)",
      "build": "**Learning focus:** Implement navigation to a specific URL at the beginning of a test using `page.goto()`."
    }
  },
  {
    "id": "step3",
    "type": "question",
    "phase": "Step 3 of 5",
    "paal": "Now, let's script the 'Create' part of the CRUD flow. This involves locating form elements, filling them with data, submitting the form, and then asserting that the newly created item is visible in the UI.",
    "hint": "Use Playwright's `getByRole`, `getByLabel`, `fill`, `click`, and `expect().toBeVisible()` methods.",
    "example_code": "test('should create a new item', async ({ page }) => {\n  await page.goto('/items');\n  await page.getByRole('button', { name: 'Add New Item' }).click();\n  await page.getByLabel('Item Name').fill('New Test Item');\n  await page.getByLabel('Description').fill('This is a description for the new item.');\n  await page.getByRole('button', { name: 'Save' }).click();\n  await expect(page.getByText('New Test Item')).toBeVisible();\n});",
    "think_prompt": "Which sequence of actions correctly simulates creating a new item and verifies its presence?",
    "mc_options": [
      "await page.click('Add New Item'); await page.fill('Item Name', 'Test'); await page.click('Save'); await expect(page.text('Test')).toBeVisible();",
      "await page.getByRole('button', { name: 'Add New Item' }).click(); await page.getByLabel('Item Name').fill('Test Item'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByText('Test Item')).toBeVisible();",
      "page.locator('button:text(\"Add New Item\")').click(); page.locator('input[name=\"itemName\"]').fill('Test'); page.locator('button:text(\"Save\")').click(); expect(page.locator('text=\"Test\"')).toBeVisible();"
    ],
    "mc_correct_option": "await page.getByRole('button', { name: 'Add New Item' }).click(); await page.getByLabel('Item Name').fill('Test Item'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByText('Test Item')).toBeVisible();",
    "mc_anchor": "getByRole",
    "why_this_matters": "Simulating user input and verifying UI changes is the core of UI testing. Using robust selectors like `getByRole` and `getByLabel` makes tests less brittle to minor UI changes.",
    "answer_keywords": [
      "getByRole",
      "getByLabel",
      "fill",
      "click",
      "expect",
      "toBeVisible"
    ],
    "seed_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    // ... rest of the test steps for creating an item\n  });\n});",
    "starter_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    // Add steps here to:\n    // 1. Click the 'Add New Item' button (using getByRole).\n    // 2. Fill the 'Item Name' field with 'New Test Item' (using getByLabel).\n    // 3. Fill the 'Description' field with 'This is a description for the new item.' (using getByLabel).\n    // 4. Click the 'Save' button (using getByRole).\n    // 5. Assert that 'New Test Item' is visible on the page (using expect and getByText).\n  });\n});",
    "feedback_correct": "Excellent! You've correctly used Playwright's user-facing locators (`getByRole`, `getByLabel`, `getByText`) and actions (`click`, `fill`) to simulate creation and verify the outcome.",
    "feedback_partial": "You've got the general flow, but some of your Playwright locators or assertion methods aren't quite right. Focus on using `getByRole`, `getByLabel`, and `getByText` for robust element selection.",
    "feedback_wrong": "This option uses incorrect or less robust Playwright methods. Remember to prioritize user-facing locators like `getByRole` and `getByLabel` over generic CSS selectors for better test stability.",
    "expected": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n});",
    "analog_example": "// Analogous test for creating a new task in a task management app\nimport { test, expect } from '@playwright/test';\n\ntest.describe('Task Management', () => {\n  test('should add a new task', async ({ page }) => {\n    await page.goto('/tasks');\n    await page.getByRole('button', { name: 'New Task' }).click();\n    await page.getByPlaceholder('Task title').fill('Buy groceries');\n    await page.getByLabel('Due Date').fill('2024-12-31');\n    await page.getByRole('button', { name: 'Create Task' }).click();\n    await expect(page.getByText('Buy groceries')).toBeVisible();\n  });\n});",
    "deepDiveLabel": "What are 'user-facing locators' and why are they preferred?",
    "deepDive": {
      "hook": "Imagine you're giving directions to a friend to find a specific shop in a busy mall. You could say, \"Go to the third shop on the left after the big red sign, then look for the shop with the blue awning, which is the fifth element inside the div with class 'store-row'.\" Or, you could simply say, \"Go to 'The Coffee Bean' near the main entrance.\" Which set of directions is more reliable if the mall layout changes slightly, or if some shops get new paint jobs? The first set of directions is incredibly brittle; if the red sign moves, or a new shop is added, your friend gets lost. The second set of directions focuses on what a human user would actually look for – the name of the shop. In UI testing, relying on internal, implementation-specific details (like CSS classes or element indices) makes your tests fragile and prone to breaking with minor UI refactors, leading to constant test maintenance.",
      "pain": "⚠️ **Lesson:** Tests that rely on implementation-specific selectors (like CSS classes or XPath) are brittle and break easily with UI changes. Symptom: Tests fail frequently even when the application's visual appearance and user flow haven't functionally changed.",
      "mentalModel": "**Mental model:** The \"Human-First Navigator.\" When a human uses an application, they don't think in terms of `div.container > ul > li:nth-child(3) > button`. They think, \"I need to click the 'Add' button,\" or \"I need to type into the 'Username' field.\" User-facing locators are like giving your test script the same instructions a human would follow. Instead of telling the script *how* to find an element based on its internal structure, you tell it *what* the element is from a user's perspective. This makes your tests more resilient to underlying HTML/CSS changes, as long as the user experience remains functionally the same.",
      "discover": "**Pattern - User-Facing Locators:**\n```typescript\n// Instead of:\n// await page.locator('div.form-group > input#item-name').fill('New Item');\n// await page.locator('button.btn-primary').click();\n\n// Use user-facing locators:\nawait page.getByLabel('Item Name').fill('New Test Item'); // 1. By associated label text\nawait page.getByRole('button', { name: 'Save' }).click(); // 2. By ARIA role and accessible name\nawait expect(page.getByText('New Test Item')).toBeVisible(); // 3. By visible text content\n```\n-   **1. `page.getByLabel('Text')`:** Locates an input element by its associated `<label>` text. This is highly robust as users interact with labels.\n-   **2. `page.getByRole('role', { name: 'Accessible Name' })`:** Locates an element by its ARIA role (e.g., 'button', 'textbox', 'link') and its accessible name (the text a screen reader would announce). This is the most robust locator as it mimics how assistive technologies perceive the UI.\n-   **3. `page.getByText('Text')`:** Locates an element by its visible text content. Useful for verifying labels, messages, or content that appears on the page.\n-   **Other user-facing locators:** `getByPlaceholder`, `getByAltText`, `getByTitle`, `getByTestId` (when `data-testid` attributes are intentionally added for testing).",
      "quickRules": "**Quick rules:**\n-   ✅ Prioritize `getByRole` as the most robust and user-centric locator.\n-   ✅ Use `getByLabel` for form inputs that have associated labels.\n-   ✅ Employ `getByText` to assert the presence of specific content on the page.\n-   ✅ Consider `getByTestId` if your application explicitly adds `data-testid` attributes.\n-   ❌ Avoid using brittle CSS selectors like `div > span.some-class` unless absolutely necessary.\n-   ❌ Do not rely on element order (`nth-child`) as it's highly susceptible to layout changes.\n-   ❌ Never use XPath selectors unless there is no other robust alternative.\n-   ❌ Do not use IDs that are dynamically generated or not unique.",
      "watchOut": "👀 **Watch out:** While user-facing locators are generally superior, sometimes you might encounter elements without clear roles, labels, or unique text. In such cases, you might need to combine locators (e.g., `page.locator('.item-card').getByRole('button', { name: 'Delete' })`) or fall back to more specific CSS selectors, but always as a last resort and with caution.",
      "dryRun": "🔁 **Think:**\n1.  **Initial State:** Browser is on '/items' page, no new item visible.\n2.  **Action 1:** `await page.getByRole('button', { name: 'Add New Item' }).click();`\n    *   **Transition 1:** The 'Add New Item' button is found and clicked. The UI transitions to a form for creating a new item.\n3.  **Action 2:** `await page.getByLabel('Item Name').fill('New Test Item');`\n    *   **Transition 2:** The input field labeled 'Item Name' is found and its value is set to 'New Test Item'.\n4.  **Action 3:** `await page.getByRole('button', { name: 'Save' }).click();`\n    *   **Transition 3:** The 'Save' button is clicked. The form submits, and the UI transitions back to the '/items' list, now with the new item.\n5.  **Action 4:** `await expect(page.getByText('New Test Item')).toBeVisible();`\n    *   **Result:** Playwright waits for an element containing the text 'New Test Item' to appear and become visible. If it appears, the assertion passes. If not, the test fails.\n(Hint: Each interaction changes the UI state, and the assertion verifies the expected final state.)",
      "build": "**Learning focus:** Script the creation of a new item by interacting with form fields and asserting its presence in the UI."
    }
  },
  {
    "id": "step4",
    "type": "question",
    "phase": "Step 4 of 5",
    "paal": "Next, let's implement the 'Update' part of the CRUD flow. This involves finding an existing item, navigating to its edit form, modifying some details, saving the changes, and then asserting that the updated information is displayed correctly.",
    "hint": "You'll need to locate the item, click an 'Edit' button, fill fields, save, and assert both the new text's presence and the old text's absence.",
    "example_code": "test('should edit an existing item', async ({ page }) => {\n  await page.goto('/items');\n  // Assuming 'New Test Item' was created in a previous setup or test\n  await page.getByText('New Test Item').click(); // Or locate an 'Edit' button next to it\n  await page.getByRole('button', { name: 'Edit' }).click();\n  await page.getByLabel('Item Name').fill('Updated Test Item');\n  await page.getByRole('button', { name: 'Save' }).click();\n  await expect(page.getByText('Updated Test Item')).toBeVisible();\n  await expect(page.getByText('New Test Item')).not.toBeVisible(); // Verify old text is gone\n});",
    "think_prompt": "Which set of actions correctly simulates editing an item and verifies the update?",
    "mc_options": [
      "await page.click('New Item'); await page.click('Edit'); await page.fill('Item Name', 'Updated'); await page.click('Save'); await expect(page.text('Updated')).toBeVisible();",
      "await page.getByText('Original Item').click(); await page.getByRole('button', { name: 'Edit' }).click(); await page.getByLabel('Item Name').fill('Modified Item'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByText('Modified Item')).toBeVisible(); await expect(page.getByText('Original Item')).not.toBeVisible();",
      "page.locator('.item:has-text(\"Original Item\")').click(); page.locator('.edit-btn').click(); page.locator('input[name=\"name\"]').fill('Modified'); page.locator('.save-btn').click(); expect(page.locator('text=\"Modified\"')).toBeVisible();"
    ],
    "mc_correct_option": "await page.getByText('Original Item').click(); await page.getByRole('button', { name: 'Edit' }).click(); await page.getByLabel('Item Name').fill('Modified Item'); await page.getByRole('button', { name: 'Save' }).click(); await expect(page.getByText('Modified Item')).toBeVisible(); await expect(page.getByText('Original Item')).not.toBeVisible();",
    "mc_anchor": "not.toBeVisible",
    "why_this_matters": "Verifying updates requires checking both the presence of new data and the absence of old data. This ensures the update was successful and not just an addition, catching subtle UI bugs.",
    "answer_keywords": [
      "getByText",
      "getByRole",
      "fill",
      "click",
      "expect",
      "toBeVisible",
      "not.toBeVisible"
    ],
    "seed_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n});",
    "starter_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n\n  test('should edit an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assume 'New Test Item' already exists from a previous step or setup.\n    // Add steps here to:\n    // 1. Locate and click on 'New Test Item' (or its associated edit button).\n    // 2. Click the 'Edit' button.\n    // 3. Fill the 'Item Name' field with 'Updated Test Item'.\n    // 4. Click the 'Save' button.\n    // 5. Assert that 'Updated Test Item' is visible.\n    // 6. Assert that 'New Test Item' is no longer visible.\n  });\n});",
    "feedback_correct": "Spot on! You've correctly scripted the edit flow, including the crucial step of asserting that the old item name is no longer visible, confirming a true update.",
    "feedback_partial": "You've handled the update, but you missed a key assertion. It's important to verify that the *old* item name is no longer present, not just that the new one is visible.",
    "feedback_wrong": "This option uses less robust selectors or misses a critical assertion. Remember to use user-facing locators and assert both the presence of new data and the absence of old data.",
    "expected": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n\n  test('should edit an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assuming 'New Test Item' was created in a previous setup or test\n    await page.getByText('New Test Item').click(); // Or locate an 'Edit' button next to it\n    await page.getByRole('button', { name: 'Edit' }).click();\n    await page.getByLabel('Item Name').fill('Updated Test Item');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('Updated Test Item')).toBeVisible();\n    await expect(page.getByText('New Test Item')).not.toBeVisible(); // Verify old text is gone\n  });\n});",
    "analog_example": "// Analogous test for updating a user's email address\nimport { test, expect } from '@playwright/test';\n\ntest.describe('User Profile Updates', () => {\n  test('should update user email successfully', async ({ page }) => {\n    await page.goto('/settings');\n    await page.getByLabel('Current Email').fill('new.email@example.com');\n    await page.getByRole('button', { name: 'Save Changes' }).click();\n    await expect(page.getByText('Profile updated successfully!')).toBeVisible();\n    await expect(page.getByText('old.email@example.com')).not.toBeVisible(); // Assuming this was the old email\n  });\n});",
    "deepDiveLabel": "Why is it important to assert both presence and absence?",
    "deepDive": {
      "hook": "Imagine you're checking if a magic trick worked. The magician claims to have turned a red ball into a blue ball. If you only look for the blue ball and find it, does that definitively mean the trick worked? What if the red ball is still hidden under the table, and the magician just pulled out a new blue ball? Your test would pass, but the trick (or the application's logic) would be flawed. In UI testing, simply asserting that the new data is visible isn't enough to confirm an update. It could mean the new data was *added* alongside the old, or that the old data is still present but hidden, leading to data duplication or incorrect states that a user might eventually encounter. This incomplete verification can allow subtle bugs to slip through, giving a false sense of security about your application's stability.",
      "pain": "⚠️ **Lesson:** Asserting only the presence of new data after an update can mask bugs where old data persists or duplicates. Symptom: Tests pass, but users report seeing both old and new versions of data, or incorrect historical data.",
      "mentalModel": "**Mental model:** The \"Before & After Snapshot.\" When you perform an update, you're essentially taking a snapshot of the UI *before* the change and comparing it to a snapshot *after* the change. For a successful update, the \"after\" snapshot should show the new state, and crucially, the old state should be entirely absent. It's not just about adding a new layer; it's about replacing the old layer with the new one. Your assertions should reflect this complete transformation, ensuring that the UI accurately represents the single, current truth.",
      "discover": "**Pattern - Verifying Updates (Presence & Absence):**\n```typescript\n// Assuming 'Old Value' is the original text and 'New Value' is the updated text\nawait page.getByLabel('Input Field').fill('New Value');\nawait page.getByRole('button', { name: 'Save' }).click();\n\n// 1. Assert the new value is visible\nawait expect(page.getByText('New Value')).toBeVisible();\n\n// 2. Assert the old value is NOT visible\nawait expect(page.getByText('Old Value')).not.toBeVisible();\n\n// Optional: Assert other related elements are also updated or unchanged as expected\nawait expect(page.getByText('Status: Updated')).toBeVisible();\n```\n-   **1. `await expect(page.getByText('New Value')).toBeVisible();`:** This assertion confirms that the expected new content or state is now present and visible on the page.\n-   **2. `await expect(page.getByText('Old Value')).not.toBeVisible();`:** This is the critical second part. It verifies that the original content or state has been correctly removed or replaced, preventing scenarios where old data might linger.\n-   **Robustness:** Combining these two assertions provides a much stronger guarantee that the update operation was successful and the UI reflects the single, correct state.\n-   **Context:** The specific locators (`getByText`, `getByRole`, etc.) used will depend on how the old and new values are displayed in your application.",
      "quickRules": "**Quick rules:**\n-   ✅ Always assert that the new, expected data is visible after an update.\n-   ✅ Crucially, assert that the old, replaced data is no longer visible.\n-   ✅ Consider asserting any related status messages (e.g., \"Saved successfully\").\n-   ✅ Ensure your assertions are specific enough to avoid false positives (e.g., checking for a generic 'Item' vs. 'Updated Test Item').\n-   ❌ Never rely solely on the presence of new data to confirm an update.\n-   ❌ Do not assume that if new data appears, old data automatically disappears.\n-   ❌ Avoid making assertions on elements that might be visually hidden but still present in the DOM, unless that's the specific behavior you're testing.",
      "watchOut": "👀 **Watch out:** This is particularly important for fields like names, titles, or statuses. If you only check for the new name, a bug could cause both the old and new names to appear simultaneously, which would be a confusing user experience. The `.not.toBeVisible()` assertion is your safeguard against such issues.",
      "dryRun": "🔁 **Think:**\n1.  **Initial State:** Page shows \"New Test Item\".\n2.  **Action 1:** Click \"New Test Item\", then \"Edit\" button.\n    *   **Transition 1:** UI navigates to an edit form, pre-filled with \"New Test Item\".\n3.  **Action 2:** Fill 'Item Name' with \"Updated Test Item\", then click \"Save\".\n    *   **Transition 2:** Form submits. UI navigates back to the list. The application's internal state for the item is now \"Updated Test Item\".\n4.  **Action 3:** `await expect(page.getByText('Updated Test Item')).toBeVisible();`\n    *   **Result 1:** Playwright finds \"Updated Test Item\" on the list page. Assertion passes.\n5.  **Action 4:** `await expect(page.getByText('New Test Item')).not.toBeVisible();`\n    *   **Result 2:** Playwright attempts to find \"New Test Item\". Since the item was updated, the old text is no longer rendered. Assertion passes.\n(Hint: The UI's visible content directly reflects the underlying data state, and both must be verified.)",
      "build": "**Learning focus:** Script the editing of an existing item and verify the update by asserting both the new and old values."
    }
  },
  {
    "id": "step5",
    "type": "question",
    "phase": "Step 5 of 5",
    "paal": "Finally, let's complete the CRUD flow by scripting the 'Delete' operation. This involves locating an item, triggering its deletion, handling any confirmation dialogs, and then asserting that the item is no longer present in the UI.",
    "hint": "You'll need to locate the item, click a 'Delete' button, potentially handle a browser dialog, and assert the item's absence.",
    "example_code": "test('should delete an existing item', async ({ page }) => {\n  await page.goto('/items');\n  // Assuming 'Updated Test Item' exists from a previous setup or test\n  page.on('dialog', async dialog => { // Listen for dialogs\n    expect(dialog.message()).toContain('Are you sure you want to delete');\n    await dialog.accept(); // Accept the confirmation dialog\n  });\n  await page.getByText('Updated Test Item').locator('..').getByRole('button', { name: 'Delete' }).click();\n  await expect(page.getByText('Updated Test Item')).not.toBeVisible();\n  await expect(page.getByText('No items found')).toBeVisible(); // Optional: Verify empty state\n});",
    "think_prompt": "Which sequence of actions correctly simulates deleting an item, handles a confirmation, and verifies its removal?",
    "mc_options": [
      "await page.click('Delete Item'); await page.acceptDialog(); await expect(page.text('Item')).not.toBeVisible();",
      "page.on('dialog', async dialog => { await dialog.accept(); }); await page.getByRole('button', { name: 'Delete' }).click(); await expect(page.getByText('Item Name')).not.toBeVisible();",
      "await page.getByText('Item to Delete').locator('..').getByRole('button', { name: 'Delete' }).click(); page.on('dialog', async dialog => { expect(dialog.message()).toContain('Are you sure'); await dialog.accept(); }); await expect(page.getByText('Item to Delete')).not.toBeVisible();"
    ],
    "mc_correct_option": "page.on('dialog', async dialog => { await dialog.accept(); }); await page.getByText('Item to Delete').locator('..').getByRole('button', { name: 'Delete' }).click(); await expect(page.getByText('Item to Delete')).not.toBeVisible();",
    "mc_anchor": "page.on('dialog')",
    "why_this_matters": "Deleting data often involves confirmation steps to prevent accidental loss. Automating the handling of these dialogs is crucial for robust delete tests, alongside verifying the item's complete removal.",
    "answer_keywords": [
      "page.on",
      "dialog",
      "accept",
      "getByText",
      "locator",
      "getByRole",
      "click",
      "expect",
      "not.toBeVisible"
    ],
    "seed_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n\n  test('should edit an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assuming 'New Test Item' was created in a previous setup or test\n    await page.getByText('New Test Item').click(); // Or locate an 'Edit' button next to it\n    await page.getByRole('button', { name: 'Edit' }).click();\n    await page.getByLabel('Item Name').fill('Updated Test Item');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('Updated Test Item')).toBeVisible();\n    await expect(page.getByText('New Test Item')).not.toBeVisible(); // Verify old text is gone\n  });\n});",
    "starter_code": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n\n  test('should edit an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assuming 'New Test Item' was created in a previous setup or test\n    await page.getByText('New Test Item').click(); // Or locate an 'Edit' button next to it\n    await page.getByRole('button', { name: 'Edit' }).click();\n    await page.getByLabel('Item Name').fill('Updated Test Item');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('Updated Test Item')).toBeVisible();\n    await expect(page.getByText('New Test Item')).not.toBeVisible(); // Verify old text is gone\n  });\n\n  test('should delete an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assume 'Updated Test Item' exists from a previous step or setup.\n    // Add steps here to:\n    // 1. Set up a dialog listener to accept the confirmation dialog.\n    // 2. Locate the 'Delete' button associated with 'Updated Test Item' and click it.\n    //    (Hint: You might need to chain locators, e.g., page.getByText('...').locator('..').getByRole('button', { name: 'Delete' }))\n    // 3. Assert that 'Updated Test Item' is no longer visible.\n    // 4. (Optional) Assert that a 'No items found' message is visible if the list becomes empty.\n  });\n});",
    "feedback_correct": "Fantastic! You've successfully implemented the delete flow, including the crucial step of handling the confirmation dialog and verifying the item's complete removal from the UI.",
    "feedback_partial": "You've got the deletion logic, but you missed handling the confirmation dialog. Without accepting it, the item won't actually be deleted, and your test might fail or hang.",
    "feedback_wrong": "This option either misses the dialog handling or uses less robust selectors. Remember that delete operations often trigger confirmation dialogs that need to be explicitly handled by your test.",
    "expected": "import { test, expect } from '@playwright/test';\n\ntest.describe('Item Management CRUD', () => {\n  test('should create a new item', async ({ page }) => {\n    await page.goto('/items');\n    await page.getByRole('button', { name: 'Add New Item' }).click();\n    await page.getByLabel('Item Name').fill('New Test Item');\n    await page.getByLabel('Description').fill('This is a description for the new item.');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('New Test Item')).toBeVisible();\n  });\n\n  test('should edit an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assuming 'New Test Item' was created in a previous setup or test\n    await page.getByText('New Test Item').click(); // Or locate an 'Edit' button next to it\n    await page.getByRole('button', { name: 'Edit' }).click();\n    await page.getByLabel('Item Name').fill('Updated Test Item');\n    await page.getByRole('button', { name: 'Save' }).click();\n    await expect(page.getByText('Updated Test Item')).toBeVisible();\n    await expect(page.getByText('New Test Item')).not.toBeVisible(); // Verify old text is gone\n  });\n\n  test('should delete an existing item', async ({ page }) => {\n    await page.goto('/items');\n    // Assuming 'Updated Test Item' exists from a previous setup or test\n    page.on('dialog', async dialog => { // Listen for dialogs\n      expect(dialog.message()).toContain('Are you sure you want to delete');\n      await dialog.accept(); // Accept the confirmation dialog\n    });\n    await page.getByText('Updated Test Item').locator('..').getByRole('button', { name: 'Delete' }).click();\n    await expect(page.getByText('Updated Test Item')).not.toBeVisible();\n    await expect(page.getByText('No items found')).toBeVisible(); // Optional: Verify empty state\n  });\n});",
    "analog_example": "// Analogous test for removing an item from a shopping cart\nimport { test, expect } from '@playwright/test';\n\ntest.describe('Shopping Cart Management', () => {\n  test('should remove an item from the cart', async ({ page }) => {\n    await page.goto('/cart');\n    // Assume 'Product X' is already in the cart\n    await page.getByLabel('Remove item: Product X').click(); // Click remove button\n    // No dialog handling needed if the app doesn't show one for cart removal\n    await expect(page.getByText('Product X')).not.toBeVisible();\n    await expect(page.getByText('Your cart is empty')).toBeVisible(); // Verify cart empty message\n  });\n});",
    "deepDiveLabel": "How do UI tests handle browser dialogs and why is it important?",
    "deepDive": {
      "hook": "Imagine you're trying to automate a task on your computer, but suddenly a pop-up window appears asking for confirmation. If your automation script isn't programmed to handle that pop-up, it will just sit there, stuck, waiting for a human to click \"OK\" or \"Cancel.\" Your script will eventually time out and fail, even though the underlying application might be working perfectly. This is a common scenario in UI testing, especially with delete operations or form submissions that trigger native browser confirmation dialogs (like `alert()`, `confirm()`, or `prompt()`). If your test doesn't explicitly tell the browser what to do with these dialogs, it will halt, leading to flaky tests and frustrating debugging sessions. Ignoring dialogs means your tests can't complete critical user flows, leaving significant parts of your application untested.",
      "pain": "⚠️ **Lesson:** Unhandled browser dialogs (confirmations, alerts) will halt test execution and cause failures. Symptom: Tests hang indefinitely or fail with timeout errors when a dialog is expected but not interacted with.",
      "mentalModel": "**Mental model:** The \"Dialog Interceptor.\" Think of your test script as having a special \"interceptor\" that can listen for and respond to browser dialogs. When a dialog pops up, this interceptor catches it *before* it blocks the main test flow. It then allows your script to programmatically interact with the dialog – reading its message, accepting it, or dismissing it – just as a human user would. This ensures that the test can continue its execution without being stalled by unexpected pop-ups, making the test robust and reliable even when dialogs are part of the user journey.",
      "discover": "**Pattern - Handling Browser Dialogs:**\n```typescript\ntest('should handle a confirmation dialog', async ({ page }) => {\n  // 1. Set up a listener for dialog events *before* the action that triggers it\n  page.on('dialog', async dialog => {\n    console.log(`Dialog message: ${dialog.message()}`);\n    expect(dialog.type()).toBe('confirm'); // Assert dialog type\n    expect(dialog.message()).toContain('Are you sure?'); // Assert dialog message\n    await dialog.accept(); // 2. Programmatically accept the dialog\n    // await dialog.dismiss(); // Or dismiss it\n  });\n\n  // 3. Perform the action that triggers the dialog\n  await page.getByRole('button', { name: 'Delete Item' }).click();\n\n  // 4. Continue with assertions after the dialog is handled\n  await expect(page.getByText('Item deleted')).toBeVisible();\n});\n```\n-   **1. `page.on('dialog', ...)`:** This sets up an event listener that will be triggered whenever a browser dialog (alert, confirm, prompt) appears. It's crucial to set this up *before* the action that causes the dialog.\n-   **2. `dialog.accept()` / `dialog.dismiss()`:** Inside the listener, you can interact with the `dialog` object. `accept()` simulates clicking \"OK\" or \"Yes\", while `dismiss()` simulates clicking \"Cancel\" or \"No\".\n-   **3. Triggering action:** After setting up the listener, perform the action (e.g., clicking a 'Delete' button) that is expected to open the dialog.\n-   **4. Assertions:** Once the dialog is handled, the test can proceed with verifying the outcome of the action.",
      "quickRules": "**Quick rules:**\n-   ✅ Always set up your `page.on('dialog', ...)` listener *before* the action that triggers the dialog.\n-   ✅ Use `await dialog.accept()` to confirm actions (e.g., deletions).\n-   ✅ Use `await dialog.dismiss()` to cancel actions or close informational alerts.\n-   ✅ Assert the dialog's message (`dialog.message()`) to ensure the correct dialog appeared.\n-   ❌ Never trigger an action that opens a dialog without an active listener; the test will hang.\n-   ❌ Do not forget to `await` the `dialog.accept()` or `dialog.dismiss()` calls.\n-   ❌ Avoid using hardcoded `setTimeout` to wait for dialogs; the event listener is much more reliable.",
      "watchOut": "👀 **Watch out:** The `page.on('dialog', ...)` listener needs to be set up *before* the action that causes the dialog to appear. If you click the button first and then try to set up the listener, the dialog might have already appeared and blocked the test before your listener is active. Also, remember that `dialog.accept()` and `dialog.dismiss()` are asynchronous operations and require `await`.",
      "dryRun": "🔁 **Think:**\n1.  **Initial State:** Browser is on '/items' page, showing \"Updated Test Item\".\n2.  **Action 1:** `page.on('dialog', async dialog => { await dialog.accept(); });` is set up.\n    *   **Transition 1:** Playwright's internal event listener is now active, waiting for any browser dialogs.\n3.  **Action 2:** `await page.getByText('Updated Test Item').locator('..').getByRole('button', { name: 'Delete' }).click();`\n    *   **Transition 2:** The 'Delete' button is clicked. The application triggers a browser confirmation dialog (e.g., `confirm('Are you sure?')`).\n    *   **Transition 3:** Playwright's dialog listener catches the dialog. The `dialog.accept()` call is executed, programmatically clicking \"OK\" on the dialog. The dialog closes.\n    *   **Transition 4:** The application processes the deletion. The UI updates, removing \"Updated Test Item\" from the list.\n4.  **Action 3:** `await expect(page.getByText('Updated Test Item')).not.toBeVisible();`\n    *   **Result 1:** Playwright verifies that \"Updated Test Item\" is no longer rendered on the page. Assertion passes.\n5.  **Action 4:** `await expect(page.getByText('No items found')).toBeVisible();`\n    *   **Result 2:** Playwright verifies that the \"No items found\" message is now visible. Assertion passes.\n(Hint: The dialog listener acts as a crucial intermediary, allowing the test to continue its flow after an interactive pop-up.)",
      "build": "**Learning focus:** Script the deletion of an item, including handling confirmation dialogs, and verify its removal from the UI."
    }
  }
];

const sideItems = [
  { label: "Lesson", id: "intro" },
  { label: "Objectives", id: "objectives" },
  { label: "Step 1: Setup", id: "step1" },
  { label: "Step 2: Navigate", id: "step2" },
  { label: "Step 3: Create", id: "step3" },
  { label: "Step 4: Edit", id: "step4" },
  { label: "Step 5: Delete", id: "step5" },
];

export default createINPACTEngine({
  NODES,
  sideItems,
  lessonNum: 0,
  title: "Automating End-to-End UI Tests for CRUD Flows",
  shortName: "UI CRUD Tests",
});
