import createINPACTEngine from "../inpact_engine_shared";

export const NODES = [
  {
    id: "intro",
    type: "reveal",
    phase: "Lesson",
    content: {
      tag: "funda-react-hooks-usestate-useeffect",
      title: "Managing Component State and Side Effects",
      body: `User interfaces are rarely static; they need to remember information (like a number, whether a toggle is on or off, or text typed into an input field) and react dynamically to changes. When this internal "memory" or "state" changes, the UI must update to reflect the new reality. Historically, managing this reactivity could be complex, often requiring class components with intricate lifecycle methods. React Hooks, specifically \`useState\` and \`useEffect\`, provide a simpler, more direct way to imbue functional components with this essential interactivity, allowing them to be dynamic and responsive without the boilerplate of class components.

This pattern is fundamental to nearly all interactive user interfaces you'll build. You'll encounter \`useState\` for managing everything from form input values and the visibility of modals to tracking the active item in a list or storing data fetched from an API. \`useEffect\` is equally crucial for handling "side effects" – operations that interact with the outside world or need to run in response to state or prop changes. This includes tasks like fetching data when a component loads, setting up event listeners, performing animations, or updating browser APIs (like the document title).`,
      usecase: "A settings panel where a user can toggle various options on or off, and the application needs to save these preferences or react to their changes.",
      designMock: {"kind":"list-and-form","screenTitle":"Interaction","caption":"Observe the displayed value and interact with it.","listCaption":"Current Value","emptyCaption":"No Value","emptyMessage":"No interactive value to display.","rows":[{"title":"Value","subtitle":"0","meta":"Current"}],"fields":[{"label":"Action","options":["Increment","Decrement"]}],"submitLabel":"Apply","formMode":"filter"}
    },
  },
  {
    id: "objectives",
    type: "objectives",
    phase: "Objectives",
    items: [
      "Import `useState` and `useEffect` hooks.",
      "Define a functional component to house state and effects.",
      "Manage component-specific state using `useState`.",
      "Construct JSX to display state and provide interaction points.",
      "Implement event handler functions to update state.",
      "Wire event handlers to UI elements for interactivity.",
      "Perform side effects using `useEffect` in response to state changes.",
    ],
  },
  {
    id: "step1",
    type: "question",
    phase: "Step 1 of 7",
    paal: "To use React's built-in state and effect management features, you first need to import the `useState` and `useEffect` hooks from the `react` library.",
    hint: "Remember that hooks are named exports from the 'react' package.",
    example_code: `import { useState, useEffect } from 'react';`,
    think_prompt: "What is the correct way to import the `useState` and `useEffect` hooks from the `react` library?",
    mc_options: [
      "import React, { useState, useEffect } from 'react';",
      "import { useState, useEffect } from 'react';",
      "import { State, Effect } from 'react';",
    ],
    mc_correct_option: "import { useState, useEffect } from 'react';",
    mc_anchor: "import-statement",
    why_this_matters: "Correctly importing hooks is the first step to enabling state and side effect management in your functional components, allowing them to become interactive and dynamic.",
    answer_keywords: ["import", "useState", "useEffect", "react"],
    seed_code: ``,
    starter_code: `// Add your React hook imports here`,
    feedback_correct: "Excellent! You've correctly imported the necessary hooks. `useState` and `useEffect` are named exports from the `react` package.",
    feedback_partial: "You're close, but be careful with the default import of `React`. While `React` used to be required in scope for JSX, it's often not explicitly needed for functional components with modern React versions, and `useState`/`useEffect` are named exports.",
    feedback_wrong: "Remember that `useState` and `useEffect` are specific named functions (hooks) provided by React, not generic `State` or `Effect` objects. They need to be imported by their exact names.",
    expected: `import { useState, useEffect } from 'react';`,
    analog_example: `import { readFileSync } from 'fs';\nimport { join } from 'path';\n\nconst filePath = join(__dirname, 'data.txt');\nconst fileContent = readFileSync(filePath, 'utf8');\nconsole.log(fileContent);`,
    deepDiveLabel: "Why do we import hooks this way?",
    deepDive: {
      hook: `Imagine you're building a simple web page. You want a button that, when clicked, changes the text displayed on the screen. Or perhaps you have a list of items, and when you click one, it should highlight. In a traditional HTML/JavaScript setup, you'd find the element by its ID, attach an event listener, and manually update its \`textContent\` or \`className\`. This works for small, static pages. But what if your UI is composed of many small, reusable pieces, each needing its own internal memory and reactions? Manually managing all those DOM updates and state changes becomes a tangled mess very quickly. You'd spend more time orchestrating updates than building features, leading to bugs and unmaintainable code.`,
      pain: `⚠️ **Lesson:** Without a structured way to manage component-specific data that changes over time (state) and actions that occur outside the normal rendering flow (side effects), UI development becomes brittle and complex. Symptom: Components don't update correctly, data inconsistencies, or difficult-to-trace bugs related to UI interactions.`,
      mentalModel: `**Mental model:** "Component's Utility Belt." Think of a functional component as a skilled craftsperson. By default, they can only *receive* tools (props) and *build* things (return JSX). But sometimes, they need to *remember* something for themselves (like how many times a button was clicked) or *do* something special when their environment changes (like fetching new materials when a project starts). Hooks are like adding specialized tools to their utility belt – \`useState\` for memory, \`useEffect\` for special actions – empowering them to be more dynamic and self-sufficient without becoming a "class" (a whole workshop).`,
      discover: `**Pattern - Named Imports:**\n\`\`\`tsx\nimport { namedExport1, namedExport2 } from 'module-name';\n\`\`\`\n-   This syntax is used when a module exports multiple specific values, functions, or objects using the \`export\` keyword without \`default\`.\n-   \`useState\` and \`useEffect\` are functions that React provides for specific purposes within functional components.\n-   Using curly braces \`{}\` means you are destructuring and importing specific named exports, not the entire module.\n-   This keeps your bundle size smaller by only importing what you need, rather than the entire \`React\` object.`,
      quickRules: `**Quick rules:**\n-   ✅ \`import { useState, useEffect } from 'react';\` for specific hooks.\n-   ✅ Use named imports for functions or values exported without \`default\`.\n-   ✅ Place imports at the top of the file for clarity.\n-   ✅ Only import what you actually use to optimize performance.\n-   ❌ \`import React from 'react';\` if you only need hooks and not \`React\` global (though often harmless).\n-   ❌ \`import { State, Effect } from 'react';\` (incorrect names).\n-   ❌ Importing hooks from a path other than \`'react'\`.`,
      watchOut: `👀 **Watch out:** While \`import React from 'react';\` is often included by default in many setups, it's technically not strictly necessary for functional components that only use hooks and return JSX, thanks to modern JSX transform. However, \`useState\` and \`useEffect\` *must* be explicitly imported by name. Forgetting to import them will result in runtime errors like "\`useState\` is not defined."`,
      dryRun: `🔁 **Think:** A JavaScript engine encounters \`import { useState, useEffect } from 'react';\`. It first locates the \`react\` package. Then, it looks inside that package's exports for specific named exports called \`useState\` and \`useEffect\`. If found, it makes these functions available in the current file's scope. If not found, or if the names don't match, an import error occurs. (Hint: The engine needs exact names to find the right tools.)`,
      build: `**Learning focus:** Understand how to import specific functions (hooks) from a library for use in your component.`,
    },
  },
  {
    id: "step2",
    type: "question",
    phase: "Step 2 of 7",
    paal: "Next, define a basic functional component. This component will encapsulate our state and logic.",
    hint: "A functional component is a JavaScript function that returns JSX. Remember to capitalize its name.",
    example_code: `function Counter() {\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    think_prompt: "Create a functional component named `Counter` that returns a simple `div` element.",
    mc_options: [
      `const Counter = () => {\n  return <div></div>;\n};`,
      `function Counter() {\n  return <div></div>;\n}`,
      `class Counter extends React.Component {\n  render() {\n    return <div></div>;\n  }\n}`,
    ],
    mc_correct_option: `function Counter() {\n  return <div></div>;\n}`,
    mc_anchor: "component-definition",
    why_this_matters: "Functional components are the building blocks of modern React applications, providing a clear and concise way to define UI pieces.",
    answer_keywords: ["function", "component", "return", "JSX"],
    seed_code: `import { useState, useEffect } from 'react';`,
    starter_code: `import { useState, useEffect } from 'react';\n\n// Define your functional component here`,
    feedback_correct: "Correct! Defining a functional component is the standard way to create reusable UI elements in React.",
    feedback_partial: "You've created a component, but remember that modern React heavily favors functional components over class components, especially when using hooks.",
    feedback_wrong: "While class components can also render JSX, the goal here is to use a functional component to prepare for integrating hooks like `useState` and `useEffect`.",
    expected: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    analog_example: `function GreetUser(props) {\n  return (\n    <p>Hello, {props.name || 'Guest'}!</p>\n  );\n}\n\n// Usage:\n// <GreetUser name="Alice" />`,
    deepDiveLabel: "Why use functional components over classes?",
    deepDive: {
      hook: `Imagine you're trying to build a complex machine, like a robot. In the past, you might have had to define a detailed blueprint (a "class") for every single part, even for simple things like a bolt or a gear. These blueprints came with a lot of boilerplate – constructors, \`this\` bindings, lifecycle methods – even if the part just needed to exist and do one simple thing. It felt like overkill for basic components, making the code harder to read, write, and understand. You just wanted a simple function that takes some inputs and gives you an output, but the system forced you into a more rigid, object-oriented structure.`,
      pain: `⚠️ **Lesson:** Over-reliance on class components for simple UI elements introduces unnecessary complexity and boilerplate, making code harder to read, test, and refactor. Symptom: Large, verbose components, confusion with \`this\` context, and difficulty sharing logic between components.`,
      mentalModel: `**Mental model:** "Pure Function UI." Think of a functional component as a mathematical function: it takes inputs (props), performs some calculations, and returns an output (JSX). It's predictable, easy to test, and doesn't have hidden side effects unless you explicitly add them. Class components, on the other hand, are like objects with internal state and methods, which can be powerful but also harder to reason about due to their mutable nature and complex lifecycle. Hooks allow functional components to gain the "superpowers" of state and effects without losing their functional purity and simplicity.`,
      discover: `**Pattern - Functional Component Definition:**\n\`\`\`tsx\nfunction MyComponent(props) {\n  // Component logic here\n  return (\n    <div>\n      {/* JSX output */}\n    </div>\n  );\n}\n\n// Or using arrow function syntax:\nconst MyComponent = (props) => {\n  // Component logic here\n  return (\n    <div>\n      {/* JSX output */}\n    </div>\n  );\n};\n\`\`\`\n-   Functional components are JavaScript functions that accept a single \`props\` object as an argument.\n-   They must return valid JSX, which describes the UI to be rendered.\n-   They are simpler to write and read than class components, especially with the introduction of hooks.\n-   The name of the component (e.g., \`Counter\`) must start with an uppercase letter to distinguish it from regular HTML elements.`,
      quickRules: `**Quick rules:**\n-   ✅ Start component names with an uppercase letter.\n-   ✅ Return JSX from the component function.\n-   ✅ Accept \`props\` as the first argument (optional if no props are used).\n-   ✅ Use functional components for most UI elements in modern React.\n-   ❌ Name components with lowercase letters (React will treat them as HTML).\n-   ❌ Return anything other than valid JSX (e.g., a string or number directly, unless it's a primitive component).\n-   ❌ Forget to \`export\` the component if it's meant to be used elsewhere.`,
      watchOut: `👀 **Watch out:** While both \`function MyComponent() {}\` and \`const MyComponent = () => {}\` are valid ways to define functional components, be consistent within your codebase. Also, remember that functional components *must* return JSX. If you forget the \`return\` statement or return \`undefined\`, nothing will render, and you might see an error about a component returning \`null\` or \`undefined\`.`,
      dryRun: `🔁 **Think:** When React renders \`<Counter />\`, it calls the \`Counter\` function. The function executes, and it encounters \`return (<div>...</div>);\`. React then takes the JSX returned by the function and converts it into actual DOM elements to display on the screen. If the function returned nothing, React would render an empty space. (Hint: The function's return value directly dictates what appears in the UI.)`,
      build: `**Learning focus:** Define a basic functional component that serves as the container for our interactive UI.`,
    },
  },
  {
    id: "step3",
    type: "question",
    phase: "Step 3 of 7",
    paal: "Now, let's give our `Counter` component some internal memory using the `useState` hook. This will allow it to track a numeric value that can change over time.",
    hint: "The `useState` hook returns an array with the current state value and a function to update it. Use array destructuring.",
    example_code: `function Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    think_prompt: "Inside the `Counter` component, declare a state variable named `count` initialized to `0` using `useState`. Also, declare its setter function `setCount`.",
    mc_options: [
      `const count = 0;`,
      `let [count, setCount] = useState(0);`,
      `const [count, setCount] = useState(0);`,
    ],
    mc_correct_option: `const [count, setCount] = useState(0);`,
    mc_anchor: "usestate-declaration",
    why_this_matters: "`useState` is the primary hook for adding reactive, mutable state to functional components, making them dynamic and responsive to user interactions.",
    answer_keywords: ["useState", "state", "count", "setCount", "initial value"],
    seed_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    starter_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  // Declare your state variable here\n\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    feedback_correct: "Exactly! `const [count, setCount] = useState(0);` correctly initializes your state variable and its setter. This is the core of making your component interactive.",
    feedback_partial: "You've got the right idea with `useState`, but remember that the array destructuring assignment should use `const` for both the state variable and the setter function, as their references don't change.",
    feedback_wrong: "Simply declaring `const count = 0;` creates a regular variable, not a state variable. Changes to `count` in this way won't trigger a re-render of your component, which is essential for dynamic UIs.",
    expected: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    analog_example: `// In a plain JavaScript module:\nlet currentTheme = 'light';\n\nfunction setTheme(newTheme) {\n  currentTheme = newTheme;\n  document.body.className = newTheme;\n  console.log(\`Theme changed to: \${currentTheme}\`);\n}\n\n// Usage:\n// setTheme('dark');`,
    deepDiveLabel: "How does `useState` make state 'reactive'?",
    deepDive: {
      hook: `Imagine you have a simple display board that shows a number. You want to change that number, and have the display board automatically update. If you just had a regular JavaScript variable, say \`let myNumber = 0;\`, and you did \`myNumber = 5;\`, the display board wouldn't know to update itself. You'd have to manually tell it: \`updateDisplayBoard(myNumber);\`. This manual coordination becomes incredibly tedious and error-prone when you have many pieces of data that need to be reflected in different parts of your UI. You'd constantly be asking, "Did I remember to update *that* part of the screen after *this* data changed?"`,
      pain: `⚠️ **Lesson:** Without a mechanism to automatically re-render components when their underlying data changes, developers must manually manage DOM updates, leading to inconsistent UIs and complex, error-prone code. Symptom: UI elements not reflecting the latest data, or excessive manual DOM manipulation.`,
      mentalModel: `**Mental model:** "The State Dispatcher." Think of \`useState\` as providing you with two things: a "current value" (like \`count\`) and a "dispatcher" (like \`setCount\`). When you call the dispatcher with a new value, it doesn't just update the variable; it also tells React, "Hey, something important changed in this component! You need to re-run its function and see if the UI needs to be updated." React then efficiently compares the new UI output with the old and updates only what's necessary in the actual browser DOM.`,
      discover: `**Pattern - \`useState\` Hook:**\n\`\`\`tsx\nconst [stateVariable, setStateVariable] = useState(initialValue);\n\`\`\`\n-   \`useState\` is a function that takes one argument: the \`initialValue\` for your state.\n-   It returns an array with exactly two elements: the current \`stateVariable\` and a \`setStateVariable\` function to update it.\n-   The \`stateVariable\` holds the current value of the state.\n-   The \`setStateVariable\` function is used to update the state. When called, it triggers a re-render of the component.\n-   The \`initialValue\` is only used during the *first* render of the component. Subsequent renders will use the latest state value.`,
      quickRules: `**Quick rules:**\n-   ✅ Call \`useState\` at the top level of your functional component (not inside loops, conditions, or nested functions).\n-   ✅ Use the setter function (\`setCount\`) to update state; direct modification (\`count = 5\`) will not trigger re-renders.\n-   ✅ The initial value can be any valid JavaScript data type (number, string, object, array, boolean).\n-   ✅ Use descriptive names for your state variables and their setters (e.g., \`[isOpen, setIsOpen]\`).\n-   ❌ Call \`useState\` inside a callback function or conditional block.\n-   ❌ Modify the state variable directly (e.g., \`count++\`).\n-   ❌ Forget to destructure the array returned by \`useState\` into two variables.`,
      watchOut: `👀 **Watch out:** \`useState\` updates are asynchronous. If you need to perform an action immediately after state changes, or if your new state depends on the *previous* state, use the functional update form of the setter: \`setCount(prevCount => prevCount + 1);\`. This ensures you're always working with the most up-to-date state value, preventing subtle bugs.`,
      dryRun: `🔁 **Think:**\n1.  **Initial Render:** \`Counter\` function runs. \`useState(0)\` is called. \`count\` is \`0\`, \`setCount\` is the updater function.\n2.  **User Clicks Increment:** \`setCount(1)\` is called. React schedules a re-render.\n3.  **Re-render:** \`Counter\` function runs again. \`useState(0)\` is called *again*, but React "remembers" the last value for this state variable was \`1\`, so \`count\` is now \`1\`. The UI updates to show \`1\`.\n(Hint: \`useState\` doesn't re-initialize on every render; it retrieves the *current* state.)`,
      build: `**Learning focus:** Implement \`useState\` to introduce a dynamic, reactive state variable into a functional component.`,
    },
  },
  {
    id: "step4",
    type: "question",
    phase: "Step 4 of 7",
    paal: "Let's add the basic HTML structure to display our `count` and provide buttons for interaction.",
    hint: "Embed JavaScript expressions in JSX using curly braces `{}`. Remember that JSX must return a single root element.",
    example_code: `function Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    think_prompt: "Inside the `div`, display the `count` state variable within an `h1` tag, and add two `button` elements with labels 'Increment' and 'Decrement'.",
    mc_options: [
      `<div>\n  <p>Count: {count}</p>\n  <button>Add</button>\n</div>`,
      `<div>\n  <h1>Counter: {count}</h1>\n  <button>Increment</button>\n  <button>Decrement</button>\n</div>`,
      `<h1>Counter: {count}</h1>\n<button>Increment</button>\n<button>Decrement</button>`,
    ],
    mc_correct_option: `<div>\n  <h1>Counter: {count}</h1>\n  <button>Increment</button>\n  <button>Decrement</button>\n</div>`,
    mc_anchor: "jsx-structure",
    why_this_matters: "The JSX structure defines the visual layout and content of your component, making the state visible and providing interactive elements.",
    answer_keywords: ["h1", "button", "JSX", "curly braces"],
    seed_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      {/* Our counter UI will go here */}\n    </div>\n  );\n}`,
    starter_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      {/* Add your UI elements here */}\n    </div>\n  );\n}`,
    feedback_correct: "Perfect! You've laid out the visual elements, including displaying the `count` and providing buttons for interaction. The curly braces `{count}` correctly embed the state variable.",
    feedback_partial: "You've got the elements, but ensure they are all wrapped within a single parent element (like a `div`) as required by JSX when returning multiple top-level elements.",
    feedback_wrong: "Remember that in JSX, you need to wrap multiple adjacent elements within a single parent element (like a `div` or a `Fragment`) to return them. Also, ensure the labels match the prompt.",
    expected: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    analog_example: `// In plain HTML:\n<section>\n  <h2>Product List</h2>\n  <ul>\n    <li>Item A</li>\n    <li>Item B</li>\n  </ul>\n  <button>Add New Product</button>\n</section>`,
    deepDiveLabel: "Why must JSX return a single root element?",
    deepDive: {
      hook: `Imagine you're giving instructions to a robot to build a house. If you tell the robot, "Build a wall, then build a roof, then build a door," it might get confused about how these pieces relate. Does the door go *on* the wall, or is it a separate structure? JSX has a similar rule: when a component returns its UI, it needs to return a single, coherent "tree" of elements. If you try to return two separate, unconnected elements at the top level, React doesn't know how to represent them as a single, cohesive unit in the virtual DOM, which is its internal representation of your UI.`,
      pain: `⚠️ **Lesson:** Returning multiple top-level elements from a component without a common parent causes JSX compilation errors and breaks React's ability to efficiently manage the UI tree. Symptom: "Adjacent JSX elements must be wrapped in an enclosing tag" error.`,
      mentalModel: `**Mental model:** "The Single Root Tree." Think of the JSX returned by a component as a single tree structure. Just like a real tree has one trunk from which all branches and leaves grow, a JSX component must have one root element from which all other elements descend. This single root provides a clear anchor for React's reconciliation algorithm, allowing it to efficiently track changes and update the actual browser DOM. If you need to return multiple siblings without an extra \`div\`, you can use a \`Fragment\` (\`<></>\`).`,
      discover: `**Pattern - Single Root Element:**\n\`\`\`tsx\nfunction MyComponent() {\n  return (\n    <div> {/* This is the single root element */}\n      <h1>Title</h1>\n      <p>Content</p>\n      <button>Click Me</button>\n    </div>\n  );\n}\n\n// Or using a React Fragment:\nfunction MyOtherComponent() {\n  return (\n    <> {/* This is a shorthand for <React.Fragment> */}\n      <h1>Another Title</h1>\n      <p>More Content</p>\n    </>\n  );\n}\n\`\`\`\n-   Every functional component must return a single JSX element as its top-level parent.\n-   If you need to return multiple elements without adding an extra DOM node, use \`<React.Fragment>\` or its shorthand \`<...>\`.\n-   This rule ensures that React can efficiently manage and update the component's output in the virtual DOM.\n-   It helps maintain a clear hierarchical structure for your UI.`,
      quickRules: `**Quick rules:**\n-   ✅ Wrap multiple sibling elements in a \`div\`, \`section\`, or other semantic HTML tag.\n-   ✅ Use \`<></>\` (shorthand Fragment) when you don't want an extra DOM node.\n-   ✅ Ensure the returned JSX is syntactically valid.\n-   ✅ Use curly braces \`{}\` to embed JavaScript expressions (like \`count\`) within JSX.\n-   ❌ Return two or more elements directly without a parent wrapper.\n-   ❌ Forget to close tags (e.g., \`<button>\` instead of \`<button></button>\`).\n-   ❌ Use \`class\` instead of \`className\` for CSS classes in JSX.`,
      watchOut: `👀 **Watch out:** While \`<></>\` (Fragment shorthand) is convenient, it doesn't accept \`key\` props, which can be important when rendering lists of elements. If you need to pass a \`key\` to a Fragment, you must use the explicit \`<React.Fragment key={...}>\` syntax. Also, remember that all HTML attributes in JSX are camelCase (e.g., \`onClick\`, \`className\`).`,
      dryRun: `🔁 **Think:** React receives the JSX \`<div><h1>Counter: {count}</h1><button>Increment</button><button>Decrement</button></div>\`. It sees a single \`div\` as the root. Inside, it finds an \`h1\` and two \`button\` elements. It then constructs a virtual DOM tree representing this structure. If the \`div\` were missing, React would see three separate top-level elements (\`h1\`, \`button\`, \`button\`) and throw an error because it expects a single root. (Hint: React needs a single entry point to build its internal UI representation.)`,
      build: `**Learning focus:** Construct the basic visual layout of the component, displaying state and providing interaction points.`,
    },
  },
  {
    id: "step5",
    type: "question",
    phase: "Step 5 of 7",
    paal: "Now, let's define the functions that will update our `count` state when the buttons are clicked. These are called event handlers.",
    hint: "Use the functional update form of `setCount` to ensure you're always working with the latest state.",
    example_code: `function Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    think_prompt: "Inside the `Counter` component, define two arrow functions: `increment` that increases `count` by 1, and `decrement` that decreases `count` by 1. Use the functional update form of `setCount`.",
    mc_options: [
      `function increment() { count++; }\nfunction decrement() { count--; }`,
      `const increment = () => setCount(count + 1);\nconst decrement = () => setCount(count - 1);`,
      `const increment = () => setCount(prevCount => prevCount + 1);\nconst decrement = () => setCount(prevCount => prevCount - 1);`,
    ],
    mc_correct_option: `const increment = () => setCount(prevCount => prevCount + 1);\nconst decrement = () => setCount(prevCount => prevCount - 1);`,
    mc_anchor: "event-handlers",
    why_this_matters: "Event handlers are the bridge between user actions and state changes, making your components interactive and responsive.",
    answer_keywords: ["event handler", "arrow function", "setCount", "functional update"],
    seed_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    starter_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  // Define your event handlers here\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    feedback_correct: "Excellent! Using the functional update form (`prevCount => prevCount + 1`) is the safest and most reliable way to update state when the new state depends on the previous state.",
    feedback_partial: "You've defined the handlers, but directly using `setCount(count + 1)` can lead to stale state issues if multiple updates happen quickly. The functional update form is generally preferred.",
    feedback_wrong: "Remember that directly modifying `count++` or `count--` will not trigger a re-render. You *must* use the `setCount` function to update state and ensure your UI reacts to changes.",
    expected: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    analog_example: `// In a plain JavaScript event listener:\nlet score = 0;\nconst scoreDisplay = document.getElementById('score-display');\nconst addButton = document.getElementById('add-button');\n\naddButton.addEventListener('click', () => {\n  score = score + 1;\n  scoreDisplay.textContent = \`Score: \${score}\`;\n});`,
    deepDiveLabel: "Why use `prevCount => prevCount + 1` instead of `count + 1`?",
    deepDive: {
      hook: `Imagine you're at a busy ticket counter, and multiple people are trying to buy tickets at the exact same moment. If each person just says, "Give me one more ticket than what's currently showing," without checking the *absolute latest* count, you might accidentally sell the same ticket twice or end up with an incorrect total. In React, state updates can be batched for performance. If you call \`setCount(count + 1)\` multiple times in quick succession, \`count\` might refer to an outdated value from before the previous update was processed, leading to missed updates or incorrect final state.`,
      pain: `⚠️ **Lesson:** Relying on the current state variable (\`count\`) directly within a \`setCount\` call can lead to "stale state" issues, especially when updates are batched or asynchronous. Symptom: State updates are incorrect, or UI doesn't reflect the expected value after rapid interactions.`,
      mentalModel: `**Mental model:** "The Safe Updater Function." When you pass a function to \`setCount\` (e.g., \`setCount(prevCount => prevCount + 1)\`), React guarantees that the \`prevCount\` argument you receive will *always* be the absolute latest, most up-to-date state value. It's like having a dedicated clerk who always checks the live inventory before adding a new ticket. This prevents race conditions and ensures your state updates are accurate, even when multiple updates are queued.`,
      discover: `**Pattern - Functional State Update:**\n\`\`\`tsx\nsetStateVariable(prevValue => newValueBasedOnPrevValue);\n\`\`\`\n-   When the new state depends on the previous state, pass a function to the state setter instead of a direct value.\n-   This function receives the \`prevValue\` (the current state) as its argument.\n-   The function should return the new state value.\n-   React guarantees that \`prevValue\` will be the most recent state at the time of the update, even if updates are batched.\n-   This pattern prevents stale state bugs that can occur when relying on \`stateVariable\` directly in closures.`,
      quickRules: `**Quick rules:**\n-   ✅ Use \`setCount(prev => prev + 1)\` when the new state depends on the old state.\n-   ✅ This pattern is crucial for reliable updates in asynchronous or batched scenarios.\n-   ✅ The \`prevValue\` argument is guaranteed to be the latest state.\n-   ✅ Return the new state value from the updater function.\n-   ❌ Use \`setCount(count + 1)\` if there's any chance of multiple rapid updates.\n-   ❌ Forget to return a value from the functional updater.\n-   ❌ Assume \`count\` inside an event handler is always the absolute latest value.`,
      watchOut: `👀 **Watch out:** While functional updates are generally safer for numerical or boolean state, be careful when updating objects or arrays. You must always return a *new* object or array, not mutate the \`prevValue\` directly. For example, \`setArray(prevArray => [...prevArray, newItem]);\` is correct, while \`setArray(prevArray => { prevArray.push(newItem); return prevArray; });\` is incorrect and will lead to bugs.`,
      dryRun: `🔁 **Think:**\n1.  \`count\` is \`0\`. User clicks Increment. \`setCount(prevCount => prevCount + 1)\` is called. \`prevCount\` is \`0\`. New state is \`1\`.\n2.  *Before re-render*, user clicks Increment again. \`setCount(prevCount => prevCount + 1)\` is called *again*. Because of the functional update, React ensures \`prevCount\` for this call is \`1\` (the result of the *first* update), not \`0\`. New state is \`2\`.\n3.  React re-renders with \`count\` as \`2\`.\n(Hint: The functional update ensures each update builds on the *most recent* pending state, not the state from the last render.)`,
      build: `**Learning focus:** Implement event handler functions that correctly update component state using the functional update pattern.`,
    },
  },
  {
    id: "step6",
    type: "question",
    phase: "Step 6 of 7",
    paal: "Now, connect our `increment` and `decrement` functions to the `onClick` events of their respective buttons.",
    hint: "In JSX, event attributes are camelCase, and you pass a function reference using curly braces.",
    example_code: `function Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button onClick={increment}>Increment</button>\n      <button onClick={decrement}>Decrement</button>\n    </div>\n  );\n}`,
    think_prompt: "Add `onClick` attributes to the 'Increment' and 'Decrement' buttons, wiring them to the `increment` and `decrement` functions respectively.",
    mc_options: [
      `<button onclick="increment()">Increment</button>`,
      `<button onClick={increment()}>Increment</button>`,
      `<button onClick={increment}>Increment</button>`,
    ],
    mc_correct_option: `<button onClick={increment}>Increment</button>`,
    mc_anchor: "wire-handlers",
    why_this_matters: "Wiring event handlers makes your UI interactive, allowing user actions to trigger state changes and subsequent re-renders.",
    answer_keywords: ["onClick", "event attribute", "curly braces"],
    seed_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    starter_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      {/* Wire your buttons here */}\n      <button>Increment</button>\n      <button>Decrement</button>\n    </div>\n  );\n}`,
    feedback_correct: "Spot on! By passing the function reference `{increment}` to `onClick`, you ensure the function is called only when the button is clicked, making your counter fully interactive.",
    feedback_partial: "You've got the `onClick` attribute, but remember that in JSX, event handler attributes are camelCase (`onClick`), and you should pass a *reference* to the function, not call it immediately.",
    feedback_wrong: "In JSX, event attributes are camelCase (`onClick`), and you pass a JavaScript function reference using curly braces, not a string. Calling `increment()` directly would execute it immediately on render, not on click.",
    expected: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button onClick={increment}>Increment</button>\n      <button onClick={decrement}>Decrement</button>\n    </div>\n  );\n}`,
    analog_example: `// In plain HTML/JS:\nconst myButton = document.getElementById('myButton');\nconst handleClick = () => {\n  console.log('Button clicked!');\n};\nmyButton.addEventListener('click', handleClick);`,
    deepDiveLabel: "What's the difference between `{handler}` and `{handler()}` in JSX?",
    deepDive: {
      hook: `Imagine you're setting up a doorbell. If you connect the doorbell button directly to the bell (\`{ringBell}\`), the bell rings *only* when someone presses the button. But if you accidentally connect it as \`{ringBell()}\`, it's like the bell is constantly ringing the moment you install it, without anyone ever touching the button! This is a common mistake in React: passing \`handler()\` instead of \`handler\` to an event prop. It leads to functions executing immediately on render, causing infinite loops or unexpected behavior.`,
      pain: `⚠️ **Lesson:** Incorrectly invoking an event handler function (\`{handler()}\`) instead of passing its reference (\`{handler}\`) causes the function to execute immediately during rendering, leading to infinite loops, performance issues, or unexpected side effects. Symptom: Functions running unexpectedly, "Too many re-renders" errors, or UI not responding to clicks.`,
      mentalModel: `**Mental model:** "Function Reference vs. Function Call." When you write \`{handler}\` in JSX, you are passing a *reference* to the \`handler\` function. React stores this reference and will call the function *only* when the associated event (e.g., a click) occurs. When you write \`{handler()}\`, you are *immediately calling* the \`handler\` function during the render phase, and then passing its *return value* (which is often \`undefined\` for event handlers) to the event prop. React then tries to execute \`undefined\` as an event handler, or the immediate execution causes a state update, triggering another render, and so on.`,
      discover: `**Pattern - Wiring Event Handlers:**\n\`\`\`tsx\n<button onClick={myHandlerFunction}>Click Me</button>\n\`\`\`\n-   Event attributes in JSX are camelCase (e.g., \`onClick\`, \`onChange\`, \`onSubmit\`).\n-   You pass a *reference* to a JavaScript function using curly braces \`{}\`.\n-   The function will be executed by React when the corresponding event occurs (e.g., a click).\n-   Do *not* call the function directly (e.g., \`onClick={myHandlerFunction()}\`) unless you specifically intend for it to run immediately during render and return another function.\n-   If you need to pass arguments to the handler, you can use an arrow function: \`onClick={() => myHandlerFunction(arg1, arg2)}\`.`,
      quickRules: `**Quick rules:**\n-   ✅ Use camelCase for event attributes (e.g., \`onClick\`).\n-   ✅ Pass a function reference: \`onClick={myFunction}\`.\n-   ✅ Use an arrow function to pass arguments: \`onClick={() => myFunction(arg)}\`.\n-   ✅ Ensure the function reference is defined within the component's scope.\n-   ❌ Use \`onclick\` (lowercase) for event attributes.\n-   ❌ Call the function directly: \`onClick={myFunction()}\` (unless returning another function).\n-   ❌ Pass a string like \`onClick="myFunction()"\` (this is for plain HTML, not JSX).`,
      watchOut: `👀 **Watch out:** When passing arguments using an arrow function like \`onClick={() => myFunction(arg)}\`, a *new* function is created on every render. For simple handlers, this is usually fine. However, for performance-critical components or very frequent re-renders, this can sometimes lead to unnecessary re-renders of child components if they rely on \`memo\` and the prop is a function. In such cases, \`useCallback\` can be used to memoize the handler function.`,
      dryRun: `🔁 **Think:**\n1.  React renders the \`Counter\` component. It sees \`<button onClick={increment}>\`. It stores a reference to the \`increment\` function.\n2.  User clicks the "Increment" button. React's event system catches the click.\n3.  React calls the stored \`increment\` function.\n4.  \`increment\` calls \`setCount\`, triggering a re-render.\n(Hint: The \`onClick\` attribute stores the function, it doesn't execute it immediately.)`,
      build: `**Learning focus:** Connect user interface elements to event handler functions to enable interactivity.`,
    },
  },
  {
    id: "step7",
    type: "question",
    phase: "Step 7 of 7",
    paal: "Finally, let's use the `useEffect` hook to perform a 'side effect' – logging the `count` to the console whenever it changes. This demonstrates how to react to state changes.",
    hint: "The second argument to `useEffect` is a dependency array. Include `count` to make the effect react to changes in `count`.",
    example_code: `function Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  useEffect(() => {\n    console.log(\`Count changed to: \${count}\`);\n  }, [count]);\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button onClick={increment}>Increment</button>\n      <button onClick={decrement}>Decrement</button>\n    </div>\n  );\n}`,
    think_prompt: "Add a `useEffect` hook that logs the message `Count changed to: [current count]` to the console. Ensure this effect runs only when the `count` state variable changes.",
    mc_options: [
      `useEffect(() => {\n  console.log(\`Count changed to: \${count}\`);\n});`,
      `useEffect(() => {\n  console.log(\`Count changed to: \${count}\`);\n}, []);`,
      `useEffect(() => {\n  console.log(\`Count changed to: \${count}\`);\n}, [count]);`,
    ],
    mc_correct_option: `useEffect(() => {\n  console.log(\`Count changed to: \${count}\`);\n}, [count]);`,
    mc_anchor: "useeffect-side-effect",
    why_this_matters: "`useEffect` allows you to perform actions (side effects) in response to component lifecycle events or specific data changes, integrating with external systems or performing cleanup.",
    answer_keywords: ["useEffect", "side effect", "dependency array", "console.log"],
    seed_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button onClick={increment}>Increment</button>\n      <button onClick={decrement}>Decrement</button>\n    </div>\n  );\n}`,
    starter_code: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  // Add your useEffect hook here\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button onClick={increment}>Increment</button>\n      <button onClick={decrement}>Decrement</button>\n    </div>\n  );\n}`,
    feedback_correct: "Fantastic! You've correctly used `useEffect` with a dependency array `[count]` to ensure the log message appears only when `count` actually changes. This is a powerful pattern for managing side effects.",
    feedback_partial: "You've defined a `useEffect` hook, but without a dependency array, it will run after *every* render, which is often not what you want. Or, with an empty array, it will only run once. You need to specify `[count]` to react to changes in `count`.",
    feedback_wrong: "An empty dependency array `[]` tells `useEffect` to run only once after the initial render, like `componentDidMount`. To react to changes in `count`, you must include `count` in the dependency array.",
    expected: `import { useState, useEffect } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  const increment = () => {\n    setCount(prevCount => prevCount + 1);\n  };\n\n  const decrement = () => {\n    setCount(prevCount => prevCount - 1);\n  };\n\n  useEffect(() => {\n    console.log(\`Count changed to: \${count}\`);\n  }, [count]);\n\n  return (\n    <div>\n      <h1>Counter: {count}</h1>\n      <button onClick={increment}>Increment</button>\n      <button onClick={decrement}>Decrement</button>\n    </div>\n  );\n}`,
    analog_example: `// In plain JavaScript, reacting to a global variable change:\nlet globalStatus = 'idle';\n\nfunction setGlobalStatus(newStatus) {\n  globalStatus = newStatus;\n  // Manually trigger a reaction:\n  if (globalStatus === 'active') {\n    console.log('Global status is now active!');\n  }\n}\n\n// Usage:\n// setGlobalStatus('active');`,
    deepDiveLabel: "How does the `useEffect` dependency array work?",
    deepDive: {
      hook: `Imagine you have a smart light bulb that can change color. You want it to turn blue when the weather is rainy, and yellow when it's sunny. If you just tell it, "Check the weather and change color," it might check every second, even if the weather hasn't changed, wasting energy. Or, if you tell it, "Only check once when you're first turned on," it will never react to weather changes. \`useEffect\` without a dependency array is like checking constantly; \`useEffect\` with an empty array is like checking only once. What you need is to tell it, "Only check the weather and change color *if the weather actually changes*."`,
      pain: `⚠️ **Lesson:** Incorrectly configuring the \`useEffect\` dependency array leads to either excessive, unnecessary effect re-runs (performance issues) or effects not running when they should (stale data, broken functionality). Symptom: Infinite loops, slow UI, or data not updating when dependencies change.`,
      mentalModel: `**Mental model:** "The Effect's Watchlist." The dependency array \`[]\` passed as the second argument to \`useEffect\` is like a watchlist. React "watches" the values in this array between renders. If any value in the watchlist has changed since the last render, React re-runs your effect function. If the watchlist is empty (\`[]\`), it means "watch nothing," so the effect runs only once after the initial render. If the watchlist is omitted entirely, it means "watch everything," so the effect runs after *every* render. This mechanism gives you precise control over when your side effects execute.`,
      discover: `**Pattern - \`useEffect\` with Dependency Array:**\n\`\`\`tsx\nuseEffect(() => {\n  // Code for side effect (e.g., data fetching, DOM manipulation, subscriptions)\n  console.log('Effect ran!');\n\n  return () => {\n    // Optional cleanup function (e.g., unsubscribe, clear timers)\n    console.log('Cleanup ran!');\n  };\n}, [dependency1, dependency2]); // Dependency array\n\`\`\`\n-   \`useEffect\` takes two arguments: an effect function and an optional dependency array.\n-   The effect function runs after every render where one of its dependencies has changed.\n-   If the dependency array is \`[]\` (empty), the effect runs only once after the initial render (like \`componentDidMount\`).\n-   If the dependency array is omitted, the effect runs after *every* render.\n-   The effect function can optionally return a cleanup function, which runs before the component unmounts or before the effect re-runs due to changed dependencies.`,
      quickRules: `**Quick rules:**\n-   ✅ Include all values from the component's scope that the effect uses (props, state, functions) in the dependency array.\n-   ✅ Use an empty array \`[]\` for effects that should run only once on mount.\n-   ✅ Return a cleanup function for effects that subscribe to external data or set up timers.\n-   ✅ Place \`useEffect\` calls at the top level of your functional component.\n-   ❌ Omit the dependency array if you don't want the effect to run on every render.\n-   ❌ Forget to include a dependency in the array, leading to stale closures or missed updates.\n-   ❌ Include functions that are re-created on every render (unless memoized with \`useCallback\`) in the dependency array, causing unnecessary re-runs.`,
      watchOut: `👀 **Watch out:** A common mistake is to forget to include a dependency in the array. If your effect uses a variable (like \`count\` in our example) but you don't list it in the dependency array, the effect will "capture" the value of \`count\` from the render it first ran in, leading to stale data. For example, if \`count\` is \`0\` when the effect first runs with \`[]\`, it will always log \`0\`, even if \`count\` later becomes \`5\`. The React ESLint plugin is very helpful for catching these missing dependencies.`,
      dryRun: `🔁 **Think:**\n1.  **Initial Render:** \`count\` is \`0\`. \`useEffect\` runs. \`console.log(\`Count changed to: 0\`)\` is executed. The dependency array \`[count]\` is noted.\n2.  **User Clicks Increment:** \`setCount\` updates \`count\` to \`1\`. React schedules a re-render.\n3.  **Re-render:** \`count\` is now \`1\`. React compares \`count\` (\`1\`) with its previous value (\`0\`) in the dependency array. They are different.\n4.  \`useEffect\` runs again. \`console.log(\`Count changed to: 1\`)\` is executed. The dependency array \`[count]\` is updated to \`[1]\`.\n(Hint: The effect only re-runs if a value in its dependency array has changed since the last render.)`,
      build: `**Learning focus:** Implement \`useEffect\` to perform side effects that react to specific state changes within the component.`,
    },
  },
];

const sideItems = [
  { label: "Lesson", id: "intro" },
  { label: "Objectives", id: "objectives" },
  { label: "Imports", id: "step1" },
  { label: "Component Shell", id: "step2" },
  { label: "State with useState", id: "step3" },
  { label: "Structure Skeleton", id: "step4" },
  { label: "Handlers / Logic", id: "step5" },
  { label: "Wire Handlers", id: "step6" },
  { label: "Side Effect with useEffect", id: "step7" },
];

export default createINPACTEngine({
  NODES,
  sideItems,
  lessonNum: 0,
  title: "Managing Component State and Side Effects",
  shortName: "State & Effects",
});
