import createINPACTEngine from "../inpact_engine_shared";

const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #118", title: "Zustand Persist Middleware", body: "Builds on lesson 107: cross-session state persistence. Teaches the persist middleware, choosing localStorage vs sessionStorage, excluding sensitive keys (e.g. tokens) from persistence, and handling hydration mismatches on first load.", usecase: "Persist Zustand store." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Add persist middleware to store", "Choose storage (local vs session)", "Exclude sensitive keys", "Handle hydration mismatch"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Add persist middleware to your Zustand store with a storage adapter.", answer_keywords: ["persist", "zustand", "middleware"], seed_code: "import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add persist.", feedback_wrong: "Set up persist", expected: "Persist middleware" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Configure partial persist (exclude token or sensitive slice) and storage type.", answer_keywords: ["partialize", "localStorage", "sessionStorage"], seed_code: "import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Exclude keys.", feedback_wrong: "Partial persist", expected: "Exclude sensitive from persist" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Handle rehydrate or skip SSR hydration and export.", answer_keywords: ["export", "rehydrate"], seed_code: "import { create } from 'zustand'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #118 complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];

const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, lessonNum: 118, title: "Zustand Persist Middleware", shortName: "ZUSTAND PERSIST" });
