import createINPACTEngine from "../inpact_engine_shared";

const NODES = [
  { id: "intro", type: "reveal", phase: "Lesson", content: { tag: "LESSON #124", title: "Redux Toolkit — createSlice & createAsyncThunk", body: "Lesson 76 teaches Redux from scratch; this teaches how engineers use it in production. Covers createSlice, createAsyncThunk, builder callback for async states (pending/fulfilled/rejected), and RTK DevTools.", usecase: "RTK in production." } },
  { id: "objectives", type: "objectives", phase: "Objectives", items: ["Create slice with createSlice", "Add async thunk with createAsyncThunk", "Handle pending/fulfilled/rejected in builder", "Use RTK DevTools"] },
  { id: "step1", type: "question", phase: "Step 1 of 3", paal: "Create a slice with createSlice (name, initialState, reducers).", answer_keywords: ["createSlice", "reducers", "initialState"], seed_code: "import { createSlice } from '@reduxjs/toolkit'\n\nexport default function App() {\n  // Step 1\n}", feedback_correct: "✅ Step 1 done.", feedback_partial: "Add slice.", feedback_wrong: "Set up slice", expected: "createSlice" },
  { id: "step2", type: "question", phase: "Step 2 of 3", paal: "Add createAsyncThunk for a fetch and handle extraReducers with builder.addCase for pending/fulfilled/rejected.", answer_keywords: ["createAsyncThunk", "extraReducers", "builder"], seed_code: "import { createSlice, createAsyncThunk } from '@reduxjs/toolkit'\n\nexport default function App() {\n  // Step 2\n}", feedback_correct: "✅ Step 2 done.", feedback_partial: "Async thunk.", feedback_wrong: "Async thunk + cases", expected: "Thunk + extraReducers" },
  { id: "step3", type: "question", phase: "Step 3 of 3", paal: "Configure store and export.", answer_keywords: ["configureStore", "export", "Provider"], seed_code: "import { configureStore } from '@reduxjs/toolkit'\n\nexport default function App() {\n  // Step 3\n}", feedback_correct: "✅ Lesson #124 complete.", feedback_partial: "Export and finish.", feedback_wrong: "Export component", expected: "Complete" },
];

const sideItems = [{ label: "Lesson", id: "intro" }, { label: "Objectives", id: "objectives" }, { label: "Step 1", id: "step1" }, { label: "Step 2", id: "step2" }, { label: "Step 3", id: "step3" }];
export default createINPACTEngine({ NODES, sideItems, problemNum: 124, title: "Redux Toolkit — createSlice & createAsyncThunk", shortName: "RTK SLICE & THUNK" });
